import fs from "node:fs"; import path from "node:path";
const DIR = path.resolve("messages");
const add = {
  uk: { hEyebrow:"Готові моделі", hTitle:"Покрути в руках — ще до друку", hSubtitle:"Реальні моделі, надруковані з твоєї мапи. Обертай у 3D, обери район — і замов.", galleryTitle:"Галерея 3D-моделей для друку", allGallery:"Вся галерея", viewerDescHome:"Точна 3D-мапа: вулиці, будівлі, парки й вода в масштабі. Натисни на модель — відкриється на весь екран, крути й наближай.", createOwn:"Створити свій брелок" },
  en: { hEyebrow:"Ready models", hTitle:"Spin it in your hands — before printing", hSubtitle:"Real models printed from your map. Rotate in 3D, pick a district — and order.", galleryTitle:"Gallery of 3D models for printing", allGallery:"Full gallery", viewerDescHome:"A precise 3D map: streets, buildings, parks and water to scale. Tap the model to open it full-screen, rotate and zoom.", createOwn:"Create your keychain" },
  de: { hEyebrow:"Fertige Modelle", hTitle:"Dreh es in den Händen — vor dem Druck", hSubtitle:"Echte Modelle, gedruckt aus deiner Karte. In 3D drehen, ein Viertel wählen — und bestellen.", galleryTitle:"Galerie von 3D-Modellen zum Drucken", allGallery:"Ganze Galerie", viewerDescHome:"Eine präzise 3D-Karte: Straßen, Gebäude, Parks und Wasser maßstabsgetreu. Tippe auf das Modell für Vollbild, drehen und zoomen.", createOwn:"Anhänger erstellen" },
  pl: { hEyebrow:"Gotowe modele", hTitle:"Obróć w dłoniach — przed drukiem", hSubtitle:"Prawdziwe modele wydrukowane z Twojej mapy. Obróć w 3D, wybierz dzielnicę — i zamów.", galleryTitle:"Galeria modeli 3D do druku", allGallery:"Cała galeria", viewerDescHome:"Dokładna mapa 3D: ulice, budynki, parki i woda w skali. Kliknij model, aby otworzyć na pełnym ekranie, obracaj i przybliżaj.", createOwn:"Stwórz swój brelok" },
  fr: { hEyebrow:"Modèles prêts", hTitle:"Fais-le tourner — avant l'impression", hSubtitle:"De vrais modèles imprimés à partir de ta carte. Tourne en 3D, choisis un quartier — et commande.", galleryTitle:"Galerie de modèles 3D à imprimer", allGallery:"Toute la galerie", viewerDescHome:"Une carte 3D précise : rues, bâtiments, parcs et eau à l'échelle. Touche le modèle pour le plein écran, tourne et zoome.", createOwn:"Créer ton porte-clés" },
  es: { hEyebrow:"Modelos listos", hTitle:"Gíralo en tus manos — antes de imprimir", hSubtitle:"Modelos reales impresos desde tu mapa. Gira en 3D, elige un distrito — y pide.", galleryTitle:"Galería de modelos 3D para imprimir", allGallery:"Galería completa", viewerDescHome:"Un mapa 3D preciso: calles, edificios, parques y agua a escala. Toca el modelo para pantalla completa, gira y acerca.", createOwn:"Crea tu llavero" },
};
for (const loc of ["uk","en","de","pl","fr","es"]) { const f=path.join(DIR,`${loc}.json`); const j=JSON.parse(fs.readFileSync(f,"utf8")); j.showcase={...(j.showcase||{}),...add[loc]}; fs.writeFileSync(f,JSON.stringify(j,null,2)+"\n","utf8"); }
console.log("done");
