import fs from "node:fs"; import path from "node:path";
const DIR = path.resolve("messages");
const data = {
  order: {
    uk: { errName:"Вкажіть ім'я", errPhone:"Вкажіть телефон", errNova:"Вкажіть місто та № відділення", errUkr:"Вкажіть місто та індекс", sendFail:"Не вдалося відправити замовлення. Спробуйте ще раз.", acceptedTitle:"Замовлення прийнято!", orderNo:"Номер замовлення", acceptedText:"Ми зв'яжемося з вами найближчим часом для підтвердження та оплати.", doneBtn:"Готово", title:"Замовити друк", prodKeychain:"Брелок з мапою", prodMap:"3D-мапа", phName:"Ім'я та прізвище", phPhone:"Телефон (+380…)", phCity:"Місто", phNova:"№ відділення / поштомату", phUkr:"Поштовий індекс", phAddress:"Адреса (вулиця, будинок)", phComment:"Коментар (необов'язково)", nova:"Нова Пошта", ukr:"Укрпошта", pickup:"Самовивіз", paymentNote:"Оплата узгоджується після підтвердження замовлення. Ваш дизайн і модель додаються автоматично.", sending:"Відправляємо…", submit:"Оформити замовлення" },
    en: { errName:"Enter your name", errPhone:"Enter a phone number", errNova:"Enter city and branch №", errUkr:"Enter city and postcode", sendFail:"Couldn't send the order. Please try again.", acceptedTitle:"Order received!", orderNo:"Order number", acceptedText:"We'll contact you shortly to confirm and arrange payment.", doneBtn:"Done", title:"Order printing", prodKeychain:"Map keychain", prodMap:"3D map", phName:"Full name", phPhone:"Phone (+380…)", phCity:"City", phNova:"Branch / parcel locker №", phUkr:"Postcode", phAddress:"Address (street, building)", phComment:"Comment (optional)", nova:"Nova Poshta", ukr:"Ukrposhta", pickup:"Pickup", paymentNote:"Payment is arranged after the order is confirmed. Your design and model are attached automatically.", sending:"Sending…", submit:"Place order" },
    de: { errName:"Namen eingeben", errPhone:"Telefonnummer eingeben", errNova:"Stadt und Filial-Nr. angeben", errUkr:"Stadt und PLZ angeben", sendFail:"Bestellung konnte nicht gesendet werden. Bitte erneut versuchen.", acceptedTitle:"Bestellung erhalten!", orderNo:"Bestellnummer", acceptedText:"Wir melden uns in Kürze zur Bestätigung und Zahlung.", doneBtn:"Fertig", title:"Druck bestellen", prodKeychain:"Karten-Anhänger", prodMap:"3D-Karte", phName:"Vor- und Nachname", phPhone:"Telefon (+380…)", phCity:"Stadt", phNova:"Filiale / Paketstation Nr.", phUkr:"Postleitzahl", phAddress:"Adresse (Straße, Hausnr.)", phComment:"Kommentar (optional)", nova:"Nova Poshta", ukr:"Ukrposhta", pickup:"Selbstabholung", paymentNote:"Die Zahlung wird nach Bestätigung der Bestellung vereinbart. Dein Design und Modell werden automatisch angehängt.", sending:"Senden…", submit:"Bestellen" },
    pl: { errName:"Podaj imię", errPhone:"Podaj numer telefonu", errNova:"Podaj miasto i nr oddziału", errUkr:"Podaj miasto i kod pocztowy", sendFail:"Nie udało się wysłać zamówienia. Spróbuj ponownie.", acceptedTitle:"Zamówienie przyjęte!", orderNo:"Numer zamówienia", acceptedText:"Skontaktujemy się wkrótce, aby potwierdzić i ustalić płatność.", doneBtn:"Gotowe", title:"Zamów druk", prodKeychain:"Brelok z mapą", prodMap:"Mapa 3D", phName:"Imię i nazwisko", phPhone:"Telefon (+380…)", phCity:"Miasto", phNova:"Nr oddziału / paczkomatu", phUkr:"Kod pocztowy", phAddress:"Adres (ulica, numer)", phComment:"Komentarz (opcjonalnie)", nova:"Nova Poshta", ukr:"Ukrposhta", pickup:"Odbiór osobisty", paymentNote:"Płatność ustalana po potwierdzeniu zamówienia. Twój projekt i model dołączane są automatycznie.", sending:"Wysyłanie…", submit:"Złóż zamówienie" },
    fr: { errName:"Indique ton nom", errPhone:"Indique un numéro de téléphone", errNova:"Indique la ville et le n° d'agence", errUkr:"Indique la ville et le code postal", sendFail:"Échec de l'envoi de la commande. Réessaie.", acceptedTitle:"Commande reçue !", orderNo:"Numéro de commande", acceptedText:"Nous te contacterons bientôt pour confirmer et organiser le paiement.", doneBtn:"Terminé", title:"Commander l'impression", prodKeychain:"Porte-clés carte", prodMap:"Carte 3D", phName:"Nom et prénom", phPhone:"Téléphone (+380…)", phCity:"Ville", phNova:"N° d'agence / point relais", phUkr:"Code postal", phAddress:"Adresse (rue, numéro)", phComment:"Commentaire (facultatif)", nova:"Nova Poshta", ukr:"Ukrposhta", pickup:"Retrait", paymentNote:"Le paiement est convenu après confirmation de la commande. Ton design et ton modèle sont joints automatiquement.", sending:"Envoi…", submit:"Commander" },
    es: { errName:"Indica tu nombre", errPhone:"Indica un teléfono", errNova:"Indica ciudad y n.º de sucursal", errUkr:"Indica ciudad y código postal", sendFail:"No se pudo enviar el pedido. Inténtalo de nuevo.", acceptedTitle:"¡Pedido recibido!", orderNo:"Número de pedido", acceptedText:"Te contactaremos pronto para confirmar y gestionar el pago.", doneBtn:"Listo", title:"Pedir impresión", prodKeychain:"Llavero con mapa", prodMap:"Mapa 3D", phName:"Nombre y apellidos", phPhone:"Teléfono (+380…)", phCity:"Ciudad", phNova:"N.º de sucursal / casillero", phUkr:"Código postal", phAddress:"Dirección (calle, número)", phComment:"Comentario (opcional)", nova:"Nova Poshta", ukr:"Ukrposhta", pickup:"Recogida", paymentNote:"El pago se acuerda tras confirmar el pedido. Tu diseño y modelo se adjuntan automáticamente.", sending:"Enviando…", submit:"Hacer pedido" },
  },
  contact: {
    uk: { errPhone:"Вкажіть телефон", sendFail:"Не вдалося відправити. Спробуйте ще раз.", thanks:"Дякуємо!", thanksText:"Ми зв'яжемося з вами найближчим часом.", close:"Закрити", title:"Звʼязатися з нами", subtitle:"Залиште телефон — ми напишемо вам.", phName:"Ім'я (необовʼязково)", phPhone:"Телефон (+380…)", phMessage:"Повідомлення (необовʼязково)", sending:"Надсилаємо…", send:"Надіслати" },
    en: { errPhone:"Enter a phone number", sendFail:"Couldn't send. Please try again.", thanks:"Thank you!", thanksText:"We'll get in touch with you shortly.", close:"Close", title:"Contact us", subtitle:"Leave your phone — we'll write to you.", phName:"Name (optional)", phPhone:"Phone (+380…)", phMessage:"Message (optional)", sending:"Sending…", send:"Send" },
    de: { errPhone:"Telefonnummer eingeben", sendFail:"Senden fehlgeschlagen. Bitte erneut versuchen.", thanks:"Danke!", thanksText:"Wir melden uns in Kürze bei dir.", close:"Schließen", title:"Kontaktiere uns", subtitle:"Hinterlasse deine Nummer — wir schreiben dir.", phName:"Name (optional)", phPhone:"Telefon (+380…)", phMessage:"Nachricht (optional)", sending:"Senden…", send:"Senden" },
    pl: { errPhone:"Podaj numer telefonu", sendFail:"Nie udało się wysłać. Spróbuj ponownie.", thanks:"Dziękujemy!", thanksText:"Skontaktujemy się z Tobą wkrótce.", close:"Zamknij", title:"Skontaktuj się z nami", subtitle:"Zostaw telefon — napiszemy do Ciebie.", phName:"Imię (opcjonalnie)", phPhone:"Telefon (+380…)", phMessage:"Wiadomość (opcjonalnie)", sending:"Wysyłanie…", send:"Wyślij" },
    fr: { errPhone:"Indique un numéro de téléphone", sendFail:"Échec de l'envoi. Réessaie.", thanks:"Merci !", thanksText:"Nous te contacterons bientôt.", close:"Fermer", title:"Contacte-nous", subtitle:"Laisse ton téléphone — nous t'écrirons.", phName:"Nom (facultatif)", phPhone:"Téléphone (+380…)", phMessage:"Message (facultatif)", sending:"Envoi…", send:"Envoyer" },
    es: { errPhone:"Indica un teléfono", sendFail:"No se pudo enviar. Inténtalo de nuevo.", thanks:"¡Gracias!", thanksText:"Nos pondremos en contacto contigo pronto.", close:"Cerrar", title:"Contáctanos", subtitle:"Deja tu teléfono — te escribiremos.", phName:"Nombre (opcional)", phPhone:"Teléfono (+380…)", phMessage:"Mensaje (opcional)", sending:"Enviando…", send:"Enviar" },
  },
};
for (const loc of ["uk","en","de","pl","fr","es"]) { const f=path.join(DIR,`${loc}.json`); const j=JSON.parse(fs.readFileSync(f,"utf8")); for(const ns of Object.keys(data)) j[ns]={...(j[ns]||{}),...data[ns][loc]}; fs.writeFileSync(f,JSON.stringify(j,null,2)+"\n","utf8"); }
console.log("done");
