// Картки-рендери (18.09.2026): ціна «за запитом» для гір/світів + 4 нові форми брелків.
import fs from "node:fs"; import path from "node:path";
const DIR = path.resolve("messages");
const scenario = { uk: { priceOnRequest: "ціна за запитом" }, en: { priceOnRequest: "price on request" }, de: { priceOnRequest: "Preis auf Anfrage" }, pl: { priceOnRequest: "cena na zapytanie" }, fr: { priceOnRequest: "prix sur demande" }, es: { priceOnRequest: "precio a consultar" } };
const kc = {
  uk: { cardHouseTitle: "Будиночок HOME", cardHouseDesc: "Силует дому з мапою вашого району й написом", cardPuzzleTitle: "Пазл для двох", cardPuzzleDesc: "Дві половинки-пазли: ваше місто й місто близької людини", cardCapsuleTitle: "Капсула зі щілиною", cardCapsuleDesc: "Овальний брелок 55×35 з широкою смугою для напису", cardTagTitle: "Вертикальний тег", cardTagDesc: "Тонкий тег 35×55 з виступним вушком" },
  en: { cardHouseTitle: "HOME house", cardHouseDesc: "House silhouette with your district map and a label", cardPuzzleTitle: "Puzzle for two", cardPuzzleDesc: "Two puzzle halves: your city and a loved one's city", cardCapsuleTitle: "Capsule with slot", cardCapsuleDesc: "Oval 55×35 keychain with a wide label band", cardTagTitle: "Vertical tag", cardTagDesc: "Slim 35×55 tag with a protruding loop" },
  de: { cardHouseTitle: "Häuschen HOME", cardHouseDesc: "Haus-Silhouette mit Karte deines Viertels und Schriftzug", cardPuzzleTitle: "Puzzle für zwei", cardPuzzleDesc: "Zwei Puzzlehälften: deine Stadt und die eines lieben Menschen", cardCapsuleTitle: "Kapsel mit Schlitz", cardCapsuleDesc: "Ovaler 55×35-Anhänger mit breitem Schriftband", cardTagTitle: "Vertikaler Tag", cardTagDesc: "Schlanker 35×55-Tag mit vorstehender Öse" },
  pl: { cardHouseTitle: "Domek HOME", cardHouseDesc: "Sylwetka domu z mapą Twojej dzielnicy i napisem", cardPuzzleTitle: "Puzzle dla dwojga", cardPuzzleDesc: "Dwie połówki puzzli: Twoje miasto i miasto bliskiej osoby", cardCapsuleTitle: "Kapsuła ze szczeliną", cardCapsuleDesc: "Owalny brelok 55×35 z szerokim pasem na napis", cardTagTitle: "Pionowy tag", cardTagDesc: "Smukły tag 35×55 z wystającym oczkiem" },
  fr: { cardHouseTitle: "Maisonnette HOME", cardHouseDesc: "Silhouette de maison avec la carte de votre quartier et un texte", cardPuzzleTitle: "Puzzle pour deux", cardPuzzleDesc: "Deux moitiés de puzzle : votre ville et celle d'un proche", cardCapsuleTitle: "Capsule à fente", cardCapsuleDesc: "Porte-clés ovale 55×35 avec large bande de texte", cardTagTitle: "Tag vertical", cardTagDesc: "Tag fin 35×55 avec anneau saillant" },
  es: { cardHouseTitle: "Casita HOME", cardHouseDesc: "Silueta de casa con el mapa de tu barrio y un texto", cardPuzzleTitle: "Puzle para dos", cardPuzzleDesc: "Dos mitades de puzle: tu ciudad y la de alguien querido", cardCapsuleTitle: "Cápsula con ranura", cardCapsuleDesc: "Llavero ovalado 55×35 con banda ancha para texto", cardTagTitle: "Etiqueta vertical", cardTagDesc: "Etiqueta fina 35×55 con anilla saliente" },
};
for (const loc of ["uk","en","de","pl","fr","es"]) { const f=path.join(DIR,`${loc}.json`); const j=JSON.parse(fs.readFileSync(f,"utf8")); j.scenario={...j.scenario,...scenario[loc]}; j.kcScenario={...j.kcScenario,...kc[loc]}; fs.writeFileSync(f,JSON.stringify(j,null,2)+"\n","utf8"); }
console.log("done");
