// Режим «Гори» + агент (18.09.2026). Запуск: node scripts/i18n_merge_mountains.mjs (з frontend/).
import fs from "node:fs"; import path from "node:path";
const DIR = path.resolve("messages");
const L = ["uk", "en", "de", "pl", "fr", "es"];

const mountains = {
  uk: { badge: "Реальні гори · бета", title: "3D-модель будь-якої гори світу", subtitle: "Оберіть вершину або точку на мапі — отримаєте друковану модель зі справжнього рельєфу (лідар 2 м для Швейцарії, Copernicus 30 м для світу), з ободком, скельними боками та фігурками.",
    tabsAria: "Режими", tabPresets: "Відомі вершини", tabMap: "Обрати на мапі", tabWorlds: "Світи з опису",
    agentPlaceholder: "Наприклад: «Говерла 20 см, заокруглений ободок, скелелаз на стіні й хатина»", agentEx1: "Матергорн 25 см з заокругленим ободком і людиною на вершині", agentEx2: "Говерла 15×15 см без ободка, похилі боки, хатина", agentEx3: "Монблан 30 см висотою 12 см, скельні боки, 2 людей",
    step1: "1 · Місце", mapHint: "Клікніть по мапі — центр моделі. Маркер можна перетягнути. Квадрат показує ділянку.", areaLabel: "Ділянка", areaHint: "Для окремої вершини 3–6 км; для масиву 8–20 км. Що менша ділянка, то крутіша й вища гора на моделі.",
    sizeLabel: "Розмір плити", sizeCustom: "інший", sizeOne: "Друкується однією деталлю.", sizeTiles: "Більше за стіл {bed} мм — поріжу на плитки, які стикуються без щілин.",
    heightLabel: "Висота моделі", heightAuto: "природна", heightInfo: "Перепад {relief} м = {natural} мм у масштабі 1:{scale}", zexag: "вертикаль ×{k}",
    frameLabel: "Ободок", frame_none: "без ободка", frame_flat: "плаский з фаскою", frame_rounded: "заокруглений", frameWidth: "Ширина", frameHeight: "Висота",
    sidesLabel: "Боки", sides_slope: "похилі скельні", sides_rock: "скельні стінки", sides_vertical: "рівний зріз",
    sidesHint_slope: "Рельєф плавно спускається до ободка справжнім схилом з осипом — без підтримок.", sidesHint_rock: "Вертикальні стінки з ребрами й жолобами до 6 мм — як розріз скелі.", sidesHint_vertical: "Гладкий вертикальний зріз, як у класичних рельєфних мап.",
    figuresLabel: "Фігурки", figuresHint: "Фігурки не в масштабі гори (людина була б 0,2 мм) — вони сувенірні: ~8 % ширини плити. Скелелаз сам знаходить найкрутішу стіну біля вершини.",
    where_summit: "на вершині", where_steepest: "на крутій стіні", where_slope: "на пологому схилі", where_point: "у точці", pickPoint: "вказати на превʼю", pickPointHint: "Клікніть по превʼю, де поставити фігурку", figHeight: "висота", remove: "Прибрати",
    textureLabel: "Супутникова текстура для превʼю та гайду розпису", generateButton: "Згенерувати гору", generating: "Генерую…", starting: "Запускаю…", needPlace: "Спершу оберіть вершину або точку на мапі.",
    hint: "Модель герметична й друкується без підтримок. Джерела висот: swissALTI3D 2 м (Швейцарія), Copernicus GLO-30 (світ). Знімок: Esri World Imagery.",
    previewTitle: "Превʼю ділянки", previewAlt: "Тіньова карта висот обраної ділянки", previewEmpty: "Оберіть вершину чи точку на мапі — тут одразу зʼявиться превʼю рельєфу.", previewFailed: "Не вдалося отримати висоти для цієї ділянки.",
    previewStats: "{min}–{max} м · 1:{scale}", builtAs: "{place} · 1:{scale} · {height} мм · вертикаль ×{zexag}", tilesCount: "{n} плиток",
    downloadPrint: "Друк-файл 3MF", downloadTiles: "Плитки для стола (ZIP)", photoTop: "Фото зверху", paintGuide: "Гайд розпису", downloadGlb: "GLB для перегляду", editAgain: "Змінити параметри",
    orderTitle: "Замовити друк цієї гори", orderSub: "Ціна залежить від розміру й фігурок — напишіть нам, опис і посилання на 3D вже скопійовані.", shareLink: "Поділитися посиланням", shareCopied: "Посилання скопійовано", msgCopied: "Опис скопійовано — вставте його в чат.",
    msgPrefill: "Вітаю! Хочу надрукувати 3D-модель гори: {place}, плита {size} мм. 3D-перегляд: {link}", genFailed: "Не вдалося згенерувати модель. Спробуйте меншу ділянку або інше місце." },
  en: { badge: "Real mountains · beta", title: "3D model of any mountain on Earth", subtitle: "Pick a summit or a point on the map and get a printable model from real elevation data (2 m lidar for Switzerland, Copernicus 30 m worldwide) with a rim, rocky sides and figures.",
    tabsAria: "Modes", tabPresets: "Famous peaks", tabMap: "Pick on the map", tabWorlds: "Worlds from a description",
    agentPlaceholder: "E.g. “Matterhorn 25 cm, rounded rim, a climber on the wall and a hut”", agentEx1: "Matterhorn 25 cm with a rounded rim and a person on the summit", agentEx2: "Hoverla 15×15 cm, no rim, sloped sides, a hut", agentEx3: "Mont Blanc 30 cm, 12 cm tall, rocky sides, 2 people",
    step1: "1 · Place", mapHint: "Click the map to set the model centre. Drag the marker to adjust. The square is the area.", areaLabel: "Area", areaHint: "3–6 km for a single peak; 8–20 km for a massif. Smaller area → steeper, taller mountain.",
    sizeLabel: "Plate size", sizeCustom: "other", sizeOne: "Prints as one piece.", sizeTiles: "Larger than the {bed} mm bed — split into tiles that join seamlessly.",
    heightLabel: "Model height", heightAuto: "natural", heightInfo: "Relief {relief} m = {natural} mm at 1:{scale}", zexag: "vertical ×{k}",
    frameLabel: "Rim", frame_none: "no rim", frame_flat: "flat with chamfer", frame_rounded: "rounded", frameWidth: "Width", frameHeight: "Height",
    sidesLabel: "Sides", sides_slope: "sloped rock", sides_rock: "rock walls", sides_vertical: "flat cut",
    sidesHint_slope: "Terrain descends to the rim as a real slope with scree — no supports.", sidesHint_rock: "Vertical walls with ribs and gullies up to 6 mm deep — like a rock cross-section.", sidesHint_vertical: "Smooth vertical cut, as in classic relief maps.",
    figuresLabel: "Figures", figuresHint: "Figures are not to mountain scale (a person would be 0.2 mm) — they are souvenirs: ~8 % of plate width. The climber finds the steepest wall near the summit by itself.",
    where_summit: "on the summit", where_steepest: "on a steep wall", where_slope: "on a gentle slope", where_point: "at a point", pickPoint: "pick on preview", pickPointHint: "Click the preview where the figure should stand", figHeight: "height", remove: "Remove",
    textureLabel: "Satellite texture for preview and paint guide", generateButton: "Generate mountain", generating: "Generating…", starting: "Starting…", needPlace: "Pick a summit or a map point first.",
    hint: "The model is watertight and prints without supports. Elevation: swissALTI3D 2 m (Switzerland), Copernicus GLO-30 (world). Imagery: Esri World Imagery.",
    previewTitle: "Area preview", previewAlt: "Hillshade of the selected area", previewEmpty: "Pick a summit or a map point — the terrain preview appears here instantly.", previewFailed: "Could not fetch elevation for this area.",
    previewStats: "{min}–{max} m · 1:{scale}", builtAs: "{place} · 1:{scale} · {height} mm · vertical ×{zexag}", tilesCount: "{n} tiles",
    downloadPrint: "Print file 3MF", downloadTiles: "Bed tiles (ZIP)", photoTop: "Top photo", paintGuide: "Paint guide", downloadGlb: "GLB to view", editAgain: "Change settings",
    orderTitle: "Order a print of this mountain", orderSub: "Price depends on size and figures — message us; the description and 3D link are already copied.", shareLink: "Share link", shareCopied: "Link copied", msgCopied: "Description copied — paste it into the chat.",
    msgPrefill: "Hi! I'd like a 3D print of a mountain: {place}, plate {size} mm. 3D view: {link}", genFailed: "Generation failed. Try a smaller area or another place." },
};
// de/pl/fr/es — переклад з en (короткі UI-рядки)
mountains.de = { ...mountains.en, badge: "Echte Berge · Beta", title: "3D-Modell jedes Berges der Welt", subtitle: "Gipfel oder Kartenpunkt wählen — druckbares Modell aus echten Höhendaten (2-m-Lidar Schweiz, Copernicus 30 m weltweit) mit Rand, Felsflanken und Figuren.", tabPresets: "Bekannte Gipfel", tabMap: "Auf der Karte wählen", tabWorlds: "Welten aus Beschreibung", step1: "1 · Ort", areaLabel: "Gebiet", sizeLabel: "Plattengröße", heightLabel: "Modellhöhe", heightAuto: "natürlich", frameLabel: "Rand", frame_none: "ohne Rand", frame_flat: "flach mit Fase", frame_rounded: "abgerundet", frameWidth: "Breite", frameHeight: "Höhe", sidesLabel: "Seiten", sides_slope: "geneigter Fels", sides_rock: "Felswände", sides_vertical: "glatter Schnitt", figuresLabel: "Figuren", generateButton: "Berg generieren", generating: "Generiere…", downloadPrint: "Druckdatei 3MF", orderTitle: "Druck dieses Berges bestellen", editAgain: "Einstellungen ändern", previewTitle: "Vorschau", needPlace: "Zuerst Gipfel oder Kartenpunkt wählen." };
mountains.pl = { ...mountains.en, badge: "Prawdziwe góry · beta", title: "Model 3D dowolnej góry świata", subtitle: "Wybierz szczyt lub punkt na mapie — otrzymasz model do druku z prawdziwych danych wysokości (lidar 2 m Szwajcaria, Copernicus 30 m świat) z obrzeżem, skalnymi bokami i figurkami.", tabPresets: "Znane szczyty", tabMap: "Wybierz na mapie", tabWorlds: "Światy z opisu", step1: "1 · Miejsce", areaLabel: "Obszar", sizeLabel: "Rozmiar płyty", heightLabel: "Wysokość modelu", heightAuto: "naturalna", frameLabel: "Obrzeże", frame_none: "bez obrzeża", frame_flat: "płaskie z fazą", frame_rounded: "zaokrąglone", frameWidth: "Szerokość", frameHeight: "Wysokość", sidesLabel: "Boki", sides_slope: "pochyła skała", sides_rock: "ściany skalne", sides_vertical: "gładkie cięcie", figuresLabel: "Figurki", generateButton: "Wygeneruj górę", generating: "Generowanie…", downloadPrint: "Plik do druku 3MF", orderTitle: "Zamów wydruk tej góry", editAgain: "Zmień ustawienia", previewTitle: "Podgląd", needPlace: "Najpierw wybierz szczyt lub punkt na mapie." };
mountains.fr = { ...mountains.en, badge: "Vraies montagnes · bêta", title: "Modèle 3D de n'importe quelle montagne", subtitle: "Choisissez un sommet ou un point sur la carte — modèle imprimable à partir de vraies altitudes (lidar 2 m Suisse, Copernicus 30 m monde) avec bordure, flancs rocheux et figurines.", tabPresets: "Sommets connus", tabMap: "Choisir sur la carte", tabWorlds: "Mondes décrits", step1: "1 · Lieu", areaLabel: "Zone", sizeLabel: "Taille de la plaque", heightLabel: "Hauteur du modèle", heightAuto: "naturelle", frameLabel: "Bordure", frame_none: "sans bordure", frame_flat: "plate chanfreinée", frame_rounded: "arrondie", frameWidth: "Largeur", frameHeight: "Hauteur", sidesLabel: "Flancs", sides_slope: "roche inclinée", sides_rock: "parois rocheuses", sides_vertical: "coupe lisse", figuresLabel: "Figurines", generateButton: "Générer la montagne", generating: "Génération…", downloadPrint: "Fichier 3MF", orderTitle: "Commander l'impression", editAgain: "Modifier les réglages", previewTitle: "Aperçu", needPlace: "Choisissez d'abord un sommet ou un point." };
mountains.es = { ...mountains.en, badge: "Montañas reales · beta", title: "Modelo 3D de cualquier montaña del mundo", subtitle: "Elige una cima o un punto en el mapa: modelo imprimible con altitudes reales (lidar 2 m Suiza, Copernicus 30 m mundial) con borde, laderas rocosas y figuras.", tabPresets: "Cimas famosas", tabMap: "Elegir en el mapa", tabWorlds: "Mundos por descripción", step1: "1 · Lugar", areaLabel: "Zona", sizeLabel: "Tamaño de la placa", heightLabel: "Altura del modelo", heightAuto: "natural", frameLabel: "Borde", frame_none: "sin borde", frame_flat: "plano con chaflán", frame_rounded: "redondeado", frameWidth: "Ancho", frameHeight: "Alto", sidesLabel: "Lados", sides_slope: "roca inclinada", sides_rock: "paredes rocosas", sides_vertical: "corte liso", figuresLabel: "Figuras", generateButton: "Generar montaña", generating: "Generando…", downloadPrint: "Archivo 3MF", orderTitle: "Pedir la impresión", editAgain: "Cambiar ajustes", previewTitle: "Vista previa", needPlace: "Elige primero una cima o un punto." };

const agent = {
  uk: { title: "Агент: опишіть словами", hint: "Я розберу опис, покажу, як зрозумів, і лише після вашого «Застосувати» заповню форму. Генерацію запускаєте ви.", understand: "Зрозуміти", thinking: "Розбираю…", understood: "Як я зрозумів", confidence: "впевненість {pct} %", srcRules: "за ключовими словами", srcUser: "ваш вибір", apply: "Застосувати до форми", applied: "Застосовано ✓", applyHint: "Перевірте значення у формі й натисніть «Згенерувати».", failed: "Агент не відповів. Заповніть форму вручну." },
  en: { title: "Agent: describe it in words", hint: "I parse the description, show how I understood it, and fill the form only after you click Apply. You start the generation.", understand: "Understand", thinking: "Parsing…", understood: "How I understood it", confidence: "confidence {pct} %", srcRules: "by keywords", srcUser: "your choice", apply: "Apply to form", applied: "Applied ✓", applyHint: "Check the values in the form and press Generate.", failed: "The agent did not respond. Fill the form manually." },
  de: { title: "Agent: in Worten beschreiben", hint: "Ich analysiere die Beschreibung, zeige mein Verständnis und fülle das Formular erst nach „Übernehmen“. Du startest die Generierung.", understand: "Verstehen", thinking: "Analysiere…", understood: "So habe ich es verstanden", confidence: "Sicherheit {pct} %", srcRules: "nach Stichwörtern", srcUser: "deine Wahl", apply: "Ins Formular übernehmen", applied: "Übernommen ✓", applyHint: "Werte prüfen und „Generieren“ drücken.", failed: "Der Agent antwortet nicht. Bitte manuell ausfüllen." },
  pl: { title: "Agent: opisz słowami", hint: "Przeanalizuję opis, pokażę jak go rozumiem i wypełnię formularz dopiero po „Zastosuj”. Generowanie uruchamiasz Ty.", understand: "Zrozum", thinking: "Analizuję…", understood: "Jak to zrozumiałem", confidence: "pewność {pct} %", srcRules: "po słowach kluczowych", srcUser: "Twój wybór", apply: "Zastosuj do formularza", applied: "Zastosowano ✓", applyHint: "Sprawdź wartości i naciśnij „Generuj”.", failed: "Agent nie odpowiedział. Wypełnij formularz ręcznie." },
  fr: { title: "Agent : décrivez en mots", hint: "J'analyse la description, je montre ma compréhension et je remplis le formulaire seulement après « Appliquer ». C'est vous qui lancez la génération.", understand: "Comprendre", thinking: "Analyse…", understood: "Ce que j'ai compris", confidence: "confiance {pct} %", srcRules: "par mots-clés", srcUser: "votre choix", apply: "Appliquer au formulaire", applied: "Appliqué ✓", applyHint: "Vérifiez les valeurs puis « Générer ».", failed: "L'agent n'a pas répondu. Remplissez manuellement." },
  es: { title: "Agente: descríbelo con palabras", hint: "Analizo la descripción, muestro cómo la entendí y relleno el formulario solo tras «Aplicar». Tú inicias la generación.", understand: "Entender", thinking: "Analizando…", understood: "Cómo lo entendí", confidence: "confianza {pct} %", srcRules: "por palabras clave", srcUser: "tu elección", apply: "Aplicar al formulario", applied: "Aplicado ✓", applyHint: "Revisa los valores y pulsa «Generar».", failed: "El agente no respondió. Rellena el formulario a mano." },
};

const mountainsMeta = {
  uk: { title: "3D-модель гори з реального рельєфу — Матергорн, Говерла, будь-яка вершина", description: "Оберіть вершину або точку на мапі: друкована 3D-модель гори зі справжніх висот (лідар 2 м, Copernicus 30 м), з ободком, скельними боками й фігурками альпіністів.", keywords: "3D модель гори, рельєфна модель, Матергорн 3D, Говерла 3D, топографічна модель, 3D друк гори",
    proseH2: "Як створюється модель гори", proseP1: "Ми беремо реальні дані висот (лазерне сканування swissALTI3D з кроком 2 м для Швейцарії та глобальну модель Copernicus GLO-30) і будуємо герметичне тіло: рельєф, скельні боки, ободок і низ — одним обʼєктом, що друкується без підтримок. Плити більші за стіл принтера ріжуться на плитки, які стикуються без щілин.", proseP2: "Фігурки альпінистів і хатини сідають на рельєф автоматично: скелелаз знаходить найкрутішу стіну біля вершини, людина стає на вирівняний майданчик, хатина — на пологому схилі. Супутниковий знімок дає фото-превʼю та гайд для розпису фарбами." },
  en: { title: "3D mountain model from real terrain — Matterhorn, Hoverla, any peak", description: "Pick a summit or a map point: a printable 3D mountain from real elevation (2 m lidar, Copernicus 30 m) with a rim, rocky sides and climber figures.", keywords: "3D mountain model, relief model, Matterhorn 3D, topographic model, 3D print mountain",
    proseH2: "How the mountain model is made", proseP1: "We take real elevation data (swissALTI3D 2 m lidar for Switzerland and the global Copernicus GLO-30 model) and build a watertight solid: terrain, rocky sides, rim and bottom as one object that prints without supports. Plates larger than the printer bed are split into seamless tiles.", proseP2: "Climber figures and huts are placed automatically: the climber finds the steepest wall near the summit, the hiker stands on a levelled spot, the hut sits on a gentle slope. Satellite imagery gives a photo preview and a painting guide." },
};
mountainsMeta.de = { ...mountainsMeta.en, title: "3D-Bergmodell aus echtem Gelände — Matterhorn, Hoverla, jeder Gipfel", description: "Gipfel oder Kartenpunkt wählen: druckbares 3D-Bergmodell aus echten Höhen (2-m-Lidar, Copernicus 30 m) mit Rand, Felsflanken und Bergsteigerfiguren." };
mountainsMeta.pl = { ...mountainsMeta.en, title: "Model 3D góry z prawdziwego terenu — Matterhorn, Howerla, dowolny szczyt", description: "Wybierz szczyt lub punkt na mapie: model 3D góry do druku z prawdziwych wysokości (lidar 2 m, Copernicus 30 m) z obrzeżem, skalnymi bokami i figurkami wspinaczy." };
mountainsMeta.fr = { ...mountainsMeta.en, title: "Modèle 3D de montagne à partir du vrai relief — Cervin, Hoverla, tout sommet", description: "Choisissez un sommet ou un point sur la carte : modèle 3D imprimable à partir de vraies altitudes (lidar 2 m, Copernicus 30 m) avec bordure, flancs rocheux et figurines d'alpinistes." };
mountainsMeta.es = { ...mountainsMeta.en, title: "Modelo 3D de montaña con relieve real — Cervino, Hoverla, cualquier cima", description: "Elige una cima o un punto del mapa: modelo 3D imprimible con altitudes reales (lidar 2 m, Copernicus 30 m) con borde, laderas rocosas y figuras de alpinistas." };

const nav = { uk: "Гори", en: "Mountains", de: "Berge", pl: "Góry", fr: "Montagnes", es: "Montañas" };
const beta = { uk: "Реальний рельєф зі swissALTI3D / Copernicus; фігурки сувенірні, не в масштабі. Для друку чи замовлення напишіть нам — порахуємо ціну окремо.",
  en: "Real terrain from swissALTI3D / Copernicus; figures are souvenir-scale. For printing or ordering, message us — we quote separately.",
  de: "Echtes Gelände aus swissALTI3D / Copernicus; Figuren im Souvenirmaßstab. Für Druck oder Bestellung schreib uns.",
  pl: "Prawdziwy teren ze swissALTI3D / Copernicus; figurki w skali pamiątkowej. Druk lub zamówienie — napisz do nas.",
  fr: "Vrai relief swissALTI3D / Copernicus ; figurines à l'échelle souvenir. Pour imprimer ou commander, écrivez-nous.",
  es: "Relieve real de swissALTI3D / Copernicus; figuras a escala de recuerdo. Para imprimir o pedir, escríbenos." };
const worldsAgent = { uk: { agentPlaceholder: "Опишіть світ словами — я скажу, яку форму й висоту зроблю", agentApplied: "Форму та розмір узято з опису" }, en: { agentPlaceholder: "Describe the world — I'll tell you the shape and height I'll build", agentApplied: "Shape and size taken from the description" },
  de: { agentPlaceholder: "Beschreibe die Welt — ich sage dir Form und Höhe", agentApplied: "Form und Größe aus der Beschreibung" }, pl: { agentPlaceholder: "Opisz świat — powiem, jaki kształt i wysokość zbuduję", agentApplied: "Kształt i rozmiar z opisu" },
  fr: { agentPlaceholder: "Décrivez le monde — je vous dirai la forme et la hauteur", agentApplied: "Forme et taille tirées de la description" }, es: { agentPlaceholder: "Describe el mundo — te diré la forma y la altura", agentApplied: "Forma y tamaño tomados de la descripción" } };

for (const loc of L) {
  const f = path.join(DIR, `${loc}.json`); const j = JSON.parse(fs.readFileSync(f, "utf8"));
  j.mountains = { ...(j.mountains || {}), ...mountains[loc] };
  j.agent = { ...(j.agent || {}), ...agent[loc] };
  j.mountainsMeta = { ...(j.mountainsMeta || {}), ...mountainsMeta[loc] };
  j.nav = { ...(j.nav || {}), mountains: nav[loc] };
  j.beta = { ...(j.beta || {}), mountains: beta[loc] };
  j.worlds = { ...(j.worlds || {}), ...worldsAgent[loc] };
  fs.writeFileSync(f, JSON.stringify(j, null, 2) + "\n", "utf8");
}
console.log("done");
