import fs from "node:fs"; import path from "node:path";
const DIR = path.resolve("messages");
const data = {
  wizard: {
    uk: { settingsMap:"Параметри", settingsKeychain:"Дизайн", hintMap:"Розмір і шари (за бажанням)", hintKeychain:"Текст, петля, розмір", city:"Місто", cityPrompt:"Оберіть місто", area:"Ділянка", areaDone:"Виділено", areaPrompt:"Намалюйте прямокутник на мапі", done:"Готово", generating:"Генерація {progress}%", downloadReady:"Завантажте 3MF", generatePrompt:"Згенеруйте модель", aria:"Кроки створення", step:"Крок {n}" },
    en: { settingsMap:"Settings", settingsKeychain:"Design", hintMap:"Size and layers (optional)", hintKeychain:"Text, loop, size", city:"City", cityPrompt:"Pick a city", area:"Area", areaDone:"Selected", areaPrompt:"Draw a rectangle on the map", done:"Done", generating:"Generating {progress}%", downloadReady:"Download 3MF", generatePrompt:"Generate the model", aria:"Creation steps", step:"Step {n}" },
    de: { settingsMap:"Einstellungen", settingsKeychain:"Design", hintMap:"Größe und Ebenen (optional)", hintKeychain:"Text, Öse, Größe", city:"Stadt", cityPrompt:"Stadt wählen", area:"Bereich", areaDone:"Ausgewählt", areaPrompt:"Zeichne ein Rechteck auf der Karte", done:"Fertig", generating:"Generierung {progress}%", downloadReady:"3MF herunterladen", generatePrompt:"Modell generieren", aria:"Erstellungsschritte", step:"Schritt {n}" },
    pl: { settingsMap:"Ustawienia", settingsKeychain:"Projekt", hintMap:"Rozmiar i warstwy (opcjonalnie)", hintKeychain:"Tekst, oczko, rozmiar", city:"Miasto", cityPrompt:"Wybierz miasto", area:"Obszar", areaDone:"Zaznaczono", areaPrompt:"Narysuj prostokąt na mapie", done:"Gotowe", generating:"Generowanie {progress}%", downloadReady:"Pobierz 3MF", generatePrompt:"Wygeneruj model", aria:"Kroki tworzenia", step:"Krok {n}" },
    fr: { settingsMap:"Paramètres", settingsKeychain:"Design", hintMap:"Taille et couches (facultatif)", hintKeychain:"Texte, anneau, taille", city:"Ville", cityPrompt:"Choisis une ville", area:"Zone", areaDone:"Sélectionnée", areaPrompt:"Dessine un rectangle sur la carte", done:"Terminé", generating:"Génération {progress}%", downloadReady:"Télécharger 3MF", generatePrompt:"Générer le modèle", aria:"Étapes de création", step:"Étape {n}" },
    es: { settingsMap:"Ajustes", settingsKeychain:"Diseño", hintMap:"Tamaño y capas (opcional)", hintKeychain:"Texto, anilla, tamaño", city:"Ciudad", cityPrompt:"Elige una ciudad", area:"Zona", areaDone:"Seleccionada", areaPrompt:"Dibuja un rectángulo en el mapa", done:"Listo", generating:"Generando {progress}%", downloadReady:"Descargar 3MF", generatePrompt:"Genera el modelo", aria:"Pasos de creación", step:"Paso {n}" },
  },
  simple: {
    uk: { step1city:"Крок 1 · Місто", step2districts:"Крок 2 · Готові райони", orDraw:"або намалюйте на мапі", kyiv:"Київ", khmel:"Хмельницький", noDistricts:"Для цього міста ще немає готових районів — намалюйте ділянку прямокутником на мапі.", areaSelected:"✓ Ділянку вибрано", areaNotSelected:"Ділянку ще не вибрано", step3style:"Крок 3 · Стиль", step4size:"Крок 4 · Розмір", quickPreview:"Швидке прев'ю", forPrint:"Для друку", generating:"Генерація…", generate:"Згенерувати модель", errSelectArea:"Оберіть район або намалюйте ділянку на мапі", errGen:"Помилка генерації", qualityWarn:"Модель готова, але є зауваження щодо друку. Деталі — у режимі «Про».", downloadFile:"Завантажити 3MF", advancedHint:"Потрібна серія зон (гексагони / квадрати)? Відкрити режим «Про» →", orderPrint:"Замовити друк", limitMsg:"Вичерпав 5 безкоштовних завантажень. Хочу більше / друк — звʼяжіться зі мною." },
    en: { step1city:"Step 1 · City", step2districts:"Step 2 · Ready districts", orDraw:"or draw on the map", kyiv:"Kyiv", khmel:"Khmelnytskyi", noDistricts:"No ready districts for this city yet — draw an area as a rectangle on the map.", areaSelected:"✓ Area selected", areaNotSelected:"No area selected yet", step3style:"Step 3 · Style", step4size:"Step 4 · Size", quickPreview:"Quick preview", forPrint:"For print", generating:"Generating…", generate:"Generate model", errSelectArea:"Pick a district or draw an area on the map", errGen:"Generation error", qualityWarn:"The model is ready, but there are print remarks. Details in “Pro” mode.", downloadFile:"Download 3MF", advancedHint:"Need a series of zones (hexagons / squares)? Open “Pro” mode →", orderPrint:"Order printing", limitMsg:"I've used all 5 free downloads. I'd like more / printing — please contact me." },
    de: { step1city:"Schritt 1 · Stadt", step2districts:"Schritt 2 · Fertige Viertel", orDraw:"oder auf der Karte zeichnen", kyiv:"Kyjiw", khmel:"Chmelnyzkyj", noDistricts:"Für diese Stadt gibt es noch keine fertigen Viertel — zeichne einen Bereich als Rechteck auf der Karte.", areaSelected:"✓ Bereich ausgewählt", areaNotSelected:"Noch kein Bereich ausgewählt", step3style:"Schritt 3 · Stil", step4size:"Schritt 4 · Größe", quickPreview:"Schnelle Vorschau", forPrint:"Für den Druck", generating:"Generierung…", generate:"Modell generieren", errSelectArea:"Wähle ein Viertel oder zeichne einen Bereich auf der Karte", errGen:"Generierungsfehler", qualityWarn:"Das Modell ist fertig, aber es gibt Druckhinweise. Details im „Pro“-Modus.", downloadFile:"3MF herunterladen", advancedHint:"Brauchst du eine Reihe von Zonen (Hexagone / Quadrate)? „Pro“-Modus öffnen →", orderPrint:"Druck bestellen", limitMsg:"Ich habe alle 5 kostenlosen Downloads aufgebraucht. Ich möchte mehr / Druck — bitte kontaktiert mich." },
    pl: { step1city:"Krok 1 · Miasto", step2districts:"Krok 2 · Gotowe dzielnice", orDraw:"lub narysuj na mapie", kyiv:"Kijów", khmel:"Chmielnicki", noDistricts:"Dla tego miasta nie ma jeszcze gotowych dzielnic — narysuj obszar prostokątem na mapie.", areaSelected:"✓ Obszar wybrany", areaNotSelected:"Nie wybrano jeszcze obszaru", step3style:"Krok 3 · Styl", step4size:"Krok 4 · Rozmiar", quickPreview:"Szybki podgląd", forPrint:"Do druku", generating:"Generowanie…", generate:"Wygeneruj model", errSelectArea:"Wybierz dzielnicę lub narysuj obszar na mapie", errGen:"Błąd generowania", qualityWarn:"Model gotowy, ale są uwagi do druku. Szczegóły w trybie „Pro”.", downloadFile:"Pobierz 3MF", advancedHint:"Potrzebujesz serii stref (heksagony / kwadraty)? Otwórz tryb „Pro” →", orderPrint:"Zamów druk", limitMsg:"Wykorzystałem 5 darmowych pobrań. Chcę więcej / druk — proszę o kontakt." },
    fr: { step1city:"Étape 1 · Ville", step2districts:"Étape 2 · Quartiers prêts", orDraw:"ou dessine sur la carte", kyiv:"Kyiv", khmel:"Khmelnytskyï", noDistricts:"Pas encore de quartiers prêts pour cette ville — dessine une zone en rectangle sur la carte.", areaSelected:"✓ Zone sélectionnée", areaNotSelected:"Aucune zone sélectionnée", step3style:"Étape 3 · Style", step4size:"Étape 4 · Taille", quickPreview:"Aperçu rapide", forPrint:"Pour l'impression", generating:"Génération…", generate:"Générer le modèle", errSelectArea:"Choisis un quartier ou dessine une zone sur la carte", errGen:"Erreur de génération", qualityWarn:"Le modèle est prêt, mais il y a des remarques d'impression. Détails en mode « Pro ».", downloadFile:"Télécharger 3MF", advancedHint:"Besoin d'une série de zones (hexagones / carrés) ? Ouvre le mode « Pro » →", orderPrint:"Commander l'impression", limitMsg:"J'ai utilisé mes 5 téléchargements gratuits. J'en veux plus / impression — contactez-moi." },
    es: { step1city:"Paso 1 · Ciudad", step2districts:"Paso 2 · Distritos listos", orDraw:"o dibuja en el mapa", kyiv:"Kiev", khmel:"Jmelnitski", noDistricts:"Aún no hay distritos listos para esta ciudad — dibuja una zona como rectángulo en el mapa.", areaSelected:"✓ Zona seleccionada", areaNotSelected:"Aún no hay zona seleccionada", step3style:"Paso 3 · Estilo", step4size:"Paso 4 · Tamaño", quickPreview:"Vista rápida", forPrint:"Para imprimir", generating:"Generando…", generate:"Generar modelo", errSelectArea:"Elige un distrito o dibuja una zona en el mapa", errGen:"Error de generación", qualityWarn:"El modelo está listo, pero hay observaciones de impresión. Detalles en modo «Pro».", downloadFile:"Descargar 3MF", advancedHint:"¿Necesitas una serie de zonas (hexágonos / cuadrados)? Abre el modo «Pro» →", orderPrint:"Pedir impresión", limitMsg:"He usado mis 5 descargas gratuitas. Quiero más / impresión — contáctame, por favor." },
  },
};
for (const loc of ["uk","en","de","pl","fr","es"]) { const f=path.join(DIR,`${loc}.json`); const j=JSON.parse(fs.readFileSync(f,"utf8")); for(const ns of Object.keys(data)) j[ns]={...(j[ns]||{}),...data[ns][loc]}; fs.writeFileSync(f,JSON.stringify(j,null,2)+"\n","utf8"); }
console.log("done");
