/**
 * SEO 27.09.2026, етап 1: сторінки ВІДОМИХ ВУЛИЦЬ великих міст —
 * /maps/{city}/{slug}, лише uk + en. Запити «3d модель хрещатика», «макет
 * дерибасівської купити», «мапа вулиці де ми познайомились».
 *
 * ВІДБІР: вулиці з Wikidata (P31=Q79007), що мають статтю в uk-Вікіпедії та
 * ≥3 мовні версії статті (сигнал відомості); Київ — топ-120, решта міст — усі.
 * ФАКТИ лише з Wikidata: на честь кого названа (P138), довжина (P2043), рік (P571),
 * координати (P625); посилання на статтю Вікіпедії як джерело. Жодної вигаданої
 * «історії» — унікальність дають факти + обчислення (район, відстань від центру,
 * сусідні вулиці).
 * Згенеровано скриптом gen_streets.py (scratchpad) — можна правити вручну.
 */
export interface CityStreet {
  citySlug: string;
  slug: string;
  wd: string; // Wikidata Q-id
  uk: string;
  en?: string;
  center: [number, number];
  namedAfter?: string;
  lengthM?: number;
  since?: number;
  wiki: string; // назва статті uk.wikipedia
}

export const STREET_LOCALES = ["uk", "en"] as const;

export const CITY_STREETS: CityStreet[] = [
  { citySlug: "kyiv", slug: "khreshchatyk", wd: "Q1076911", uk: "Хрещатик", en: "Khreshchatyk", center: [50.44722, 30.52194], lengthM: 1300, wiki: "Хрещатик" },
  { citySlug: "kyiv", slug: "lvivska-ploshcha", wd: "Q3406749", uk: "Львівська площа", en: "Lvivska Square", center: [50.45481, 30.50625], namedAfter: "Львів", wiki: "Львівська площа" },
  { citySlug: "kyiv", slug: "odeska-ploshcha", wd: "Q4331416", uk: "Одеська площа", en: "Odesa Square, Kyiv", center: [50.37004, 30.45882], namedAfter: "Одеса", wiki: "Одеська площа (Київ)" },
  { citySlug: "kyiv", slug: "instytutska-vulytsia", wd: "Q4201886", uk: "Інститутська вулиця", en: "Instytutska Street", center: [50.44781, 30.52928], namedAfter: "Київський інститут шляхетних дівчат", lengthM: 756, wiki: "Інститутська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "aleia-mahdeburzkoho-prava", wd: "Q4361165", uk: "Алея Магдебурзького права", en: "Mahdeburzkoho prava Alley", center: [50.45081, 30.52950], namedAfter: "Магдебурзьке право", wiki: "Алея Магдебурзького права" },
  { citySlug: "kyiv", slug: "biloruska-vulytsia", wd: "Q12086765", uk: "Білоруська вулиця", en: "Biloruska Street, Kyiv", center: [50.46192, 30.48067], namedAfter: "Білорусь", wiki: "Білоруська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yevhena-konovaltsia", wd: "Q12092677", uk: "Вулиця Євгена Коновальця", en: "Yevhen Konovalets Street, Kyiv", center: [50.42543, 30.52625], namedAfter: "Коновалець Євген Михайлович", wiki: "Вулиця Євгена Коновальця (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-petra-bolbochana", wd: "Q12091732", uk: "Вулиця Петра Болбочана", en: "Petra Bolbochana Street", center: [50.42175, 30.54572], namedAfter: "Болбочан Петро Федорович", wiki: "Вулиця Петра Болбочана (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yakuba-kolasa", wd: "Q12092697", uk: "Вулиця Якуба Коласа", en: "Yakuba Kolasa Street, Kyiv", center: [50.43519, 30.37800], namedAfter: "Якуб Колас", wiki: "Вулиця Якуба Коласа (Київ)" },
  { citySlug: "kyiv", slug: "heroiv-upa-ploshcha", wd: "Q4465225", uk: "Героїв УПА площа", en: "Heroiv UPA Square", center: [50.48917, 30.49722], wiki: "Площа Героїв УПА" },
  { citySlug: "kyiv", slug: "holosiivska-ploshcha", wd: "Q4142167", uk: "Голосіївська площа", en: "Holosiivska Square", center: [50.39733, 30.50994], namedAfter: "Голосіїв", wiki: "Голосіївська площа" },
  { citySlug: "kyiv", slug: "liuteranska-vulytsia", wd: "Q4272309", uk: "Лютеранська вулиця", en: "Lyuteranska Street", center: [50.44444, 30.52250], lengthM: 660, wiki: "Лютеранська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "aleia-heroiv-nebesnoi-sotni", wd: "Q20073731", uk: "Алея Героїв Небесної Сотні", en: "Alley of Heroes of the Heavenly Hundred", center: [50.44781, 30.52928], namedAfter: "Небесна сотня", lengthM: 756, wiki: "Алея Героїв Небесної Сотні" },
  { citySlug: "kyiv", slug: "vokzalna-ploshcha", wd: "Q4122836", uk: "Вокзальна площа", en: "Vokzalna Square, Kyiv", center: [50.44106, 30.49069], wiki: "Вокзальна площа (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yevhena-sverstiuka", wd: "Q12091934", uk: "Вулиця Євгена Сверстюка", en: "Yevhena Sverstiuka Street, Kyiv", center: [50.45158, 30.59836], namedAfter: "Сверстюк Євген Олександрович", wiki: "Вулиця Євгена Сверстюка (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yevhena-chykalenka", wd: "Q4384781", uk: "Вулиця Євгена Чикаленка", en: "Yevhen Chykalenko Street, Kyiv", center: [50.44811, 30.51928], namedAfter: "Чикаленко Євген Харламович", lengthM: 975, wiki: "Вулиця Євгена Чикаленка (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yezhy-gedroitsia", wd: "Q12160232", uk: "Вулиця Єжи Ґедройця", en: "Yezhy Gedroitsia Street, Kyiv", center: [50.41915, 30.52185], namedAfter: "Єжи Ґедройць", wiki: "Вулиця Єжи Ґедройця" },
  { citySlug: "kyiv", slug: "vulytsia-ivana-franka", wd: "Q4472277", uk: "Вулиця Івана Франка", en: "Ivana Franka Street", center: [50.45078, 30.51025], namedAfter: "Іван Франко", lengthM: 710, wiki: "Вулиця Івана Франка (Київ, Шевченківський район)" },
  { citySlug: "kyiv", slug: "vulytsia-ioanna-pavla-ii", wd: "Q12092196", uk: "Вулиця Іоанна Павла II", en: "John Paul II Street, Kyiv", center: [50.41865, 30.53422], namedAfter: "Іван Павло II", wiki: "Вулиця Іоанна Павла II (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-bohomoltsia", wd: "Q4471172", uk: "Вулиця Академіка Богомольця", en: "Akademika Bohomoltsia Street", center: [50.44131, 30.52867], namedAfter: "Богомолець Олександр Олександрович", lengthM: 500, wiki: "Вулиця Академіка Богомольця (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-arkhitektora-horodetskoho", wd: "Q4471335", uk: "Вулиця Архітектора Городецького", en: "Arkhitektora Horodetskoho Street", center: [50.44919, 30.52342], namedAfter: "Городецький Владислав Владиславович", lengthM: 405, wiki: "Вулиця Архітектора Городецького" },
  { citySlug: "kyiv", slug: "vulytsia-heroiv-dnipra", wd: "Q12091464", uk: "Вулиця Героїв Дніпра", en: "Heroiv Dnipra Street, Kyiv", center: [50.51762, 30.48433], namedAfter: "Битва за Дніпро", lengthM: 2400, wiki: "Вулиця Героїв Дніпра (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-deputatska", wd: "Q4158622", uk: "Вулиця Депутатська", en: "Deputatskaya Street, Kyiv", center: [50.45875, 30.38000], wiki: "Депутатська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-kuchmyn-yar", wd: "Q6436261", uk: "Вулиця Кучмин Яр", en: "Kuchmyn Yar Street", center: [50.43639, 30.49188], namedAfter: "Кучмин яр", lengthM: 1075, wiki: "Вулиця Кучмин Яр" },
  { citySlug: "kyiv", slug: "vulytsia-ovanesa-tumaniana", wd: "Q12092102", uk: "Вулиця Ованеса Туманяна", en: "Ovanesa Tumaniana Street", center: [50.44635, 30.60075], namedAfter: "Туманян Ованес Тадевосович", lengthM: 420, wiki: "Вулиця Ованеса Туманяна (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-oleksy-tykhoho", wd: "Q12089067", uk: "Вулиця Олекси Тихого", en: "Oleksy Tykhoho Street", center: [50.44686, 30.45297], namedAfter: "Тихий Олексій Іванович", wiki: "Вулиця Олекси Тихого (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-onore-de-balzaka", wd: "Q12092144", uk: "Вулиця Оноре де Бальзака", en: "Honoré de Balzac Street", center: [50.49562, 30.57752], namedAfter: "Оноре де Бальзак", since: 1983, wiki: "Вулиця Оноре де Бальзака (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-rohnidynska", wd: "Q4395476", uk: "Вулиця Рогнідинська", en: "Rohnidynska Street, Kyiv", center: [50.43917, 30.52000], namedAfter: "Рогнеда", lengthM: 230, wiki: "Рогнідинська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-symona-petliury", wd: "Q4473996", uk: "Вулиця Симона Петлюри", en: "Symona Petliury Street", center: [50.44528, 30.50056], namedAfter: "Петлюра Симон Васильович", wiki: "Вулиця Симона Петлюри (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-shota-rustaveli", wd: "Q4474616", uk: "Вулиця Шота Руставелі", en: "Shota Rustaveli Street, Kyiv", center: [50.44014, 30.52267], namedAfter: "Шота Руставелі", lengthM: 850, wiki: "Вулиця Шота Руставелі (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yanky-kupaly", wd: "Q12092702", uk: "Вулиця Янки Купали", en: "Yanky Kupaly Street, Kyiv", center: [50.42851, 30.45853], namedAfter: "Янка Купала", lengthM: 215, wiki: "Вулиця Янки Купали (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yanusha-korchaka", wd: "Q12091229", uk: "Вулиця Януша Корчака", en: "Yanusha Korchaka Street", center: [50.46289, 30.41150], namedAfter: "Януш Корчак", wiki: "Вулиця Януша Корчака" },
  { citySlug: "kyiv", slug: "demiivska-ploshcha", wd: "Q4303941", uk: "Деміївська площа", en: "Demiivska Square, Kyiv", center: [50.40714, 30.51917], namedAfter: "Деміївка", wiki: "Деміївська площа" },
  { citySlug: "kyiv", slug: "derevlianska-vulytsia", wd: "Q4474692", uk: "Деревлянська вулиця", en: "Derevlianska Street, Kyiv", center: [50.46586, 30.46971], namedAfter: "Деревляни", lengthM: 820, wiki: "Деревлянська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "estonska-vulytsia", wd: "Q4532885", uk: "Естонська вулиця", en: "Estonska Street", center: [50.46422, 30.41306], namedAfter: "Естонія", wiki: "Естонська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "kyrylivska-vulytsia", wd: "Q4474368", uk: "Кирилівська вулиця", en: "Kyrylivska Street, Kyiv", center: [50.46667, 30.50975], namedAfter: "Кирилівська церква", wiki: "Кирилівська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "kolektorna-vulytsia", wd: "Q12111577", uk: "Колекторна вулиця", en: "Kolektorna Street, Kyiv", center: [50.40111, 30.68167], wiki: "Колекторна вулиця" },
  { citySlug: "kyiv", slug: "krakivska-vulytsia", wd: "Q12114129", uk: "Краківська вулиця", en: "Krakivska Street, Kyiv", center: [50.45203, 30.61233], namedAfter: "Краків", wiki: "Краківська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "kiltseva-doroha", wd: "Q12116422", uk: "Кільцева дорога", en: "Kiltseva Road, Kyiv", center: [50.37014, 30.45842], wiki: "Кільцева дорога (Київ)" },
  { citySlug: "kyiv", slug: "luhova-vulytsia", wd: "Q12118617", uk: "Лугова вулиця", en: "Luhova Street", center: [50.50607, 30.47113], wiki: "Лугова вулиця (Київ, Оболонський район)" },
  { citySlug: "kyiv", slug: "mykhailivska-vulytsia", wd: "Q4297711", uk: "Михайлівська вулиця", en: "Mykhailivska Street, Kyiv", center: [50.45330, 30.52154], namedAfter: "Михайлівський Золотоверхий монастир", wiki: "Михайлівська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "naberezhno-luhova-vulytsia", wd: "Q4311149", uk: "Набережно-Лугова вулиця", en: "Naberezhno-Luhova Street", center: [50.47394, 30.51647], wiki: "Набережно-Лугова вулиця" },
  { citySlug: "kyiv", slug: "olhynska-vulytsia", wd: "Q4334124", uk: "Ольгинська вулиця", en: "Olhynska Street", center: [50.44656, 30.51081], namedAfter: "Ольга", lengthM: 190, wiki: "Ольгинська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "ploshcha-kosmonavtiv", wd: "Q4365610", uk: "Площа Космонавтів", en: "Kosmonavtiv Square", center: [50.43156, 30.45523], wiki: "Площа Космонавтів" },
  { citySlug: "kyiv", slug: "ploshcha-lesi-ukrainky", wd: "Q4365648", uk: "Площа Лесі Українки", en: "Lesi Ukrainky Square, Kyiv", center: [50.42736, 30.53981], namedAfter: "Леся Українка", wiki: "Площа Лесі Українки (Київ)" },
  { citySlug: "kyiv", slug: "poliarna-vulytsia", wd: "Q12142049", uk: "Полярна вулиця", en: "Poliarna Street", center: [50.51790, 30.46650], wiki: "Полярна вулиця (Київ)" },
  { citySlug: "kyiv", slug: "rostyslavska-vulytsia", wd: "Q4473096", uk: "Ростиславська вулиця", en: "Rostyslavska Street", center: [50.45517, 30.48771], namedAfter: "Ростислав Мстиславич", wiki: "Ростиславська вулиця" },
  { citySlug: "kyiv", slug: "stratehichne-shose", wd: "Q12158113", uk: "Стратегічне шосе", en: "Stratehichne Highway", center: [50.39944, 30.53389], wiki: "Стратегічне шосе" },
  { citySlug: "kyiv", slug: "kharkivske-shose", wd: "Q4496376", uk: "Харківське шосе", en: "Kharkivske Highway", center: [50.44072, 30.62811], namedAfter: "Харків", since: 1930, wiki: "Харківське шосе (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-olesia-honchara", wd: "Q167223", uk: "вулиця Олеся Гончара", en: "Olesia Honchara Street, Kyiv", center: [50.45519, 30.51158], namedAfter: "Гончар Олесь Терентійович", lengthM: 1500, wiki: "Вулиця Олеся Гончара (Київ)" },
  { citySlug: "kyiv", slug: "ihorivska-vulytsia", wd: "Q4197628", uk: "Ігорівська вулиця", en: "Ihorivska Street", center: [50.46049, 30.52378], namedAfter: "Ігор Рюрикович", wiki: "Ігорівська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "illinska-vulytsia", wd: "Q4199695", uk: "Іллінська вулиця", en: "Illinska Street, Kyiv", center: [50.46367, 30.51997], namedAfter: "Іллінська церква", wiki: "Іллінська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "irynynska-vulytsia", wd: "Q4203215", uk: "Ірининська вулиця", en: "Irynynska Street, Kyiv", center: [50.45103, 30.51665], namedAfter: "Ірининська церква", lengthM: 150, wiki: "Ірининська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "avtozavodska-vulytsia", wd: "Q12075961", uk: "Автозаводська вулиця", en: "Avtozavodska Street", center: [50.50934, 30.45806], lengthM: 2500, wiki: "Автозаводська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "azovska-vulytsia", wd: "Q12077151", uk: "Азовська вулиця", en: "Azovska Street", center: [50.41650, 30.47352], namedAfter: "Азовське море", lengthM: 200, wiki: "Азовська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "bakynska-vulytsia", wd: "Q12080457", uk: "Бакинська вулиця", en: "Bakynska Street", center: [50.47950, 30.44576], lengthM: 820, wiki: "Бакинська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "baryshivska-vulytsia", wd: "Q12091117", uk: "Баришівська вулиця", en: "Baryshivska Street", center: [50.40831, 30.54053], namedAfter: "Баришівка", lengthM: 139, wiki: "Баришівська вулиця" },
  { citySlug: "kyiv", slug: "berezhanska-vulytsia", wd: "Q12082042", uk: "Бережанська вулиця", en: "Berezhanska Street, Kyiv", center: [50.50704, 30.46471], namedAfter: "Бережани", lengthM: 1600, wiki: "Бережанська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "berezniakivska-vulytsia", wd: "Q12082139", uk: "Березняківська вулиця", en: "Berezniakivska Street, Kyiv", center: [50.43703, 30.61208], namedAfter: "Березняки", lengthM: 3000, wiki: "Березняківська вулиця" },
  { citySlug: "kyiv", slug: "bessarabskyi-proizd", wd: "Q4473496", uk: "Бессарабський проїзд", en: "Pavla Skoropadskoho Street", center: [50.44081, 30.51983], wiki: "Бессарабський проїзд" },
  { citySlug: "kyiv", slug: "bohatyrska-vulytsia", wd: "Q12083171", uk: "Богатирська вулиця", en: "Bohatyrska Street", center: [50.48901, 30.50139], wiki: "Богатирська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "borysohlibska-vulytsia", wd: "Q4094029", uk: "Борисоглібська вулиця", en: "Borysohlibska Street, Kyiv", center: [50.46214, 30.52017], namedAfter: "Церква святих Бориса й Гліба", wiki: "Борисоглібська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "boryspilska-vulytsia", wd: "Q12084096", uk: "Бориспільська вулиця", en: "Boryspilska Street, Kyiv", center: [50.41425, 30.69711], namedAfter: "Бориспіль", lengthM: 7900, wiki: "Бориспільська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "borova-vulytsia", wd: "Q12084140", uk: "Борова вулиця", en: "Borova Street, Chervonyi Khutir, Kyiv", center: [50.41461, 30.66889], lengthM: 690, wiki: "Борова вулиця (Київ, Червоний хутір)" },
  { citySlug: "kyiv", slug: "borshchahivska-vulytsia", wd: "Q12084284", uk: "Борщагівська вулиця", en: "Borshchahivska Street, Kyiv", center: [50.44639, 30.48139], lengthM: 3600, wiki: "Борщагівська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "bratska-vulytsia", wd: "Q4095944", uk: "Братська вулиця", en: "Bratska Street, Kyiv", center: [50.46386, 30.52078], namedAfter: "Києво-Братський монастир", lengthM: 400, wiki: "Братська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "bulvar-pavla-virskoho", wd: "Q12150636", uk: "Бульвар Павла Вірського", en: "Pavla Virskoho Boulevard", center: [50.47138, 30.41432], namedAfter: "Вірський Павло Павлович", lengthM: 1310, wiki: "Бульвар Павла Вірського" },
  { citySlug: "kyiv", slug: "busovohirska-vulytsia", wd: "Q12091988", uk: "Бусовогірська вулиця", en: "Busovohirska Street", center: [50.41050, 30.55814], namedAfter: "Бусова гора", lengthM: 170, wiki: "Бусовогірська вулиця" },
  { citySlug: "kyiv", slug: "bilytska-vulytsia", wd: "Q12086649", uk: "Білицька вулиця", en: "Bilytska Street, Kyiv", center: [50.49694, 30.45600], namedAfter: "Біличе поле", wiki: "Білицька вулиця (Київ)" },
  { citySlug: "kyiv", slug: "vasylkivska-vulytsia", wd: "Q12087930", uk: "Васильківська вулиця", en: "Vasylkivska Street", center: [50.38957, 30.49369], namedAfter: "Васильків", wiki: "Васильківська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "verbolozna-vulytsia", wd: "Q12088655", uk: "Верболозна вулиця", en: "Verbolozna street", center: [50.48429, 30.45874], lengthM: 640, wiki: "Верболозна вулиця" },
  { citySlug: "kyiv", slug: "veresneva-vulytsia", wd: "Q12088718", uk: "Вереснева вулиця", en: "Veresneva Street, Kyiv", center: [50.42364, 30.66631], lengthM: 1200, wiki: "Вереснева вулиця (Київ)" },
  { citySlug: "kyiv", slug: "vyshhorodska-vulytsia", wd: "Q4129955", uk: "Вишгородська вулиця", en: "Vyshhorodska Street", center: [50.49658, 30.45690], namedAfter: "Вишгород", lengthM: 2800, wiki: "Вишгородська вулиця" },
  { citySlug: "kyiv", slug: "vyshniakivska-vulytsia", wd: "Q12089747", uk: "Вишняківська вулиця", en: "Vyshniakivska Street", center: [50.39504, 30.64841], lengthM: 810, wiki: "Вишняківська вулиця" },
  { citySlug: "kyiv", slug: "voznesenskyi-uzviz", wd: "Q6685458", uk: "Вознесенський узвіз", en: "Voznesenskyi Descent", center: [50.45578, 30.50481], namedAfter: "Вознесенська церква (Кудрявець)", lengthM: 865, wiki: "Вознесенський узвіз" },
  { citySlug: "kyiv", slug: "volynska-vulytsia", wd: "Q12090309", uk: "Волинська вулиця", en: "Volynska Street, Kyiv", center: [50.43425, 30.45397], namedAfter: "Волинь", wiki: "Волинська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "volnovaska-vulytsia", wd: "Q12092312", uk: "Волноваська вулиця", en: "Volnovaska Street, Kyiv", center: [50.44800, 30.41060], namedAfter: "Волноваха", wiki: "Волноваська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "volodymyrskyi-proizd", wd: "Q4113285", uk: "Володимирський проїзд", en: "Volodymyrskyi Pass", center: [50.45361, 30.51694], namedAfter: "Володимир Святославич", lengthM: 290, since: 1850, wiki: "Володимирський проїзд" },
  { citySlug: "kyiv", slug: "voloska-vulytsia", wd: "Q4124137", uk: "Волоська вулиця", en: "Voloska Street", center: [50.46444, 30.52389], wiki: "Волоська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-yevheniia-kharchenka", wd: "Q12091844", uk: "Вулиця Євгенія Харченка", en: "Yevheniia Kharchenka Street, Kyiv", center: [50.39361, 30.69750], namedAfter: "Харченко Євген Борисович", lengthM: 2500, wiki: "Вулиця Євгена Харченка" },
  { citySlug: "kyiv", slug: "vulytsia-yelyzavety-chavdar", wd: "Q12091079", uk: "Вулиця Єлизавети Чавдар", en: "Yelyzavety Chavdar Street", center: [50.39317, 30.61683], namedAfter: "Чавдар Єлизавета Іванівна", wiki: "Вулиця Єлизавети Чавдар" },
  { citySlug: "kyiv", slug: "vulytsia-ivana-yizhakevycha", wd: "Q12091086", uk: "Вулиця Івана Їжакевича", en: "Ivana Izhakevycha Street", center: [50.51494, 30.43515], namedAfter: "Їжакевич Іван Сидорович", wiki: "Вулиця Івана Їжакевича (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-ivana-kramskoho", wd: "Q4472273", uk: "Вулиця Івана Крамського", en: "Ivana Kramskoho Street, Kyiv", center: [50.45292, 30.37244], namedAfter: "Крамськой Іван Миколайович", wiki: "Вулиця Івана Крамського" },
  { citySlug: "kyiv", slug: "vulytsia-ivana-mykolaichuka", wd: "Q12092379", uk: "Вулиця Івана Миколайчука", en: "Ivana Mykolaichuka Street", center: [50.43319, 30.60249], namedAfter: "Миколайчук Іван Васильович", lengthM: 1600, wiki: "Вулиця Івана Миколайчука (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-ivana-fedorova", wd: "Q4472283", uk: "Вулиця Івана Федорова", en: "Ivana Fedorova Street, Kyiv", center: [50.42740, 30.51340], namedAfter: "Федоров Євген Костянтинович", wiki: "Вулиця Івана Федорова (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-ihoria-turchyna", wd: "Q12091317", uk: "Вулиця Ігоря Турчина", en: "Ihoria Turchyna Street, Kyiv", center: [50.48147, 30.39594], namedAfter: "Турчин Ігор Євдокимович", lengthM: 580, wiki: "Вулиця Ігоря Турчина" },
  { citySlug: "kyiv", slug: "vulytsia-irpinska", wd: "Q4203417", uk: "Вулиця Ірпінська", en: "Irpinska Street, Kyiv", center: [50.46061, 30.35806], namedAfter: "Ірпінь", wiki: "Ірпінська вулиця (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-ismaila-hasprynskoho", wd: "Q12154592", uk: "Вулиця Ісмаїла Гаспринського", en: "Ismaila Hasprynskoho Street, Kyiv", center: [50.42750, 30.64661], namedAfter: "Ісмаїл Гаспринський", wiki: "Вулиця Ісмаїла Гаспринського (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-aviakonstruktora-antonova", wd: "Q12091134", uk: "Вулиця Авіаконструктора Антонова", en: "Aviakonstruktora Antonova Street", center: [50.43089, 30.45696], namedAfter: "Антонов Олег Костянтинович", lengthM: 1340, wiki: "Вулиця Авіаконструктора Антонова (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-aviakonstruktorska", wd: "Q4471837", uk: "Вулиця Авіаконструкторська", en: "Aviakonstruktorska Street, Kyiv", center: [50.46081, 30.38086], lengthM: 920, wiki: "Авіаконструкторська вулиця" },
  { citySlug: "kyiv", slug: "vulytsia-adama-mitskevycha", wd: "Q12091136", uk: "Вулиця Адама Міцкевича", en: "Adama Mitskevycha Street", center: [50.43774, 30.45494], namedAfter: "Адам Міцкевич", lengthM: 340, wiki: "Вулиця Адама Міцкевича (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-yefremova", wd: "Q4472512", uk: "Вулиця Академіка Єфремова", en: "Akademika Yefremova Street, Kyiv", center: [50.46442, 30.34664], namedAfter: "Єфремов Сергій Олександрович", lengthM: 1300, wiki: "Вулиця Академіка Єфремова (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-bulakhovskoho", wd: "Q4471174", uk: "Вулиця Академіка Булаховського", en: "Akademika Bulakhovskoho Street, Kyiv", center: [50.46908, 30.34411], namedAfter: "Булаховський Леонід Арсенійович", wiki: "Вулиця Академіка Булаховського" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-biletskoho", wd: "Q12091145", uk: "Вулиця Академіка Білецького", en: "Akademika Biletskoho Street, Kyiv", center: [50.43197, 30.42247], namedAfter: "Білецький Олександр Іванович", wiki: "Вулиця Академіка Білецького (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-dobrokhotova", wd: "Q4471179", uk: "Вулиця Академіка Доброхотова", en: "Akademika Dobrokhotova Street, Kyiv", center: [50.46267, 30.36431], namedAfter: "Доброхотов Микола Миколайович", lengthM: 1000, wiki: "Вулиця Академіка Доброхотова" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-zabolotnoho", wd: "Q4471181", uk: "Вулиця Академіка Заболотного", en: "Akademika Zabolotnoho Street", center: [50.35039, 30.49672], namedAfter: "Заболотний Данило Кирилович", wiki: "Вулиця Академіка Заболотного (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-korolova", wd: "Q12091154", uk: "Вулиця Академіка Корольова", en: "Akademika Koroliova Street, Kyiv", center: [50.42886, 30.39289], namedAfter: "Корольов Сергій Павлович", lengthM: 470, wiki: "Вулиця Академіка Корольова (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-kostycheva", wd: "Q12091158", uk: "Вулиця Академіка Костичева", en: "Profesora Balinskoho Street", center: [50.38164, 30.45716], wiki: "Вулиця Професора Балінського" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-kukharia", wd: "Q12130827", uk: "Вулиця Академіка Кухаря", en: "Academian Koukhar Street", center: [50.46072, 30.65189], namedAfter: "Кухар Валерій Павлович", lengthM: 460, wiki: "Вулиця Академіка Кухаря" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-lebedieva", wd: "Q12091162", uk: "Вулиця Академіка Лебедєва", en: "Akademika Lebedieva Street, Kyiv", center: [50.34703, 30.48306], namedAfter: "Лебедєв Сергій Олексійович", wiki: "Вулиця Академіка Лебедєва (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-akademika-yanhelia", wd: "Q12091172", uk: "Вулиця Академіка Янгеля", en: "Akademika Yanhelia Street, Kyiv", center: [50.44997, 30.45300], namedAfter: "Янгель Михайло Кузьмич", lengthM: 715, since: 1910, wiki: "Вулиця Академіка Янгеля (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-ally-tarasovoi", wd: "Q4471278", uk: "Вулиця Алли Тарасової", en: "Ally Tarasovoi Street", center: [50.45333, 30.51844], namedAfter: "Алла Тарасова", lengthM: 160, wiki: "Вулиця Алли Тарасової" },
  { citySlug: "kyiv", slug: "vulytsia-aliabieva", wd: "Q4471283", uk: "Вулиця Аляб'єва", en: "Hulakiv-Artemovskykh Street, Kyiv", center: [50.48375, 30.48804], namedAfter: "Аляб'єв Олександр Олександрович", lengthM: 950, wiki: "Вулиця Гулаків-Артемовських" },
  { citySlug: "kyiv", slug: "vulytsia-amvrosiia-buchmy", wd: "Q12091179", uk: "Вулиця Амвросія Бучми", en: "Amvrosiia Buchmy Street, Kyiv", center: [50.43364, 30.60247], namedAfter: "Амвросій Бучма", lengthM: 500, wiki: "Бульвар Амвросія Бучми" },
  { citySlug: "kyiv", slug: "vulytsia-anatoliia-petrytskoho", wd: "Q12091183", uk: "Вулиця Анатолія Петрицького", en: "Anatoliia Petrytskoho Street, Kyiv", center: [50.45393, 30.37936], namedAfter: "Петрицький Анатолій Галактіонович", lengthM: 640, wiki: "Вулиця Анатолія Петрицького" },
  { citySlug: "kyiv", slug: "vulytsia-andriia-malyshka", wd: "Q12091190", uk: "Вулиця Андрія Малишка", en: "Andriya Malyshka Street", center: [50.45606, 30.60947], namedAfter: "Малишко Андрій Самійлович", wiki: "Вулиця Андрія Малишка (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-anny-akhmatovoi", wd: "Q12091192", uk: "Вулиця Анни Ахматової", en: "Anny Akhmatovoi Street", center: [50.40892, 30.62937], namedAfter: "Ахматова Анна Андріївна", lengthM: 2340, wiki: "Вулиця Анни Ахматової (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-antona-tsedika", wd: "Q12091611", uk: "Вулиця Антона Цедіка", en: "Antona Tsedika Street, Kyiv", center: [50.45885, 30.43992], namedAfter: "Цедік Антон Ігорович", wiki: "Вулиця Антона Цедіка" },
  { citySlug: "kyiv", slug: "vulytsia-arkhitektora-verbytskoho", wd: "Q12091209", uk: "Вулиця Архітектора Вербицького", en: "Arkhitektora Verbytskoho Street", center: [50.40972, 30.67000], namedAfter: "Вербицький Олександр Матвійович", wiki: "Вулиця Архітектора Вербицького" },
  { citySlug: "kyiv", slug: "vulytsia-arkhitektora-kobelieva", wd: "Q12092562", uk: "Вулиця Архітектора Кобелєва", en: "Arkhitektora Kobelieva Street", center: [50.43965, 30.48317], namedAfter: "Кобелєв Олександр Васильович", lengthM: 300, wiki: "Вулиця Архітектора Кобелєва" },
  { citySlug: "kyiv", slug: "vulytsia-baidy-vyshnevetskoho", wd: "Q12092148", uk: "Вулиця Байди-Вишневецького", en: "Baidy-Vyshnevetskoho street, Kyiv", center: [50.51549, 30.44086], namedAfter: "Дмитро Вишневецький", lengthM: 1500, wiki: "Вулиця Байди-Вишневецького (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-bohdana-havrylyshyna", wd: "Q4471595", uk: "Вулиця Богдана Гаврилишина", en: "Bohdana Havrylyshyna Street, Kyiv", center: [50.45122, 30.46681], namedAfter: "Гаврилишин Богдан Дмитрович", wiki: "Вулиця Богдана Гаврилишина (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-bohdana-stupky", wd: "Q4474078", uk: "Вулиця Богдана Ступки", en: "Bohdana Stupky Street", center: [50.44635, 30.52608], namedAfter: "Богдан Ступка", lengthM: 120, wiki: "Вулиця Богдана Ступки (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-borysa-hmyri", wd: "Q12091267", uk: "Вулиця Бориса Гмирі", en: "Borysa Hmyri Street, Kyiv", center: [50.39681, 30.62631], namedAfter: "Гмиря Борис Романович", lengthM: 1030, wiki: "Вулиця Бориса Гмирі (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-borysa-hrinchenka", wd: "Q12091269", uk: "Вулиця Бориса Грінченка", en: "Borysa Hrinchenka Street, Kyiv", center: [50.44943, 30.52062], namedAfter: "Грінченко Борис Дмитрович", lengthM: 350, wiki: "Вулиця Бориса Грінченка (Київ)" },
  { citySlug: "kyiv", slug: "vulytsia-borysa-zhytkova", wd: "Q12091270", uk: "Вулиця Бориса Житкова", en: "Brativ Malakovykh Street, Kyiv", center: [50.47547, 30.43630], namedAfter: "Борис Житков", wiki: "Вулиця Братів Малакових" },
  { citySlug: "kyiv", slug: "vulytsia-borychiv-tik", wd: "Q4471511", uk: "Вулиця Боричів Тік", en: "Borychiv Tik Street", center: [50.45878, 30.52336], wiki: "Вулиця Боричів Тік" },
  { citySlug: "kyiv", slug: "vulytsia-bratstva-tarasivtsiv", wd: "Q12091560", uk: "Вулиця Братства Тарасівців", en: "Bratstva Tarasivtsiv Street, Kyiv", center: [50.40753, 30.65636], namedAfter: "Братство тарасівців", lengthM: 580, wiki: "Вулиця Братства тарасівців" },
  { citySlug: "kyiv", slug: "vulytsia-brativ-zerovykh", wd: "Q12169653", uk: "Вулиця Братів Зерових", en: "Brativ Zerovykh Street", center: [50.42594, 30.47469], namedAfter: "Зеров Дмитро Костянтинович", lengthM: 600, wiki: "Вулиця Братів Зерових" },
  { citySlug: "kyiv", slug: "vulytsia-viacheslava-lypynskoho", wd: "Q12092587", uk: "Вулиця В'ячеслава Липинського", en: "Viacheslava Lypynskoho Street, Kyiv", center: [50.44897, 30.50939], namedAfter: "Липинський В'ячеслав Казимирович", lengthM: 400, wiki: "Вулиця В'ячеслава Липинського (Київ)" },
  { citySlug: "lviv", slug: "ploshcha-staryi-rynok", wd: "Q4365797", uk: "Площа Старий Ринок", en: "Old Market Square", center: [49.84620, 24.02980], wiki: "Площа Старий Ринок" },
  { citySlug: "lviv", slug: "ploshcha-halytska", wd: "Q4132525", uk: "Площа Галицька", en: "Halytska Square, Lviv", center: [49.83951, 24.03248], wiki: "Площа Галицька (Львів)" },
  { citySlug: "lviv", slug: "ploshcha-soborna", wd: "Q4426088", uk: "Площа Соборна", en: "Soborna Square, Lviv", center: [49.83890, 24.03420], wiki: "Площа Соборна (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-brativ-rohatyntsiv", wd: "Q4471529", uk: "Вулиця Братів Рогатинців", en: "Brativ Rohatyntsiv Street, Lviv", center: [49.84040, 24.03340], namedAfter: "Рогатинець Юрій", wiki: "Вулиця Братів Рогатинців" },
  { citySlug: "lviv", slug: "vulytsia-volodymyra-velykoho", wd: "Q4471680", uk: "Вулиця Володимира Великого", en: "Volodymyra Velykoho Street, Lviv", center: [49.80814, 24.01904], namedAfter: "Володимир Святославич", wiki: "Вулиця Володимира Великого (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-virmenska", wd: "Q4069723", uk: "Вулиця Вірменська", center: [49.84300, 24.03000], wiki: "Вулиця Вірменська (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-hetmana-mazepy", wd: "Q4471899", uk: "Вулиця Гетьмана Мазепи", en: "Hetmana Mazepy street, Lviv", center: [49.87140, 24.03680], namedAfter: "Іван Мазепа", wiki: "Вулиця Гетьмана Мазепи (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-kulparkivska", wd: "Q4246578", uk: "Вулиця Кульпарківська", en: "Kulparkivska Street", center: [49.81750, 23.98722], wiki: "Вулиця Кульпарківська" },
  { citySlug: "lviv", slug: "ploshcha-kropyvnytskoho", wd: "Q4365619", uk: "Площа Кропивницького", en: "Kropyvnytskoho Square, Lviv", center: [49.83680, 24.00490], wiki: "Площа Кропивницького" },
  { citySlug: "lviv", slug: "vulytsia-vyhody", wd: "Q15977878", uk: "Вулиця Вигоди", en: "Vyhody Street, Lviv", center: [49.84120, 23.97320], wiki: "Вулиця Вигода" },
  { citySlug: "lviv", slug: "vulytsia-havryshkevycha", wd: "Q16695310", uk: "Вулиця Гавришкевича", en: "Havryshkevycha Street, Lviv", center: [49.84425, 24.03081], namedAfter: "Гавришкевич Сильвестр", wiki: "Вулиця Гавришкевича (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-honty", wd: "Q16695339", uk: "Вулиця Гонти", en: "Honty Street, Lviv", center: [49.84460, 24.03069], wiki: "Вулиця Гонти (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-zamarstynivska", wd: "Q3791126", uk: "Вулиця Замарстинівська", en: "Zamarstynivska Street", center: [49.87075, 24.01948], wiki: "Вулиця Замарстинівська" },
  { citySlug: "lviv", slug: "vulytsia-kalicha-hora", wd: "Q12091674", uk: "Вулиця Каліча Гора", en: "Kalicha Hora Street, Lviv", center: [49.83470, 24.02780], wiki: "Вулиця Каліча Гора" },
  { citySlug: "lviv", slug: "vulytsia-kleparivska", wd: "Q4223372", uk: "Вулиця Клепарівська", en: "Kleparivska Street", center: [49.84849, 24.01564], wiki: "Вулиця Клепарівська" },
  { citySlug: "lviv", slug: "vulytsia-kniahyni-olhy", wd: "Q558259", uk: "Вулиця Княгині Ольги", en: "Kniahyni Olhy Street, Lviv", center: [49.81268, 24.00357], namedAfter: "Ольга", wiki: "Вулиця Княгині Ольги (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-kniazia-mstyslava-udatnoho", wd: "Q16695381", uk: "Вулиця Князя Мстислава Удатного", en: "Mstyslava Udatnoho Street, Lviv", center: [49.84636, 24.02635], namedAfter: "Мстислав Мстиславич", wiki: "Вулиця Князя Мстислава Удатного" },
  { citySlug: "lviv", slug: "vulytsia-kulisha", wd: "Q4472750", uk: "Вулиця Куліша", en: "Kulisha Street, Lviv", center: [49.84757, 24.02424], namedAfter: "Пантелеймон Куліш", wiki: "Вулиця Пантелеймона Куліша (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-lesi-ukrainky", wd: "Q16695409", uk: "Вулиця Лесі Українки", en: "Lesi Ukrainky Street", center: [49.84377, 24.03106], namedAfter: "Леся Українка", wiki: "Вулиця Лесі Українки (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-liubinska", wd: "Q4271437", uk: "Вулиця Любінська", en: "Liubinska Street", center: [49.82525, 23.97325], namedAfter: "Великий Любінь", wiki: "Вулиця Любінська" },
  { citySlug: "lviv", slug: "vulytsia-naukova", wd: "Q20075089", uk: "Вулиця Наукова", en: "Naukova Street", center: [49.80379, 24.00031], wiki: "Вулиця Наукова (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-okruzhna", wd: "Q28112622", uk: "Вулиця Окружна", en: "Okruzhna Street", center: [49.82869, 23.98371], wiki: "Вулиця Окружна (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-pamvy-beryndy", wd: "Q4473501", uk: "Вулиця Памви Беринди", en: "Beryndy Street, Lviv", center: [49.84083, 24.02972], namedAfter: "Беринда Памво", wiki: "Вулиця Памви Беринди (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-stefana-banakha", wd: "Q16695522", uk: "Вулиця Стефана Банаха", en: "Banakha Street, Lviv", center: [49.83030, 24.05940], namedAfter: "Стефан Банах", wiki: "Вулиця Стефана Банаха (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-universytetska", wd: "Q12092537", uk: "Вулиця Університетська", en: "Universytetska Street, Lviv", center: [49.84004, 24.02192], namedAfter: "Львівський національний університет імені Івана Франка", wiki: "Вулиця Університетська (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-chernivetska", wd: "Q20096118", uk: "Вулиця Чернівецька", en: "Chernivetska Street, Lviv", center: [49.83820, 23.99881], wiki: "Вулиця Чернівецька (Львів)" },
  { citySlug: "lviv", slug: "vulytsia-yaponska", wd: "Q16695594", uk: "Вулиця Японська", en: "Yaponska Street, Lviv", center: [49.83356, 24.01028], namedAfter: "Японія", wiki: "Вулиця Японська" },
  { citySlug: "lviv", slug: "ploshcha-kniazia-sviatoslava", wd: "Q16711766", uk: "Площа Князя Святослава", en: "Kniazia Sviatoslava Square, Lviv", center: [49.84240, 24.00978], wiki: "Площа Князя Святослава" },
  { citySlug: "lviv", slug: "ploshcha-petrushevycha", wd: "Q4365703", uk: "Площа Петрушевича", en: "Petrushevych Square, Lviv", center: [49.83285, 24.03648], namedAfter: "Петрушевич Євген Омелянович", wiki: "Площа Петрушевича" },
  { citySlug: "lviv", slug: "ploshcha-sviatoho-yura", wd: "Q4365773", uk: "Площа Святого Юра", en: "St. George's square, Lviv", center: [49.83731, 24.01386], wiki: "Площа Святого Юра" },
  { citySlug: "lviv", slug: "prospekt-sviatoho-ivana-pavla-ii", wd: "Q16695566", uk: "Проспект Святого Івана Павла ІІ", en: "st. John Paul II street", center: [49.80197, 24.03221], wiki: "Проспект Святого Івана Павла II" },
  { citySlug: "odesa", slug: "vulytsia-derybasivska", wd: "Q1975755", uk: "вулиця Дерибасівська", en: "Derybasivska Street", center: [46.48444, 30.73444], lengthM: 945, wiki: "Дерибасівська вулиця" },
  { citySlug: "odesa", slug: "italiiska-vulytsia", wd: "Q13635658", uk: "Італійська вулиця", en: "Italiiska Street", center: [46.48250, 30.74286], since: 1827, wiki: "Італійська вулиця (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-artura-savelieva", wd: "Q4474525", uk: "Вулиця Артура Савельєва", en: "Artura Savelieva Street", center: [46.43917, 30.75222], namedAfter: "Савельєв Артур Юрійович", lengthM: 831, wiki: "Вулиця Артура Савельєва" },
  { citySlug: "odesa", slug: "bulvar-viiskovo-morskykh-syl", wd: "Q41962288", uk: "Бульвар Військово-морських сил", en: "Viiskovo morskykh syl Boulevard", center: [46.49194, 30.73222], namedAfter: "Військово-Морські сили Збройних сил України", since: 1968, wiki: "Бульвар Військово-морських сил" },
  { citySlug: "odesa", slug: "vulytsia-astashkina", wd: "Q42305348", uk: "Вулиця Асташкіна", en: "Astashkina Street", center: [46.47722, 30.72400], namedAfter: "Асташкін Михайло Єгорович", wiki: "Вулиця Асташкіна" },
  { citySlug: "odesa", slug: "vulytsia-vladyslava-buvalkina", wd: "Q125761084", uk: "Вулиця Владислава Бувалкіна", en: "Vladyslava Buvalkina Street", center: [46.58839, 30.79494], namedAfter: "Бувалкін Владислав Віталійович", wiki: "Вулиця Владислава Бувалкіна" },
  { citySlug: "odesa", slug: "vulytsia-vodoprovidna", wd: "Q42306515", uk: "Вулиця Водопровідна", en: "Vodoprovidna Street", center: [46.45575, 30.72908], wiki: "Водопровідна вулиця (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-vsevoloda-zmiienka", wd: "Q42308213", uk: "Вулиця Всеволода Змієнка", en: "Vsevoloda Zmienka Street", center: [46.48494, 30.72736], namedAfter: "Змієнко Всеволод Юхимович", since: 1814, wiki: "Вулиця Всеволода Змієнка (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-karantynna", wd: "Q23835915", uk: "Вулиця Карантинна", en: "Karantynna Street", center: [46.47629, 30.74619], namedAfter: "Одеський карантин", since: 1828, wiki: "Карантинна вулиця (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-kachynskoho", wd: "Q21665536", uk: "Вулиця Качинського", en: "Kachynskoho Street", center: [46.48244, 30.74485], namedAfter: "Лех Качинський", wiki: "Вулиця Качинського (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-miasoidivska", wd: "Q23005569", uk: "Вулиця М'ясоїдівська", en: "Miasoidivska Street", center: [46.47068, 30.72266], wiki: "М'ясоїдівська вулиця" },
  { citySlug: "odesa", slug: "vulytsia-mykhaila-omelianovycha-pavlenka", wd: "Q43307864", uk: "Вулиця Михайла Омеляновича-Павленка", en: "Mykhaila Omelianovycha-Pavlenka Street", center: [46.46611, 30.74889], namedAfter: "Омелянович-Павленко Михайло Володимирович", wiki: "Вулиця Михайла Омеляновича-Павленка (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-novoshchepnyi-riad", wd: "Q15221324", uk: "Вулиця Новощепний ряд", en: "Novoshchepnyi Riad Street", center: [46.46811, 30.73390], wiki: "Вулиця Новощіпний Ряд" },
  { citySlug: "odesa", slug: "vulytsia-pryvozna", wd: "Q43370921", uk: "Вулиця Привозна", en: "Pryvozna Street", center: [46.46958, 30.73058], wiki: "Привозна вулиця (Одеса, Приморський район)" },
  { citySlug: "odesa", slug: "vulytsia-rishelievska", wd: "Q19712815", uk: "Вулиця Рішельєвська", en: "Rishelievska Street", center: [46.47744, 30.73997], namedAfter: "Арман Емманюель дю Плессі, герцог де Рішельє", wiki: "Рішельєвська вулиця (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-serednofontanska", wd: "Q45051290", uk: "Вулиця Середньофонтанська", en: "Seredniofontanska Street", center: [46.46056, 30.73944], namedAfter: "Середній Фонтан", wiki: "Середньофонтанська вулиця" },
  { citySlug: "odesa", slug: "vulytsia-universytetska", wd: "Q43097286", uk: "Вулиця Університетська", en: "Universytetska Street", center: [46.48942, 30.72986], namedAfter: "Одеський національний університет імені І. І. Мечникова", wiki: "Університетська вулиця (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-chornomorskoho-kozatstva", wd: "Q20850445", uk: "Вулиця Чорноморського козацтва", en: "Chornomorskoho Kozatstva Street", center: [46.50589, 30.72458], namedAfter: "Чорноморське козацьке військо", wiki: "Вулиця Чорноморського козацтва" },
  { citySlug: "odesa", slug: "vulytsia-yamchytskoho", wd: "Q42725973", uk: "Вулиця Ямчитського", en: "Yamchytskoho Street", center: [46.46611, 30.74778], wiki: "Вулиця Ямчитського" },
  { citySlug: "odesa", slug: "viiskovyi-uzviz", wd: "Q23304278", uk: "Військовий узвіз", en: "Viiskovyi Uzviz", center: [46.48678, 30.73597], wiki: "Військовий узвіз" },
  { citySlug: "odesa", slug: "devolanivskyi-uzviz", wd: "Q21045179", uk: "Деволанівський узвіз", en: "Devolanivskyi Descent", center: [46.47777, 30.74579], wiki: "Деволанівський узвіз" },
  { citySlug: "odesa", slug: "dihtiarna-vulytsia", wd: "Q42307944", uk: "Дігтярна вулиця", en: "Dihtyarna Street", center: [46.47883, 30.72450], wiki: "Дігтярна вулиця (Одеса)" },
  { citySlug: "odesa", slug: "karantynnyi-uzviz", wd: "Q21055421", uk: "Карантинний узвіз", en: "Karantynnyi Descent", center: [46.48389, 30.74712], namedAfter: "Одеський карантин", since: 1840, wiki: "Карантинний узвіз" },
  { citySlug: "odesa", slug: "kartamyshevska-vulytsia", wd: "Q30499356", uk: "Картамишевська вулиця", en: "Kartamyshevska street", center: [46.47047, 30.71214], wiki: "Картамишевська вулиця" },
  { citySlug: "odesa", slug: "lanzheronivskyi-uzviz", wd: "Q41631254", uk: "Ланжеронівський узвіз", en: "Lanzheronivskyi Descent", center: [46.48469, 30.74547], namedAfter: "Луї Олександр Андро де Ланжерон", wiki: "Ланжеронівський узвіз" },
  { citySlug: "odesa", slug: "olhiivska-vulytsia", wd: "Q43269150", uk: "Ольгіївська вулиця", en: "Olhiivska Street", center: [46.48892, 30.71736], namedAfter: "Потоцька Ольга Станіславівна", wiki: "Ольгіївська вулиця (Одеса)" },
  { citySlug: "odesa", slug: "polskyi-uzviz", wd: "Q21605545", uk: "Польський узвіз", en: "Polskyi Descent", center: [46.48080, 30.74473], since: 1820, wiki: "Польський узвіз" },
  { citySlug: "odesa", slug: "prospekt-nebesnoi-sotni", wd: "Q21660906", uk: "Проспект Небесної Сотні", en: "Nebesnoi Sotni Avenue", center: [46.40692, 30.71078], namedAfter: "Небесна сотня", wiki: "Проспект Небесної Сотні" },
  { citySlug: "odesa", slug: "spyrydonivska-vulytsia", wd: "Q44322630", uk: "Спиридонівська вулиця", en: "Spyrydonivska Street", center: [46.47781, 30.72383], namedAfter: "Святий Спиридон", wiki: "Спиридонівська вулиця (Одеса)" },
  { citySlug: "odesa", slug: "uzviz-vitaliia-blazhka", wd: "Q41994872", uk: "Узвіз Віталія Блажка", en: "Vitaliya Blazhka Descent", center: [46.49539, 30.72528], namedAfter: "Блажко Віталій Олегович", wiki: "Узвіз Віталія Блажка" },
  { citySlug: "odesa", slug: "vulytsia-akademika-korolova", wd: "Q4471189", uk: "вулиця Академіка Корольова", en: "Akademika Korolyova Street", center: [46.40248, 30.72251], namedAfter: "Корольов Сергій Павлович", wiki: "Вулиця Академіка Корольова (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-borysa-litvaka", wd: "Q43225845", uk: "вулиця Бориса Літвака", en: "Borysa Litvaka Street", center: [46.47453, 30.72912], namedAfter: "Літвак Борис Давидович", lengthM: 480, wiki: "Вулиця Бориса Літвака" },
  { citySlug: "odesa", slug: "vulytsia-viacheslava-chornovola", wd: "Q46633619", uk: "вулиця В'ячеслава Чорновола", en: "Viacheslava Chornovola Street", center: [46.46983, 30.74878], namedAfter: "Чорновіл Вячеслав Максимович", wiki: "Вулиця В'ячеслава Чорновола (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-vitaliia-blazhka", wd: "Q125761453", uk: "вулиця Віталія Блажка", en: "Vitaliya Blazhka Street", center: [46.59236, 30.79747], namedAfter: "Блажко Віталій Олегович", wiki: "Вулиця Віталія Блажка" },
  { citySlug: "odesa", slug: "vulytsia-vitaliia-borovyka", wd: "Q105703235", uk: "вулиця Віталія Боровика", en: "Vitaliya Borovyka Street", center: [46.48194, 30.74705], namedAfter: "Боровик Віталій Гаврилович", lengthM: 290, since: 1828, wiki: "Вулиця Віталія Боровика" },
  { citySlug: "odesa", slug: "vulytsia-kostandi", wd: "Q4472614", uk: "вулиця Костанді", en: "Kostandi Street", center: [46.40703, 30.74222], namedAfter: "Костанді Киріак Костянтинович", wiki: "Вулиця Костанді" },
  { citySlug: "odesa", slug: "vulytsia-seminarska", wd: "Q44007467", uk: "вулиця Семінарська", en: "Seminarska Street", center: [46.46278, 30.74100], namedAfter: "Одеська духовна семінарія", wiki: "Семінарська вулиця (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-siechenova", wd: "Q46602991", uk: "вулиця Сєченова", en: "Siechenova Street", center: [46.49222, 30.71850], namedAfter: "Сєченов Іван Михайлович", wiki: "Вулиця Сєченова (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-utosova", wd: "Q77265690", uk: "вулиця Утьосова", en: "Utyosov Street", center: [46.47356, 30.72686], namedAfter: "Утьосов Леонід Осипович", wiki: "Вулиця Утьосова (Одеса)" },
  { citySlug: "odesa", slug: "vulytsia-yukhyma-hellera", wd: "Q86664603", uk: "вулиця Юхима Геллера", en: "Yukhyma Hellera Street", center: [46.42889, 30.73806], namedAfter: "Геллер Юхим Петрович", wiki: "Вулиця Юхима Геллера" },
  { citySlug: "odesa", slug: "provulok-borysa-aizenberha", wd: "Q44306135", uk: "провулок Бориса Айзенберга", en: "Borysa Aizenberha Lane", center: [46.46356, 30.74461], namedAfter: "Айзенберг Борис Борисович", lengthM: 220, wiki: "Провулок Бориса Айзенберга" },
  { citySlug: "kharkiv", slug: "sumska-vulytsia", wd: "Q4446038", uk: "Сумська вулиця", en: "Sumska Street", center: [50.01201, 36.24267], wiki: "Сумська вулиця (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-myronosytska", wd: "Q4296165", uk: "Вулиця Мироносицька", en: "Myronosytska Street", center: [50.00000, 36.23611], wiki: "Мироносицька вулиця" },
  { citySlug: "kharkiv", slug: "maidan-konstytutsii", wd: "Q4365606", uk: "Майдан Конституції", en: "Konstytutsiyi Square, Kharkiv", center: [49.99222, 36.23111], namedAfter: "Конституція України", lengthM: 550, wiki: "Майдан Конституції (Харків)" },
  { citySlug: "kharkiv", slug: "pavlivska-ploshcha", wd: "Q4365749", uk: "Павлівська площа", en: "Pavlivska Square, Kharkiv", center: [49.98778, 36.22944], wiki: "Павлівський майдан" },
  { citySlug: "kharkiv", slug: "iskrynska-vulytsia", wd: "Q4203930", uk: "Іскринська вулиця", en: "Iskynska Street, Kharkiv", center: [49.99444, 36.26667], lengthM: 900, wiki: "Іскринська вулиця" },
  { citySlug: "kharkiv", slug: "aerokosmichnyi-prospekt", wd: "Q4381105", uk: "Аерокосмічний проспект", en: "Haharina Avenue", center: [49.86832, 36.29995], wiki: "Аерокосмічний проспект" },
  { citySlug: "kharkiv", slug: "vulytsia-23-serpnia", wd: "Q4471042", uk: "Вулиця 23 Серпня", en: "23 Serpnia Street, Kharkiv", center: [50.03389, 36.21667], wiki: "Вулиця 23 Серпня (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-akademika-pavlova", wd: "Q16272355", uk: "Вулиця Академіка Павлова", en: "Akademika Pavlova Street, Kharkiv", center: [50.00759, 36.30789], namedAfter: "Павлов Іван Петрович", wiki: "Вулиця Академіка Павлова (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-bohdana-khmelnytskoho", wd: "Q98970984", uk: "Вулиця Богдана Хмельницького", en: "Bohdana Khmelnytskoho Street, Kharkiv", center: [49.98947, 36.25031], namedAfter: "Богдан Хмельницький", lengthM: 770, wiki: "Вулиця Богдана Хмельницького (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-hvardiitsiv-shyronintsiv", wd: "Q20074979", uk: "Вулиця Гвардійців-Широнінців", en: "Hvardiitsiv-Shyronintsiv Street", center: [50.01347, 36.34736], namedAfter: "Широнінці", wiki: "Вулиця Гвардійців-Широнінців (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-holdberhivska", wd: "Q28706907", uk: "Вулиця Гольдбергівська", en: "Holberhivska Street", center: [49.97625, 36.23625], wiki: "Гольдбергівська вулиця" },
  { citySlug: "kharkiv", slug: "vulytsia-kvitky-osnovianenka", wd: "Q4472415", uk: "Вулиця Квітки-Основ'яненка", en: "Kvitky-Osnovianenka Street, Kharkiv", center: [49.98972, 36.23139], namedAfter: "Григорій Квітка-Основ'яненко", lengthM: 350, wiki: "Вулиця Квітки-Основ'яненка (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-kooperatyvna", wd: "Q28707392", uk: "Вулиця Кооперативна", en: "Kooperatyvna Street", center: [49.98736, 36.23542], lengthM: 780, wiki: "Кооперативна вулиця (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-marshala-rybalka", wd: "Q4473849", uk: "Вулиця Маршала Рибалка", en: "Rybalka Street, Kharkiv", center: [49.95611, 36.34417], namedAfter: "Рибалко Павло Семенович", wiki: "Вулиця Бригади Хартія" },
  { citySlug: "kharkiv", slug: "vulytsia-moskalivska", wd: "Q4473415", uk: "Вулиця Москалівська", en: "Moskalivska Street", center: [49.96917, 36.21583], wiki: "Москалівська вулиця" },
  { citySlug: "kharkiv", slug: "vulytsia-otakara-yarosha", wd: "Q4473480", uk: "Вулиця Отакара Яроша", en: "Otakara Yarosha Street, Kharkiv", center: [50.03056, 36.23333], namedAfter: "Отакар Ярош", wiki: "Вулиця Отакара Яроша (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-poltavskyi-shliakh", wd: "Q4370811", uk: "Вулиця Полтавський Шлях", en: "Poltavskyi Shliakh Street", center: [49.98850, 36.22647], namedAfter: "Полтава", wiki: "Вулиця Полтавський Шлях" },
  { citySlug: "kharkiv", slug: "vulytsia-rustaveli", wd: "Q33039052", uk: "Вулиця Руставелі", en: "Rustaveli Street", center: [49.98622, 36.24367], namedAfter: "Шота Руставелі", lengthM: 1100, wiki: "Вулиця Руставелі (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-universytetska", wd: "Q4475867", uk: "Вулиця Університетська", en: "Universytetska Street, Kharkiv", center: [49.99083, 36.23014], wiki: "Університетська вулиця (Харків)" },
  { citySlug: "kharkiv", slug: "klochkivska-vulytsia", wd: "Q4224156", uk: "Клочківська вулиця", en: "Klochkivska Street, Kharkiv", center: [49.99053, 36.22762], wiki: "Клочківська вулиця" },
  { citySlug: "kharkiv", slug: "kontorska-vulytsia", wd: "Q4238858", uk: "Конторська вулиця", en: "Kontorska Street", center: [49.98153, 36.21722], wiki: "Конторська вулиця (Харків)" },
  { citySlug: "kharkiv", slug: "sobornyi-uzviz", wd: "Q4426096", uk: "Соборний узвіз", en: "Sobornyi Descent", center: [49.99042, 36.22722], wiki: "Соборний узвіз (Харків)" },
  { citySlug: "kharkiv", slug: "uzviz-klochkivskyi", wd: "Q4438255", uk: "Узвіз Клочківський", en: "Klochkovskyi Uzviz", center: [50.00417, 36.22222], lengthM: 710, wiki: "Клочківський узвіз" },
  { citySlug: "kharkiv", slug: "vulytsia-zhon-myronosyts", wd: "Q4426581", uk: "вулиця Жон Мироносиць", en: "Radnarkomivska Street, Kharkiv", center: [49.99889, 36.23750], lengthM: 480, wiki: "Вулиця Жон Мироносиць (Харків)" },
  { citySlug: "kharkiv", slug: "vulytsia-neskorenykh", wd: "Q65205917", uk: "вулиця Нескорених", en: "Neskorenykh Street, Kharkiv", center: [50.02942, 36.30267], wiki: "Вулиця Нескорених (Харків)" },
  { citySlug: "dnipro", slug: "sicheslavska-naberezhna", wd: "Q4163209", uk: "Січеславська Набережна", en: "Sicheslavska Naberezhna", center: [48.47267, 35.04253], namedAfter: "Січеслав", lengthM: 30, wiki: "Січеславська Набережна" },
  { citySlug: "dnipro", slug: "vulytsia-nezalezhnosti", wd: "Q4474218", uk: "Вулиця Незалежності", en: "Vulytsia Nezalezhnosti", center: [48.43100, 35.00697], wiki: "Вулиця Незалежності (Дніпро)" },
  { citySlug: "dnipro", slug: "kelnskyi-bulvar", wd: "Q30965865", uk: "Кельнський бульвар", en: "Kelnsky Bulvar", center: [48.46110, 35.05014], namedAfter: "Кельн", wiki: "Кельнський бульвар" },
  { citySlug: "dnipro", slug: "ploshcha-heroiv-maidanu", wd: "Q20069222", uk: "Площа Героїв Майдану", en: "Heroyiv Maydanu Square, Dnipro", center: [48.46400, 35.04550], wiki: "Площа Героїв Майдану (Дніпро)" },
];

export const STREETS_BY_CITY: Record<string, CityStreet[]> = CITY_STREETS.reduce(
  (acc, s) => {
    (acc[s.citySlug] ??= []).push(s);
    return acc;
  },
  {} as Record<string, CityStreet[]>,
);
