// ──────────────────────────────────────────────────────────────────────────
// СТОРІНКИ ГІР (/gory/[slug]) — 25.09.2026, SEO-хвиля «окрема сторінка на кожну
// вершину режиму «Гори»». Кожна вершина = пресет бекенду (/api/mountains/presets,
// presetId), кнопка веде в /mountains?peak=<presetId> з уже обраною горою.
//
// Правила контенту: факти — лише загальновідомі (висота, хребет, країна, перше
// сходження); «що видно на моделі» — чесно з того, що справді дає рельєф ділянки
// areaKm×areaKm км. Ціна друку гори — за запитом (як у самому режимі «Гори»).
// Ельбрус із пресетів навмисно НЕ має сторінки (Росія — недоречно для бренду).
// Усі 6 мов — справжні тексти (не фолбек), тож індексуються всі.
// ──────────────────────────────────────────────────────────────────────────

export type PeakLocale = "uk" | "en" | "de" | "pl" | "fr" | "es";
export const PEAK_LOCALES: PeakLocale[] = ["uk", "en", "de", "pl", "fr", "es"];

type PeakText = {
  name: string;
  country: string;
  title: string; // <title> і h1
  p: [string, string, string]; // про гору · що видно на моделі · кому подарувати
};

export type Peak = {
  slug: string;
  presetId: string;
  elev: number;
  areaKm: number;
  photo: string;
  lat: number;
  lon: number;
  t: Record<PeakLocale, PeakText>;
};

export const PEAKS: Peak[] = [
  {
    slug: "hoverla", presetId: "hoverla", elev: 2061, areaKm: 5, lat: 48.16, lon: 24.50028, photo: "/mountains/presets/hoverla.jpg",
    t: {
      uk: { name: "Говерла", country: "Україна, Чорногора", title: "3D-модель Говерли — найвища гора України на вашій полиці",
        p: ["Говерла (2061 м) — найвища вершина України і Чорногірського хребта Українських Карпат, на межі Закарпатської та Івано-Франківської областей. На неї щоліта піднімаються тисячі людей, і для багатьох це перша справжня гора.",
          "Модель охоплює ділянку близько 5×5 км: видно сам купол Говерли, сідловину в бік Петроса, гребінь Чорногори й долини, якими йдуть маршрути з Заросляка. Висоти — з супутникової моделі рельєфу, вертикаль можна підсилити, щоб схили читались рельєфніше.",
          "Хороший подарунок тому, хто вже був на Говерлі, — з фігуркою людини на вершині й датою сходження на ободку. Або тим, хто сумує за Карпатами і хоче мати гори вдома."] },
      en: { name: "Hoverla", country: "Ukraine, Chornohora", title: "3D model of Hoverla — Ukraine's highest mountain for your shelf",
        p: ["Hoverla (2,061 m) is the highest peak of Ukraine and of the Chornohora ridge in the Ukrainian Carpathians, on the border of the Zakarpattia and Ivano-Frankivsk regions. Thousands of people climb it every summer, and for many it is their first real mountain.",
          "The model covers an area of about 5×5 km: the dome of Hoverla, the saddle towards Petros, the Chornohora ridge and the valleys the trails follow from Zarosliak. Elevations come from a satellite terrain model, and the vertical can be exaggerated so the slopes read more clearly.",
          "A great gift for someone who has already stood on Hoverla — with a figure on the summit and the climb date on the frame. Or for anyone who misses the Carpathians and wants the mountains at home."] },
      de: { name: "Howerla", country: "Ukraine, Tschornohora", title: "3D-Modell der Howerla — der höchste Berg der Ukraine fürs Regal",
        p: ["Die Howerla (2061 m) ist der höchste Gipfel der Ukraine und des Tschornohora-Kamms in den ukrainischen Karpaten, an der Grenze der Oblaste Transkarpatien und Iwano-Frankiwsk. Jeden Sommer steigen Tausende hinauf — für viele ist es der erste richtige Berg.",
          "Das Modell zeigt einen Ausschnitt von etwa 5×5 km: die Kuppe der Howerla, den Sattel zum Petros, den Kamm der Tschornohora und die Täler, durch die die Wege von Sarosljak führen. Die Höhen stammen aus einem Satelliten-Geländemodell, die Vertikale lässt sich überhöhen.",
          "Ein schönes Geschenk für alle, die schon oben standen — mit einer Figur auf dem Gipfel und dem Datum auf dem Rahmen. Oder für alle, die die Karpaten vermissen."] },
      pl: { name: "Howerla", country: "Ukraina, Czarnohora", title: "Model 3D Howerli — najwyższa góra Ukrainy na twojej półce",
        p: ["Howerla (2061 m) to najwyższy szczyt Ukrainy i pasma Czarnohory w Karpatach Ukraińskich, na granicy obwodów zakarpackiego i iwanofrankiwskiego. Przed wojną biegła tędy granica polsko-czechosłowacka — do dziś stoją tu graniczne słupki.",
          "Model obejmuje obszar około 5×5 km: kopułę Howerli, przełęcz w stronę Petrosa, grzbiet Czarnohory i doliny, którymi prowadzą szlaki z Zaroślaka. Wysokości pochodzą z satelitarnego modelu terenu, a pionową skalę można wzmocnić.",
          "Dobry prezent dla kogoś, kto już stał na Howerli — z figurką na szczycie i datą wejścia na ramce. Albo dla każdego, kto tęskni za Karpatami."] },
      fr: { name: "Hoverla", country: "Ukraine, Tchornohora", title: "Maquette 3D de l'Hoverla — le plus haut sommet d'Ukraine sur votre étagère",
        p: ["L'Hoverla (2 061 m) est le point culminant de l'Ukraine et de la chaîne de Tchornohora, dans les Carpates ukrainiennes, à la limite des oblasts de Transcarpatie et d'Ivano-Frankivsk. Des milliers de randonneurs y montent chaque été.",
          "La maquette couvre une zone d'environ 5×5 km : le dôme de l'Hoverla, le col vers le Petros, la crête de Tchornohora et les vallées empruntées par les sentiers depuis Zarosliak. Les altitudes viennent d'un modèle satellite du relief, avec une exagération verticale réglable.",
          "Un beau cadeau pour quelqu'un qui a déjà atteint le sommet — avec une figurine au sommet et la date gravée sur le cadre. Ou pour tous ceux à qui les Carpates manquent."] },
      es: { name: "Hoverla", country: "Ucrania, Chornohora", title: "Maqueta 3D del Hoverla — la montaña más alta de Ucrania en tu estantería",
        p: ["El Hoverla (2061 m) es el pico más alto de Ucrania y de la cordillera de Chornohora, en los Cárpatos ucranianos, en el límite de las regiones de Transcarpatia e Ivano-Frankivsk. Miles de personas lo suben cada verano.",
          "La maqueta abarca unos 5×5 km: la cúpula del Hoverla, el collado hacia el Petros, la cresta de Chornohora y los valles por los que suben los senderos desde Zarosliak. Las alturas provienen de un modelo satelital del terreno, con exageración vertical ajustable.",
          "Un buen regalo para quien ya ha estado en la cima — con una figura en la cumbre y la fecha grabada en el marco. O para quien echa de menos los Cárpatos."] },
    },
  },
  {
    slug: "petros", presetId: "petros", elev: 2020, areaKm: 4, lat: 48.17194, lon: 24.42056, photo: "/mountains/presets/petros.jpg",
    t: {
      uk: { name: "Петрос", country: "Україна, Чорногора", title: "3D-модель гори Петрос — гостра вершина Чорногори",
        p: ["Петрос (2020 м) — одна з найвищих вершин Українських Карпат, сусідка Говерли на заході Чорногірського масиву. На відміну від пологої Говерли, Петрос має виразну пірамідальну форму і круті схили — його легко впізнати з будь-якого боку.",
          "Ділянка моделі — близько 4×4 км: сама піраміда Петроса, сідловина до Говерли та глибокі долини, що спадають до Кваси й Богдана. Завдяки меншій площі схили на моделі виходять крутими й виразними.",
          "Подарунок для тих, хто проходив чорногірський хребет «від Петроса до Попа Івана» або ночував у наметі під вершиною. Можна додати фігурку туриста й напис з датою походу."] },
      en: { name: "Petros", country: "Ukraine, Chornohora", title: "3D model of Petros — the sharp peak of Chornohora",
        p: ["Petros (2,020 m) is one of the highest peaks of the Ukrainian Carpathians, Hoverla's neighbour at the western end of the Chornohora massif. Unlike the gentle dome of Hoverla, Petros is a distinct pyramid with steep slopes that is easy to recognise from any side.",
          "The model covers about 4×4 km: the Petros pyramid, the saddle towards Hoverla and the deep valleys falling towards Kvasy and Bohdan. With the smaller area the slopes come out steep and expressive.",
          "A gift for anyone who has walked the Chornohora ridge from Petros to Pip Ivan or camped below the summit. Add a hiker figure and the date of the trek."] },
      de: { name: "Petros", country: "Ukraine, Tschornohora", title: "3D-Modell des Petros — der spitze Gipfel der Tschornohora",
        p: ["Der Petros (2020 m) ist einer der höchsten Gipfel der ukrainischen Karpaten, Nachbar der Howerla am Westende des Tschornohora-Massivs. Anders als die sanfte Howerla ist der Petros eine markante Pyramide mit steilen Flanken.",
          "Das Modell zeigt etwa 4×4 km: die Pyramide des Petros, den Sattel zur Howerla und die tiefen Täler Richtung Kwassy und Bohdan. Durch den kleineren Ausschnitt wirken die Hänge steil und plastisch.",
          "Ein Geschenk für alle, die den Tschornohora-Kamm vom Petros bis zum Pip Iwan gegangen sind — mit Wanderfigur und Datum der Tour."] },
      pl: { name: "Petros", country: "Ukraina, Czarnohora", title: "Model 3D Petrosa — ostry szczyt Czarnohory",
        p: ["Petros (2020 m) to jeden z najwyższych szczytów Karpat Ukraińskich, sąsiad Howerli na zachodnim krańcu masywu Czarnohory. W przeciwieństwie do łagodnej Howerli ma wyraźny kształt piramidy i strome zbocza.",
          "Model obejmuje około 4×4 km: piramidę Petrosa, przełęcz w stronę Howerli i głębokie doliny opadające ku Kwasom i Bohdanowi. Dzięki mniejszemu obszarowi stoki wychodzą strome i wyraziste.",
          "Prezent dla kogoś, kto szedł grzbietem Czarnohory od Petrosa po Pop Iwan albo nocował pod szczytem — z figurką turysty i datą wyprawy."] },
      fr: { name: "Petros", country: "Ukraine, Tchornohora", title: "Maquette 3D du Petros — le sommet pointu de Tchornohora",
        p: ["Le Petros (2 020 m) est l'un des plus hauts sommets des Carpates ukrainiennes, voisin de l'Hoverla à l'ouest du massif de Tchornohora. Contrairement au dôme doux de l'Hoverla, c'est une pyramide nette aux pentes raides.",
          "La maquette couvre environ 4×4 km : la pyramide du Petros, le col vers l'Hoverla et les vallées profondes qui descendent vers Kvasy et Bohdan. Sur une zone plus petite, les pentes ressortent raides et expressives.",
          "Un cadeau pour ceux qui ont parcouru la crête de Tchornohora du Petros au Pip Ivan — avec une figurine de randonneur et la date de la sortie."] },
      es: { name: "Petros", country: "Ucrania, Chornohora", title: "Maqueta 3D del Petros — el pico afilado de Chornohora",
        p: ["El Petros (2020 m) es uno de los picos más altos de los Cárpatos ucranianos, vecino del Hoverla en el extremo occidental del macizo de Chornohora. A diferencia de la cúpula suave del Hoverla, es una pirámide nítida de laderas empinadas.",
          "La maqueta abarca unos 4×4 km: la pirámide del Petros, el collado hacia el Hoverla y los valles profundos que bajan hacia Kvasy y Bohdan. Con un área menor, las laderas salen empinadas y expresivas.",
          "Un regalo para quien ha recorrido la cresta de Chornohora del Petros al Pip Ivan — con una figura de excursionista y la fecha de la ruta."] },
    },
  },
  {
    slug: "pip-ivan", presetId: "pip_ivan", elev: 2028, areaKm: 4, lat: 48.04861, lon: 24.62806, photo: "/mountains/presets/pip_ivan.jpg",
    t: {
      uk: { name: "Піп Іван Чорногірський", country: "Україна, Чорногора", title: "3D-модель гори Піп Іван — вершина з обсерваторією «Білий слон»",
        p: ["Піп Іван Чорногірський (2028 м) — одна з найвищих вершин Українських Карпат на південно-східному краю Чорногори. На самій вершині стоять кам'яні стіни колишньої астрономічної обсерваторії 1930-х років, яку в народі називають «Білий слон».",
          "Модель охоплює ділянку близько 4×4 км: вершину, гребінь Чорногори, що тягнеться на північний захід, і круті кари з озерами на схилах. Рельєф тут різкий, тож навіть без великої вертикальної надбавки модель виглядає гірською.",
          "Для тих, хто дійшов до «Білого слона» — фінальної точки класичного траверсу Чорногори. На ободку можна вигравіювати назву маршруту або дату."] },
      en: { name: "Pip Ivan Chornohirskyi", country: "Ukraine, Chornohora", title: "3D model of Pip Ivan — the peak with the “White Elephant” observatory",
        p: ["Pip Ivan Chornohirskyi (2,028 m) is one of the highest peaks of the Ukrainian Carpathians, at the south-eastern end of Chornohora. On the summit stand the stone walls of a 1930s astronomical observatory, known as the “White Elephant”.",
          "The model covers about 4×4 km: the summit, the Chornohora ridge running north-west and the steep cirques on its slopes. The terrain is sharp, so the model looks properly alpine even without much vertical exaggeration.",
          "For anyone who has reached the “White Elephant” — the finishing point of the classic Chornohora traverse. Engrave the route name or date on the frame."] },
      de: { name: "Pip Iwan Tschornohirskyj", country: "Ukraine, Tschornohora", title: "3D-Modell des Pip Iwan — der Gipfel mit der Sternwarte „Weißer Elefant“",
        p: ["Der Pip Iwan Tschornohirskyj (2028 m) ist einer der höchsten Gipfel der ukrainischen Karpaten am Südostende der Tschornohora. Auf dem Gipfel stehen die Steinmauern einer Sternwarte aus den 1930er-Jahren, genannt „Weißer Elefant“.",
          "Das Modell zeigt etwa 4×4 km: den Gipfel, den nach Nordwesten ziehenden Kamm und die steilen Kare an den Hängen. Das Relief ist schroff — das Modell wirkt auch ohne starke Überhöhung alpin.",
          "Für alle, die den „Weißen Elefanten“ erreicht haben — Endpunkt der klassischen Tschornohora-Überschreitung. Route oder Datum kommen auf den Rahmen."] },
      pl: { name: "Pop Iwan Czarnohorski", country: "Ukraina, Czarnohora", title: "Model 3D Popa Iwana — szczyt z obserwatorium „Biały Słoń”",
        p: ["Pop Iwan Czarnohorski (2028 m) to jeden z najwyższych szczytów Karpat Ukraińskich, na południowo-wschodnim krańcu Czarnohory. Na szczycie stoją kamienne mury polskiego obserwatorium astronomicznego z 1938 roku, zwanego „Białym Słoniem”.",
          "Model obejmuje około 4×4 km: szczyt, grzbiet Czarnohory biegnący na północny zachód i strome kotły na zboczach. Rzeźba jest ostra, więc model wygląda górsko nawet bez dużego przewyższenia.",
          "Dla każdego, kto doszedł do „Białego Słonia” — mety klasycznego trawersu Czarnohory. Na ramce można wygrawerować nazwę szlaku lub datę."] },
      fr: { name: "Pip Ivan Tchornohirsky", country: "Ukraine, Tchornohora", title: "Maquette 3D du Pip Ivan — le sommet de l'observatoire « Éléphant blanc »",
        p: ["Le Pip Ivan Tchornohirsky (2 028 m) est l'un des plus hauts sommets des Carpates ukrainiennes, à l'extrémité sud-est de Tchornohora. Au sommet se dressent les murs de pierre d'un observatoire astronomique des années 1930, surnommé « l'Éléphant blanc ».",
          "La maquette couvre environ 4×4 km : le sommet, la crête de Tchornohora vers le nord-ouest et les cirques raides sur ses flancs. Le relief est vif : la maquette paraît alpine même sans forte exagération verticale.",
          "Pour ceux qui ont atteint « l'Éléphant blanc », arrivée de la traversée classique de Tchornohora — avec le nom de l'itinéraire ou la date sur le cadre."] },
      es: { name: "Pip Ivan Chornohirski", country: "Ucrania, Chornohora", title: "Maqueta 3D del Pip Ivan — la cumbre del observatorio «Elefante Blanco»",
        p: ["El Pip Ivan Chornohirski (2028 m) es uno de los picos más altos de los Cárpatos ucranianos, en el extremo sureste de Chornohora. En la cima se alzan los muros de piedra de un observatorio astronómico de los años 30, llamado «Elefante Blanco».",
          "La maqueta abarca unos 4×4 km: la cumbre, la cresta de Chornohora hacia el noroeste y los circos empinados de sus laderas. El relieve es abrupto, así que la maqueta parece alpina incluso sin mucha exageración vertical.",
          "Para quien ha llegado al «Elefante Blanco», final de la travesía clásica de Chornohora — con el nombre de la ruta o la fecha en el marco."] },
    },
  },
  {
    slug: "ai-petri", presetId: "ai_petri", elev: 1234, areaKm: 5, lat: 44.45111, lon: 34.05639, photo: "/mountains/presets/ai_petri.jpg",
    t: {
      uk: { name: "Ай-Петрі", country: "Україна, Крим", title: "3D-модель Ай-Петрі — зубці Кримських гір над морем",
        p: ["Ай-Петрі (1234 м) — одна з найвідоміших вершин Кримських гір над Південним узбережжям Криму. Її впізнають за скельними зубцями на гребені й за урвищем, що обривається до моря над Алупкою та Місхором.",
          "Модель охоплює близько 5×5 км: плато Ай-Петрі, скельний край яйли й круті схили до узбережжя. Різкий перепад від плато до моря на моделі читається особливо добре.",
          "Подарунок для тих, хто памʼятає Крим до окупації і чекає повернення — місце, яке хочеться мати перед очима. На ободку можна написати «Крим — це Україна» або дату поїздки."] },
      en: { name: "Ai-Petri", country: "Ukraine, Crimea", title: "3D model of Ai-Petri — the jagged teeth of the Crimean Mountains",
        p: ["Ai-Petri (1,234 m) is one of the best-known peaks of the Crimean Mountains above the southern coast of Crimea. It is recognised by the rocky teeth on its ridge and the cliff that drops towards the sea above Alupka and Miskhor.",
          "The model covers about 5×5 km: the Ai-Petri plateau, the rocky edge of the yaila and the steep slopes down to the coast. The sharp drop from plateau to sea reads especially well on the model.",
          "A gift for those who remember Crimea before the occupation and wait for its return. The frame can carry “Crimea is Ukraine” or the date of a trip."] },
      de: { name: "Ai-Petri", country: "Ukraine, Krim", title: "3D-Modell des Ai-Petri — die Felszähne des Krimgebirges",
        p: ["Der Ai-Petri (1234 m) ist einer der bekanntesten Gipfel des Krimgebirges über der Südküste der Krim, erkennbar an den Felszähnen am Grat und der Steilwand über Alupka und Mischor.",
          "Das Modell zeigt etwa 5×5 km: das Plateau des Ai-Petri, den felsigen Rand der Jaila und die steilen Hänge zur Küste. Der scharfe Abfall vom Plateau zum Meer ist auf dem Modell besonders gut lesbar.",
          "Ein Geschenk für alle, die sich an die Krim vor der Besetzung erinnern und auf ihre Rückkehr warten — mit „Die Krim ist Ukraine“ oder einem Reisedatum auf dem Rahmen."] },
      pl: { name: "Aj-Petri", country: "Ukraina, Krym", title: "Model 3D Aj-Petri — skalne zęby Gór Krymskich",
        p: ["Aj-Petri (1234 m) to jeden z najbardziej znanych szczytów Gór Krymskich nad południowym wybrzeżem Krymu, rozpoznawalny po skalnych zębach na grani i urwisku nad Ałupką i Miskhorem.",
          "Model obejmuje około 5×5 km: płaskowyż Aj-Petri, skalną krawędź jajły i strome zbocza ku wybrzeżu. Ostry spadek z płaskowyżu do morza szczególnie dobrze widać na modelu.",
          "Prezent dla tych, którzy pamiętają Krym sprzed okupacji i czekają na jego powrót — z napisem „Krym to Ukraina” albo datą podróży na ramce."] },
      fr: { name: "Aï-Petri", country: "Ukraine, Crimée", title: "Maquette 3D de l'Aï-Petri — les dents rocheuses des monts de Crimée",
        p: ["L'Aï-Petri (1 234 m) est l'un des sommets les plus connus des monts de Crimée, au-dessus de la côte sud. On le reconnaît à ses dents rocheuses et à la falaise qui plonge vers la mer au-dessus d'Aloupka et de Miskhor.",
          "La maquette couvre environ 5×5 km : le plateau de l'Aï-Petri, le rebord rocheux de la yaïla et les pentes raides vers la côte. La chute brutale du plateau vers la mer se lit particulièrement bien.",
          "Un cadeau pour ceux qui se souviennent de la Crimée avant l'occupation et attendent son retour — avec « La Crimée, c'est l'Ukraine » ou la date d'un voyage sur le cadre."] },
      es: { name: "Ai-Petri", country: "Ucrania, Crimea", title: "Maqueta 3D del Ai-Petri — los dientes de roca de los montes de Crimea",
        p: ["El Ai-Petri (1234 m) es uno de los picos más conocidos de los montes de Crimea, sobre la costa sur. Se reconoce por los dientes de roca de su cresta y el acantilado que cae hacia el mar sobre Alupka y Miskhor.",
          "La maqueta abarca unos 5×5 km: la meseta del Ai-Petri, el borde rocoso de la yaila y las laderas empinadas hacia la costa. La caída brusca de la meseta al mar se lee muy bien.",
          "Un regalo para quienes recuerdan Crimea antes de la ocupación y esperan su regreso — con «Crimea es Ucrania» o la fecha de un viaje en el marco."] },
    },
  },
  {
    slug: "matterhorn", presetId: "matterhorn", elev: 4478, areaKm: 3.6, lat: 45.9764, lon: 7.6586, photo: "/mountains/presets/matterhorn.jpg",
    t: {
      uk: { name: "Матергорн", country: "Швейцарія / Італія", title: "3D-модель Матергорна — найвідоміша піраміда Альп",
        p: ["Матергорн (4478 м) — вершина Пеннінських Альп на кордоні Швейцарії та Італії, над Церматтом. Його майже ідеальну чотиригранну піраміду знають навіть ті, хто ніколи не був у горах; перше сходження здійснив Едвард Вімпер у 1865 році.",
          "Для Швейцарії ми беремо лідарні висоти з точністю 2 м, тож на моделі ділянкою близько 3,6×3,6 км видно ребра Гернлі та Цмутт, льодовики й кулуари. Скельні боки моделі підкреслюють, наскільки круто гора виростає з долини.",
          "Подарунок альпіністу, лижнику, який катався в Церматті, або просто любителю гір — Матергорн добре виглядає на полиці навіть без ободка. Можна додати фігурку скелелаза на найкрутішій стіні."] },
      en: { name: "Matterhorn", country: "Switzerland / Italy", title: "3D model of the Matterhorn — the most famous pyramid of the Alps",
        p: ["The Matterhorn (4,478 m) rises in the Pennine Alps on the Swiss–Italian border above Zermatt. Its near-perfect four-sided pyramid is known even to people who have never been to the mountains; Edward Whymper made the first ascent in 1865.",
          "For Switzerland we use lidar elevations with 2 m precision, so a model of about 3.6×3.6 km shows the Hörnli and Zmutt ridges, the glaciers and couloirs. Rocky sides emphasise how steeply the mountain rises from the valley.",
          "A gift for a climber, a skier who has been to Zermatt or anyone who loves mountains — the Matterhorn looks great on a shelf even without a frame. Add a climber figure on the steepest face."] },
      de: { name: "Matterhorn", country: "Schweiz / Italien", title: "3D-Modell des Matterhorns — die berühmteste Pyramide der Alpen",
        p: ["Das Matterhorn (4478 m) erhebt sich in den Walliser Alpen an der Grenze zwischen der Schweiz und Italien über Zermatt. Seine fast perfekte vierseitige Pyramide kennt jeder; die Erstbesteigung gelang Edward Whymper 1865.",
          "Für die Schweiz nutzen wir Lidar-Höhen (swissALTI3D, 2 m), deshalb zeigt ein Modell von etwa 3,6×3,6 km den Hörnli- und den Zmuttgrat, Gletscher und Couloirs. Felsige Seitenwände betonen, wie steil der Berg aus dem Tal wächst.",
          "Ein Geschenk für Bergsteiger, Skifahrer aus Zermatt oder alle Bergfreunde — das Matterhorn wirkt im Regal auch ohne Rahmen. Auf Wunsch mit Kletterfigur an der steilsten Wand."] },
      pl: { name: "Matterhorn", country: "Szwajcaria / Włochy", title: "Model 3D Matterhornu — najsłynniejsza piramida Alp",
        p: ["Matterhorn (4478 m) wznosi się w Alpach Pennińskich na granicy Szwajcarii i Włoch, nad Zermatt. Jego niemal idealną czworościenną piramidę zna każdy; pierwszego wejścia dokonał Edward Whymper w 1865 roku.",
          "Dla Szwajcarii używamy wysokości z lidaru o dokładności 2 m, więc model obszaru ok. 3,6×3,6 km pokazuje granie Hörnli i Zmutt, lodowce i żleby. Skalne boki modelu podkreślają, jak stromo góra wyrasta z doliny.",
          "Prezent dla alpinisty, narciarza z Zermatt albo miłośnika gór — Matterhorn świetnie wygląda na półce nawet bez ramki. Można dodać figurkę wspinacza na najbardziej stromej ścianie."] },
      fr: { name: "Cervin", country: "Suisse / Italie", title: "Maquette 3D du Cervin (Matterhorn) — la pyramide la plus célèbre des Alpes",
        p: ["Le Cervin (4 478 m) se dresse dans les Alpes pennines, à la frontière italo-suisse, au-dessus de Zermatt. Sa pyramide presque parfaite à quatre faces est connue de tous ; Edward Whymper en a réussi la première ascension en 1865.",
          "Pour la Suisse, nous utilisons des altitudes lidar précises à 2 m : une maquette d'environ 3,6×3,6 km montre les arêtes du Hörnli et de Zmutt, les glaciers et les couloirs. Les flancs rocheux soulignent la raideur du sommet.",
          "Un cadeau pour un alpiniste, un skieur passé par Zermatt ou tout amoureux des montagnes — le Cervin fait son effet sur une étagère, même sans cadre. Ajoutez un grimpeur sur la face la plus raide."] },
      es: { name: "Cervino (Matterhorn)", country: "Suiza / Italia", title: "Maqueta 3D del Cervino — la pirámide más famosa de los Alpes",
        p: ["El Cervino o Matterhorn (4478 m) se alza en los Alpes Peninos, en la frontera entre Suiza e Italia, sobre Zermatt. Su pirámide casi perfecta de cuatro caras la conoce todo el mundo; Edward Whymper hizo la primera ascensión en 1865.",
          "Para Suiza usamos alturas lidar con precisión de 2 m, así que una maqueta de unos 3,6×3,6 km muestra las aristas Hörnli y Zmutt, los glaciares y los corredores. Los laterales de roca subrayan lo empinado de la montaña.",
          "Un regalo para un alpinista, un esquiador que estuvo en Zermatt o cualquier amante de la montaña — el Cervino luce en la estantería incluso sin marco. Añade un escalador en la cara más empinada."] },
    },
  },
  {
    slug: "mont-blanc", presetId: "mont_blanc", elev: 4808, areaKm: 7, lat: 45.83262, lon: 6.86521, photo: "/mountains/presets/mont_blanc.jpg",
    t: {
      uk: { name: "Монблан", country: "Франція / Італія", title: "3D-модель Монблану — найвища вершина Альп",
        p: ["Монблан (близько 4808 м) — найвища гора Альп і Західної Європи, на кордоні Франції та Італії над Шамоні. Перше сходження у 1786 році здійснили Жак Бальма і Мішель-Габріель Паккар — з нього відлічують історію альпінізму.",
          "Модель охоплює близько 7×7 км: сніговий купол вершини, гострі голки масиву, льодовики, що сповзають у долину Шамоні. Масив великий і складний, тому для нього добре підходять розміри 25–40 см.",
          "Для альпіністів, лижників і всіх, хто бачив Монблан з Егюй-дю-Міді. Модель можна доповнити написом маршруту чи висоти."] },
      en: { name: "Mont Blanc", country: "France / Italy", title: "3D model of Mont Blanc — the highest summit of the Alps",
        p: ["Mont Blanc (about 4,808 m) is the highest mountain of the Alps and of Western Europe, on the French–Italian border above Chamonix. Jacques Balmat and Michel-Gabriel Paccard made the first ascent in 1786, the date modern mountaineering counts from.",
          "The model covers about 7×7 km: the snow dome of the summit, the sharp aiguilles of the massif and the glaciers flowing into the Chamonix valley. The massif is large and complex, so sizes of 25–40 cm suit it best.",
          "For climbers, skiers and anyone who has seen Mont Blanc from the Aiguille du Midi. Add the route name or the altitude to the model."] },
      de: { name: "Mont Blanc", country: "Frankreich / Italien", title: "3D-Modell des Mont Blanc — der höchste Gipfel der Alpen",
        p: ["Der Mont Blanc (etwa 4808 m) ist der höchste Berg der Alpen und Westeuropas, an der französisch-italienischen Grenze über Chamonix. Jacques Balmat und Michel-Gabriel Paccard bestiegen ihn 1786 erstmals — der Beginn des modernen Alpinismus.",
          "Das Modell zeigt etwa 7×7 km: die Schneekuppe, die spitzen Aiguilles des Massivs und die Gletscher ins Tal von Chamonix. Das Massiv ist groß und vielgliedrig — am besten wirkt es in 25–40 cm.",
          "Für Bergsteiger, Skifahrer und alle, die den Mont Blanc von der Aiguille du Midi gesehen haben — mit Routenname oder Höhe als Gravur."] },
      pl: { name: "Mont Blanc", country: "Francja / Włochy", title: "Model 3D Mont Blanc — najwyższy szczyt Alp",
        p: ["Mont Blanc (około 4808 m) to najwyższa góra Alp i Europy Zachodniej, na granicy Francji i Włoch nad Chamonix. Pierwszego wejścia w 1786 roku dokonali Jacques Balmat i Michel-Gabriel Paccard — od tej daty liczy się historia alpinizmu.",
          "Model obejmuje około 7×7 km: śnieżną kopułę szczytu, ostre iglice masywu i lodowce spływające do doliny Chamonix. Masyw jest duży i złożony, dlatego najlepiej wygląda w rozmiarach 25–40 cm.",
          "Dla alpinistów, narciarzy i wszystkich, którzy widzieli Mont Blanc z Aiguille du Midi — z nazwą drogi lub wysokością na ramce."] },
      fr: { name: "Mont Blanc", country: "France / Italie", title: "Maquette 3D du Mont Blanc — le toit des Alpes",
        p: ["Le Mont Blanc (environ 4 808 m) est le plus haut sommet des Alpes et d'Europe occidentale, à la frontière franco-italienne au-dessus de Chamonix. Jacques Balmat et Michel-Gabriel Paccard l'ont gravi pour la première fois en 1786, date de naissance de l'alpinisme.",
          "La maquette couvre environ 7×7 km : le dôme neigeux, les aiguilles du massif et les glaciers qui descendent vers la vallée de Chamonix. Le massif est vaste et complexe, il prend toute sa valeur en 25 à 40 cm.",
          "Pour les alpinistes, les skieurs et tous ceux qui ont vu le Mont Blanc depuis l'Aiguille du Midi — avec le nom de la voie ou l'altitude gravés."] },
      es: { name: "Mont Blanc", country: "Francia / Italia", title: "Maqueta 3D del Mont Blanc — la cumbre más alta de los Alpes",
        p: ["El Mont Blanc (unos 4808 m) es la montaña más alta de los Alpes y de Europa occidental, en la frontera entre Francia e Italia, sobre Chamonix. Jacques Balmat y Michel-Gabriel Paccard hicieron la primera ascensión en 1786, origen del alpinismo moderno.",
          "La maqueta abarca unos 7×7 km: la cúpula nevada, las agujas afiladas del macizo y los glaciares que bajan al valle de Chamonix. El macizo es grande y complejo, así que luce mejor en 25–40 cm.",
          "Para alpinistas, esquiadores y quien haya visto el Mont Blanc desde la Aiguille du Midi — con el nombre de la ruta o la altitud grabados."] },
    },
  },
  {
    slug: "eiger", presetId: "eiger", elev: 3967, areaKm: 5, lat: 46.5775, lon: 8.00528, photo: "/mountains/presets/eiger.jpg",
    t: {
      uk: { name: "Айгер", country: "Швейцарія", title: "3D-модель Айгера — знаменита Північна стіна",
        p: ["Айгер (3967 м) — вершина Бернських Альп над Гріндельвальдом, поруч із Менхом і Юнгфрау. Його Північна стіна заввишки майже 1800 м — одна з найвідоміших і найнебезпечніших стін Альп; вперше її пройшли в 1938 році.",
          "Для Швейцарії ми беремо лідарні висоти 2 м, тож на моделі близько 5×5 км добре видно саму стіну, гребені Міттеллегі й західний схил, яким спускаються альпіністи. Скельні боки моделі роблять стіну ще драматичнішою.",
          "Подарунок скелелазу чи альпіністу — з фігуркою на найкрутішій стіні, яку генератор знаходить сам. Для фанатів Альп — разом з моделлю Матергорна на одній полиці."] },
      en: { name: "Eiger", country: "Switzerland", title: "3D model of the Eiger — the famous North Face",
        p: ["The Eiger (3,967 m) stands in the Bernese Alps above Grindelwald, next to the Mönch and the Jungfrau. Its North Face, nearly 1,800 m high, is one of the most famous and dangerous walls of the Alps; it was first climbed in 1938.",
          "For Switzerland we use 2 m lidar elevations, so a model of about 5×5 km clearly shows the face itself, the Mittellegi ridge and the west flank climbers descend by. Rocky sides make the wall even more dramatic.",
          "A gift for a rock climber or alpinist — with a figure on the steepest face, which the generator finds automatically. For Alps fans, it pairs well with a Matterhorn model."] },
      de: { name: "Eiger", country: "Schweiz", title: "3D-Modell des Eigers — die berühmte Nordwand",
        p: ["Der Eiger (3967 m) steht in den Berner Alpen über Grindelwald, neben Mönch und Jungfrau. Seine fast 1800 m hohe Nordwand gehört zu den berühmtesten und gefährlichsten Wänden der Alpen; 1938 wurde sie erstmals durchstiegen.",
          "Mit Lidar-Höhen von swissALTI3D (2 m) zeigt ein Modell von etwa 5×5 km die Wand selbst, den Mittellegigrat und die Westflanke, über die abgestiegen wird. Felsige Seitenwände steigern die Dramatik.",
          "Ein Geschenk für Kletterer und Alpinisten — mit Figur an der steilsten Stelle, die der Generator selbst findet. Für Alpenfans passend zum Matterhorn-Modell."] },
      pl: { name: "Eiger", country: "Szwajcaria", title: "Model 3D Eigeru — słynna Północna Ściana",
        p: ["Eiger (3967 m) wznosi się w Alpach Berneńskich nad Grindelwaldem, obok Mönchu i Jungfrau. Jego Północna Ściana wysokości niemal 1800 m to jedna z najsłynniejszych i najgroźniejszych ścian Alp; pierwsze przejście — 1938 rok.",
          "Dla Szwajcarii używamy wysokości z lidaru 2 m, więc model obszaru ok. 5×5 km wyraźnie pokazuje ścianę, grań Mittellegi i zachodnie zbocze, którym się schodzi. Skalne boki modelu dodają ścianie dramatyzmu.",
          "Prezent dla wspinacza lub alpinisty — z figurką na najbardziej stromej ścianie, którą generator znajduje sam. Dla fanów Alp — w parze z modelem Matterhornu."] },
      fr: { name: "Eiger", country: "Suisse", title: "Maquette 3D de l'Eiger — la célèbre face nord",
        p: ["L'Eiger (3 967 m) domine Grindelwald dans les Alpes bernoises, à côté du Mönch et de la Jungfrau. Sa face nord, haute de près de 1 800 m, est l'une des parois les plus célèbres et dangereuses des Alpes ; elle a été gravie pour la première fois en 1938.",
          "Grâce aux altitudes lidar de 2 m, une maquette d'environ 5×5 km montre nettement la paroi, l'arête du Mittellegi et le versant ouest de descente. Les flancs rocheux rendent la paroi encore plus spectaculaire.",
          "Un cadeau pour un grimpeur ou un alpiniste — avec une figurine sur la face la plus raide, trouvée automatiquement. Pour les amoureux des Alpes, à associer au Cervin."] },
      es: { name: "Eiger", country: "Suiza", title: "Maqueta 3D del Eiger — la famosa cara norte",
        p: ["El Eiger (3967 m) se alza en los Alpes berneses sobre Grindelwald, junto al Mönch y la Jungfrau. Su cara norte, de casi 1800 m, es una de las paredes más famosas y peligrosas de los Alpes; se escaló por primera vez en 1938.",
          "Con alturas lidar de 2 m, una maqueta de unos 5×5 km muestra claramente la pared, la arista Mittellegi y la vertiente oeste de descenso. Los laterales de roca hacen la pared aún más dramática.",
          "Un regalo para un escalador o alpinista — con una figura en la cara más empinada, que el generador encuentra solo. Para fans de los Alpes, junto a una maqueta del Cervino."] },
    },
  },
  {
    slug: "tre-cime", presetId: "tre_cime", elev: 2999, areaKm: 3, lat: 46.61889, lon: 12.30306, photo: "/mountains/presets/tre_cime.jpg",
    t: {
      uk: { name: "Тре-Чіме-ді-Лаваредо", country: "Італія, Доломіти", title: "3D-модель Тре-Чіме-ді-Лаваредо — три вежі Доломітових Альп",
        p: ["Тре-Чіме-ді-Лаваредо — три скельні вежі в Доломітових Альпах на півночі Італії, найвища з яких, Чіма-Гранде, сягає 2999 м. Доломіти внесено до Світової спадщини ЮНЕСКО, а кільце навколо трьох веж — один з найпопулярніших маршрутів Європи.",
          "Модель охоплює ділянку близько 3×3 км — достатньо, щоб усі три вежі стояли окремо, з прямовисними північними стінами й осипами біля підніжжя. Мала площа дає дуже виразний рельєф навіть у розмірі 15–20 см.",
          "Подарунок для тих, хто обходив Тре-Чіме від притулку Ауронцо, або для скелелазів — на стінах веж проходять класичні маршрути. Фігурка скелелаза сама знаходить найкрутішу стіну."] },
      en: { name: "Tre Cime di Lavaredo", country: "Italy, Dolomites", title: "3D model of the Tre Cime di Lavaredo — the three towers of the Dolomites",
        p: ["The Tre Cime di Lavaredo are three rock towers in the Dolomites of northern Italy; the highest, Cima Grande, reaches 2,999 m. The Dolomites are a UNESCO World Heritage Site, and the loop around the three towers is one of Europe's most popular hikes.",
          "The model covers about 3×3 km — enough for all three towers to stand apart, with their sheer north faces and scree at the base. The small area gives very expressive relief even at 15–20 cm.",
          "A gift for anyone who has walked around the Tre Cime from Rifugio Auronzo, or for climbers — classic routes run up the faces. The climber figure finds the steepest wall on its own."] },
      de: { name: "Drei Zinnen", country: "Italien, Dolomiten", title: "3D-Modell der Drei Zinnen — die drei Türme der Dolomiten",
        p: ["Die Drei Zinnen (Tre Cime di Lavaredo) sind drei Felstürme in den Dolomiten Norditaliens; die Große Zinne erreicht 2999 m. Die Dolomiten sind UNESCO-Weltnaturerbe, die Runde um die Zinnen gehört zu den beliebtesten Wanderungen Europas.",
          "Das Modell zeigt etwa 3×3 km — genug, damit alle drei Türme einzeln stehen, mit senkrechten Nordwänden und Schuttkegeln am Fuß. Der kleine Ausschnitt ergibt schon bei 15–20 cm ein sehr plastisches Relief.",
          "Ein Geschenk für alle, die die Zinnen von der Auronzohütte aus umrundet haben, oder für Kletterer — die Figur sucht sich die steilste Wand selbst."] },
      pl: { name: "Tre Cime di Lavaredo", country: "Włochy, Dolomity", title: "Model 3D Tre Cime di Lavaredo — trzy wieże Dolomitów",
        p: ["Tre Cime di Lavaredo to trzy skalne wieże w Dolomitach w północnych Włoszech; najwyższa, Cima Grande, ma 2999 m. Dolomity są na liście UNESCO, a pętla wokół trzech wież to jeden z najpopularniejszych szlaków Europy.",
          "Model obejmuje około 3×3 km — wystarczająco, by wszystkie trzy wieże stały osobno, z pionowymi północnymi ścianami i piargami u podnóża. Mały obszar daje bardzo wyrazisty relief już przy 15–20 cm.",
          "Prezent dla tych, którzy obeszli Tre Cime od schroniska Auronzo, albo dla wspinaczy — figurka sama znajduje najbardziej stromą ścianę."] },
      fr: { name: "Tre Cime di Lavaredo", country: "Italie, Dolomites", title: "Maquette 3D des Tre Cime di Lavaredo — les trois tours des Dolomites",
        p: ["Les Tre Cime di Lavaredo sont trois tours rocheuses des Dolomites, dans le nord de l'Italie ; la plus haute, la Cima Grande, atteint 2 999 m. Les Dolomites sont inscrites au patrimoine mondial de l'UNESCO, et le tour des trois tours est l'une des randonnées les plus populaires d'Europe.",
          "La maquette couvre environ 3×3 km — assez pour que les trois tours se détachent, avec leurs faces nord verticales et les éboulis à leur pied. La petite zone donne un relief très expressif dès 15–20 cm.",
          "Un cadeau pour ceux qui ont fait le tour depuis le refuge Auronzo, ou pour les grimpeurs — la figurine trouve seule la paroi la plus raide."] },
      es: { name: "Tre Cime di Lavaredo", country: "Italia, Dolomitas", title: "Maqueta 3D de las Tre Cime di Lavaredo — las tres torres de los Dolomitas",
        p: ["Las Tre Cime di Lavaredo son tres torres de roca en los Dolomitas del norte de Italia; la más alta, la Cima Grande, alcanza 2999 m. Los Dolomitas son Patrimonio de la Humanidad de la UNESCO y la vuelta a las tres torres es una de las rutas más populares de Europa.",
          "La maqueta abarca unos 3×3 km — suficiente para que las tres torres se separen, con sus caras norte verticales y los canchales al pie. El área pequeña da un relieve muy expresivo ya en 15–20 cm.",
          "Un regalo para quien ha rodeado las Tre Cime desde el refugio Auronzo, o para escaladores — la figura encuentra sola la pared más empinada."] },
    },
  },
  {
    slug: "rysy", presetId: "rysy", elev: 2503, areaKm: 4, lat: 49.17944, lon: 20.08833, photo: "/mountains/presets/rysy.jpg",
    t: {
      uk: { name: "Риси", country: "Польща / Словаччина, Татри", title: "3D-модель гори Риси — найвища вершина Польщі в Татрах",
        p: ["Риси — вершина Високих Татр на кордоні Польщі та Словаччини. Словацька вершина має 2503 м, польська — 2499 м, і це найвища точка Польщі. Маршрут від озера Морське Око — один з найвідоміших у Татрах.",
          "Модель охоплює близько 4×4 км: гребінь Рисів, озера Морське Око і Чорний Став під стінами, круті кулуари й сусідні вершини. Татри компактні й скелясті, тому рельєф виходить дуже виразним.",
          "Подарунок для тих, хто піднімався на Риси з польського чи словацького боку, або для любителів Закопаного. Можна вигравіювати дату сходження."] },
      en: { name: "Rysy", country: "Poland / Slovakia, Tatras", title: "3D model of Rysy — Poland's highest peak in the Tatras",
        p: ["Rysy is a peak of the High Tatras on the Polish–Slovak border. The Slovak summit is 2,503 m and the Polish one 2,499 m — the highest point of Poland. The trail from the Morskie Oko lake is one of the best known in the Tatras.",
          "The model covers about 4×4 km: the Rysy ridge, the Morskie Oko and Czarny Staw lakes below the walls, steep couloirs and neighbouring peaks. The Tatras are compact and rocky, so the relief comes out very expressive.",
          "A gift for anyone who has climbed Rysy from the Polish or Slovak side, or for Zakopane lovers. Engrave the date of the climb."] },
      de: { name: "Meeraugspitze (Rysy)", country: "Polen / Slowakei, Tatra", title: "3D-Modell der Meeraugspitze (Rysy) — Polens höchster Gipfel",
        p: ["Die Meeraugspitze (polnisch Rysy) liegt in der Hohen Tatra an der polnisch-slowakischen Grenze. Der slowakische Gipfel misst 2503 m, der polnische 2499 m — der höchste Punkt Polens. Der Weg vom See Morskie Oko ist einer der bekanntesten der Tatra.",
          "Das Modell zeigt etwa 4×4 km: den Grat, die Seen Morskie Oko und Czarny Staw unter den Wänden, steile Rinnen und Nachbargipfel. Die Tatra ist kompakt und felsig — das Relief wirkt sehr plastisch.",
          "Ein Geschenk für alle, die von polnischer oder slowakischer Seite oben waren — mit dem Datum der Besteigung."] },
      pl: { name: "Rysy", country: "Polska / Słowacja, Tatry", title: "Model 3D Rysów — najwyższy szczyt Polski",
        p: ["Rysy to szczyt Tatr Wysokich na granicy Polski i Słowacji. Wierzchołek słowacki ma 2503 m, polski — 2499 m i jest najwyższym punktem Polski. Szlak znad Morskiego Oka to jedna z najbardziej znanych tras w Tatrach.",
          "Model obejmuje około 4×4 km: grań Rysów, Morskie Oko i Czarny Staw pod ścianami, strome żleby i sąsiednie szczyty. Tatry są zwarte i skaliste, więc relief wychodzi bardzo wyrazisty.",
          "Prezent dla każdego, kto wszedł na Rysy od polskiej lub słowackiej strony, albo dla miłośników Zakopanego — z datą wejścia na ramce."] },
      fr: { name: "Rysy", country: "Pologne / Slovaquie, Tatras", title: "Maquette 3D du Rysy — le plus haut sommet de Pologne",
        p: ["Le Rysy est un sommet des Hautes Tatras, à la frontière polono-slovaque. Le sommet slovaque culmine à 2 503 m et le sommet polonais à 2 499 m — le point le plus haut de Pologne. Le sentier depuis le lac Morskie Oko est l'un des plus connus des Tatras.",
          "La maquette couvre environ 4×4 km : la crête du Rysy, les lacs Morskie Oko et Czarny Staw sous les parois, les couloirs raides et les sommets voisins. Les Tatras sont compactes et rocheuses : le relief est très expressif.",
          "Un cadeau pour ceux qui ont gravi le Rysy côté polonais ou slovaque — avec la date de l'ascension gravée."] },
      es: { name: "Rysy", country: "Polonia / Eslovaquia, Tatras", title: "Maqueta 3D del Rysy — el pico más alto de Polonia",
        p: ["El Rysy es un pico de los Altos Tatras en la frontera entre Polonia y Eslovaquia. La cima eslovaca mide 2503 m y la polaca 2499 m, el punto más alto de Polonia. La ruta desde el lago Morskie Oko es una de las más conocidas de los Tatras.",
          "La maqueta abarca unos 4×4 km: la cresta del Rysy, los lagos Morskie Oko y Czarny Staw bajo las paredes, corredores empinados y picos vecinos. Los Tatras son compactos y rocosos, así que el relieve sale muy expresivo.",
          "Un regalo para quien ha subido al Rysy por el lado polaco o eslovaco — con la fecha de la ascensión grabada."] },
    },
  },
  {
    slug: "olympus", presetId: "olympus", elev: 2917, areaKm: 8, lat: 40.08556, lon: 22.35861, photo: "/mountains/presets/olympus.jpg",
    t: {
      uk: { name: "Олімп", country: "Греція", title: "3D-модель гори Олімп — дім богів Стародавньої Греції",
        p: ["Олімп — найвища гора Греції, її головна вершина Мітікас сягає близько 2917 м. У давньогрецькій міфології тут жили боги на чолі із Зевсом, а сьогодні масив — національний парк, куди піднімаються з містечка Літохоро.",
          "Модель охоплює близько 8×8 км: кілька вершин масиву — Мітікас, Стефані, Сколіо, — глибокі ущелини й плато Муз. Велика ділянка добре передає, як масив здіймається майже просто від моря.",
          "Подарунок для тих, хто відпочивав у Греції чи ходив на Олімп, або для шанувальників античності. На ободку можна написати «Дім богів» чи дату подорожі."] },
      en: { name: "Mount Olympus", country: "Greece", title: "3D model of Mount Olympus — home of the ancient Greek gods",
        p: ["Mount Olympus is the highest mountain in Greece; its main summit, Mytikas, reaches about 2,917 m. In Greek mythology it was the home of the gods led by Zeus, and today the massif is a national park climbed from the town of Litochoro.",
          "The model covers about 8×8 km: several summits of the massif — Mytikas, Stefani, Skolio — deep gorges and the Plateau of the Muses. The large area conveys how the massif rises almost straight from the sea.",
          "A gift for anyone who has holidayed in Greece or hiked Olympus, or for lovers of antiquity. The frame can say “Home of the gods” or carry the trip date."] },
      de: { name: "Olymp", country: "Griechenland", title: "3D-Modell des Olymp — Sitz der griechischen Götter",
        p: ["Der Olymp ist der höchste Berg Griechenlands; sein Hauptgipfel Mytikas erreicht etwa 2917 m. In der Mythologie wohnten hier die Götter um Zeus, heute ist das Massiv ein Nationalpark mit Aufstieg ab Litochoro.",
          "Das Modell zeigt etwa 8×8 km: mehrere Gipfel — Mytikas, Stefani, Skolio —, tiefe Schluchten und das Plateau der Musen. Der große Ausschnitt zeigt, wie das Massiv fast direkt aus dem Meer aufsteigt.",
          "Ein Geschenk für Griechenland-Urlauber, Olymp-Wanderer oder Antike-Fans — mit „Sitz der Götter“ oder Reisedatum auf dem Rahmen."] },
      pl: { name: "Olimp", country: "Grecja", title: "Model 3D Olimpu — siedziba greckich bogów",
        p: ["Olimp to najwyższa góra Grecji; jego główny szczyt, Mitikas, ma około 2917 m. W mitologii mieszkali tu bogowie z Zeusem na czele, a dziś masyw jest parkiem narodowym, na który wchodzi się z Litochoro.",
          "Model obejmuje około 8×8 km: kilka szczytów masywu — Mitikas, Stefani, Skolio — głębokie wąwozy i Płaskowyż Muz. Duży obszar dobrze pokazuje, jak masyw wyrasta niemal prosto z morza.",
          "Prezent dla tych, którzy wypoczywali w Grecji lub weszli na Olimp, albo dla miłośników antyku — z napisem „Dom bogów” lub datą podróży."] },
      fr: { name: "Mont Olympe", country: "Grèce", title: "Maquette 3D du mont Olympe — la demeure des dieux grecs",
        p: ["Le mont Olympe est la plus haute montagne de Grèce ; son sommet principal, le Mytikas, culmine à environ 2 917 m. Dans la mythologie, les dieux menés par Zeus y résidaient ; le massif est aujourd'hui un parc national que l'on gravit depuis Litochoro.",
          "La maquette couvre environ 8×8 km : plusieurs sommets — Mytikas, Stefani, Skolio —, des gorges profondes et le plateau des Muses. La grande zone montre comment le massif s'élève presque directement depuis la mer.",
          "Un cadeau pour ceux qui ont voyagé en Grèce ou gravi l'Olympe, ou pour les passionnés d'Antiquité — avec « Demeure des dieux » ou la date du voyage."] },
      es: { name: "Monte Olimpo", country: "Grecia", title: "Maqueta 3D del monte Olimpo — el hogar de los dioses griegos",
        p: ["El monte Olimpo es la montaña más alta de Grecia; su cumbre principal, el Mytikas, alcanza unos 2917 m. En la mitología vivían aquí los dioses encabezados por Zeus, y hoy el macizo es un parque nacional que se sube desde Litochoro.",
          "La maqueta abarca unos 8×8 km: varias cumbres — Mytikas, Stefani, Skolio —, gargantas profundas y la Meseta de las Musas. La gran área muestra cómo el macizo se eleva casi directamente desde el mar.",
          "Un regalo para quien ha viajado a Grecia o subido al Olimpo, o para amantes de la Antigüedad — con «Hogar de los dioses» o la fecha del viaje."] },
    },
  },
  {
    slug: "everest", presetId: "everest", elev: 8849, areaKm: 12, lat: 27.98806, lon: 86.92528, photo: "/mountains/presets/everest.jpg",
    t: {
      uk: { name: "Еверест", country: "Непал / Китай", title: "3D-модель Евересту — найвища гора Землі",
        p: ["Еверест (Джомолунгма, 8849 м) — найвища вершина Землі, у Гімалаях на кордоні Непалу й Китаю. Перше підтверджене сходження здійснили Едмунд Гілларі й Тенцинг Норгей у 1953 році.",
          "Модель охоплює близько 12×12 км: піраміду Евересту, сусідні Лхоцзе й Нупцзе, льодопад Кхумбу і гребені, якими проходять класичні маршрути з Непалу й Тибету. Перепад висот тут величезний, тож модель виходить висока навіть без підсилення вертикалі.",
          "Подарунок для тих, хто мріє про Гімалаї чи ходив треком до базового табору, — або символ великої мети для колеги чи друга. На ободку можна вигравіювати «8849» чи особисту мету."] },
      en: { name: "Mount Everest", country: "Nepal / China", title: "3D model of Mount Everest — the highest mountain on Earth",
        p: ["Mount Everest (Chomolungma, 8,849 m) is the highest summit on Earth, in the Himalayas on the border of Nepal and China. Edmund Hillary and Tenzing Norgay made the first confirmed ascent in 1953.",
          "The model covers about 12×12 km: the Everest pyramid, neighbouring Lhotse and Nuptse, the Khumbu Icefall and the ridges of the classic routes from Nepal and Tibet. The height difference is enormous, so the model comes out tall even without vertical exaggeration.",
          "A gift for anyone who dreams of the Himalayas or has trekked to Base Camp — or a symbol of a big goal for a colleague or friend. Engrave “8849” or a personal goal on the frame."] },
      de: { name: "Mount Everest", country: "Nepal / China", title: "3D-Modell des Mount Everest — der höchste Berg der Erde",
        p: ["Der Mount Everest (Chomolungma, 8849 m) ist der höchste Gipfel der Erde, im Himalaya an der Grenze zwischen Nepal und China. Edmund Hillary und Tenzing Norgay gelang 1953 die erste bestätigte Besteigung.",
          "Das Modell zeigt etwa 12×12 km: die Everest-Pyramide, Lhotse und Nuptse, den Khumbu-Eisbruch und die Grate der klassischen Routen aus Nepal und Tibet. Der Höhenunterschied ist enorm — das Modell wird auch ohne Überhöhung hoch.",
          "Ein Geschenk für Himalaya-Träumer und Basislager-Trekker — oder als Symbol für ein großes Ziel. Gravur: „8849“ oder ein persönliches Ziel."] },
      pl: { name: "Mount Everest", country: "Nepal / Chiny", title: "Model 3D Mount Everestu — najwyższa góra Ziemi",
        p: ["Mount Everest (Czomolungma, 8849 m) to najwyższy szczyt Ziemi, w Himalajach na granicy Nepalu i Chin. Pierwszego potwierdzonego wejścia dokonali Edmund Hillary i Tenzing Norgay w 1953 roku.",
          "Model obejmuje około 12×12 km: piramidę Everestu, sąsiednie Lhotse i Nuptse, lodospad Khumbu oraz granie klasycznych dróg z Nepalu i Tybetu. Różnica wysokości jest ogromna, więc model wychodzi wysoki nawet bez przewyższenia.",
          "Prezent dla marzących o Himalajach i tych, którzy szli do bazy — albo symbol wielkiego celu. Na ramce: „8849” lub osobisty cel."] },
      fr: { name: "Mont Everest", country: "Népal / Chine", title: "Maquette 3D de l'Everest — le plus haut sommet de la Terre",
        p: ["L'Everest (Chomolungma, 8 849 m) est le plus haut sommet de la Terre, dans l'Himalaya, à la frontière du Népal et de la Chine. Edmund Hillary et Tenzing Norgay en ont réussi la première ascension confirmée en 1953.",
          "La maquette couvre environ 12×12 km : la pyramide de l'Everest, le Lhotse et le Nuptse voisins, la cascade de glace du Khumbu et les arêtes des voies classiques depuis le Népal et le Tibet. Le dénivelé est énorme : la maquette est haute même sans exagération verticale.",
          "Un cadeau pour ceux qui rêvent de l'Himalaya ou ont fait le trek du camp de base — ou le symbole d'un grand objectif. Gravure : « 8849 » ou un objectif personnel."] },
      es: { name: "Monte Everest", country: "Nepal / China", title: "Maqueta 3D del Everest — la montaña más alta de la Tierra",
        p: ["El Everest (Chomolungma, 8849 m) es la cumbre más alta de la Tierra, en el Himalaya, en la frontera entre Nepal y China. Edmund Hillary y Tenzing Norgay hicieron la primera ascensión confirmada en 1953.",
          "La maqueta abarca unos 12×12 km: la pirámide del Everest, el Lhotse y el Nuptse vecinos, la cascada de hielo del Khumbu y las aristas de las rutas clásicas desde Nepal y el Tíbet. El desnivel es enorme, así que la maqueta sale alta incluso sin exageración vertical.",
          "Un regalo para quien sueña con el Himalaya o ha hecho el trekking al campo base — o el símbolo de una gran meta. Grabado: «8849» o una meta personal."] },
    },
  },
  {
    slug: "k2", presetId: "k2", elev: 8611, areaKm: 10, lat: 35.88139, lon: 76.51333, photo: "/mountains/presets/k2.jpg",
    t: {
      uk: { name: "K2 (Чогорі)", country: "Пакистан / Китай", title: "3D-модель K2 — друга за висотою гора світу",
        p: ["K2, або Чогорі (8611 м), — друга за висотою вершина Землі, у Каракорумі на кордоні Пакистану й Китаю. Її називають «дикою горою» через складність і небезпеку; вперше на неї піднялася італійська експедиція в 1954 році.",
          "Модель охоплює близько 10×10 км: майже симетричну піраміду K2, льодовик Балторо біля підніжжя й гострі сусідні хребти. Стіни тут настільки круті, що скельні боки моделі підкреслюють характер гори.",
          "Подарунок альпіністу чи любителю експедиційних історій. Разом з моделлю Евересту — пара «двох найвищих» на одній полиці."] },
      en: { name: "K2 (Chhogori)", country: "Pakistan / China", title: "3D model of K2 — the world's second-highest mountain",
        p: ["K2, or Chhogori (8,611 m), is the second-highest summit on Earth, in the Karakoram on the border of Pakistan and China. It is called the “savage mountain” for its difficulty and danger; an Italian expedition made the first ascent in 1954.",
          "The model covers about 10×10 km: K2's near-symmetrical pyramid, the Baltoro glacier region below and the sharp neighbouring ridges. The faces are so steep that rocky sides emphasise the mountain's character.",
          "A gift for a mountaineer or a lover of expedition stories. Together with an Everest model it makes a pair of the two highest peaks on one shelf."] },
      de: { name: "K2 (Chogori)", country: "Pakistan / China", title: "3D-Modell des K2 — der zweithöchste Berg der Welt",
        p: ["Der K2 oder Chogori (8611 m) ist der zweithöchste Gipfel der Erde, im Karakorum an der Grenze zwischen Pakistan und China. Wegen seiner Schwierigkeit heißt er „wilder Berg“; eine italienische Expedition bestieg ihn 1954 erstmals.",
          "Das Modell zeigt etwa 10×10 km: die fast symmetrische Pyramide, die Gletscherwelt am Fuß und die scharfen Nachbargrate. Die Wände sind so steil, dass felsige Seitenwände den Charakter des Bergs betonen.",
          "Ein Geschenk für Bergsteiger und Fans von Expeditionsgeschichten — zusammen mit dem Everest ein Paar der zwei Höchsten."] },
      pl: { name: "K2 (Czogori)", country: "Pakistan / Chiny", title: "Model 3D K2 — druga najwyższa góra świata",
        p: ["K2, czyli Czogori (8611 m), to drugi co do wysokości szczyt Ziemi, w Karakorum na granicy Pakistanu i Chin. Nazywany „górą dziką” z powodu trudności; pierwszego wejścia dokonała wyprawa włoska w 1954 roku. Pierwsze zimowe wejście udało się dopiero w 2021 roku.",
          "Model obejmuje około 10×10 km: niemal symetryczną piramidę K2, lodowce u podnóża i ostre sąsiednie granie. Ściany są tak strome, że skalne boki modelu podkreślają charakter góry.",
          "Prezent dla himalaisty lub miłośnika historii wypraw — razem z modelem Everestu para dwóch najwyższych szczytów."] },
      fr: { name: "K2 (Chogori)", country: "Pakistan / Chine", title: "Maquette 3D du K2 — deuxième plus haut sommet du monde",
        p: ["Le K2, ou Chogori (8 611 m), est le deuxième plus haut sommet de la Terre, dans le Karakoram, à la frontière du Pakistan et de la Chine. Surnommé la « montagne sauvage », il a été gravi pour la première fois par une expédition italienne en 1954.",
          "La maquette couvre environ 10×10 km : la pyramide presque symétrique du K2, les glaciers à son pied et les arêtes voisines acérées. Les faces sont si raides que les flancs rocheux soulignent le caractère de la montagne.",
          "Un cadeau pour un alpiniste ou un passionné de récits d'expédition — avec l'Everest, la paire des deux plus hauts sommets."] },
      es: { name: "K2 (Chogori)", country: "Pakistán / China", title: "Maqueta 3D del K2 — la segunda montaña más alta del mundo",
        p: ["El K2 o Chogori (8611 m) es la segunda cumbre más alta de la Tierra, en el Karakórum, en la frontera entre Pakistán y China. Lo llaman la «montaña salvaje» por su dificultad; una expedición italiana hizo la primera ascensión en 1954.",
          "La maqueta abarca unos 10×10 km: la pirámide casi simétrica del K2, los glaciares a su pie y las aristas vecinas afiladas. Las paredes son tan empinadas que los laterales de roca subrayan su carácter.",
          "Un regalo para un alpinista o amante de las historias de expediciones — junto al Everest, la pareja de los dos más altos."] },
    },
  },
  {
    slug: "fuji", presetId: "fuji", elev: 3776, areaKm: 20, lat: 35.36083, lon: 138.7275, photo: "/mountains/presets/fuji.jpg",
    t: {
      uk: { name: "Фудзі", country: "Японія", title: "3D-модель Фудзі — священний вулкан Японії",
        p: ["Фудзі (3776 м) — найвища гора Японії, стратовулкан на острові Хонсю неподалік від Токіо. Її симетричний конус став символом країни, а у 2013 році гору внесли до Світової спадщини ЮНЕСКО як обʼєкт культури.",
          "Модель охоплює велику ділянку — близько 20×20 км, — щоб помістився весь конус з кратером на вершині й пологими підніжжями. Саме так видно ідеальну форму вулкана, якою його знають з гравюр Хокусая.",
          "Подарунок для тих, хто був у Японії або мріє поїхати, для шанувальників японської культури й аніме. Добре виглядає на робочому столі в розмірі 15–20 см."] },
      en: { name: "Mount Fuji", country: "Japan", title: "3D model of Mount Fuji — Japan's sacred volcano",
        p: ["Mount Fuji (3,776 m) is the highest mountain in Japan, a stratovolcano on Honshu not far from Tokyo. Its symmetrical cone has become a symbol of the country, and in 2013 it was inscribed as a UNESCO World Heritage cultural site.",
          "The model covers a large area — about 20×20 km — so the whole cone fits, with the crater at the top and the gentle lower slopes. This is how you see the perfect volcano shape known from Hokusai's prints.",
          "A gift for anyone who has been to Japan or dreams of going, and for fans of Japanese culture and anime. It looks great on a desk at 15–20 cm."] },
      de: { name: "Fuji", country: "Japan", title: "3D-Modell des Fuji — Japans heiliger Vulkan",
        p: ["Der Fuji (3776 m) ist der höchste Berg Japans, ein Schichtvulkan auf Honshu unweit von Tokio. Sein symmetrischer Kegel ist Symbol des Landes und seit 2013 UNESCO-Weltkulturerbe.",
          "Das Modell umfasst einen großen Ausschnitt von etwa 20×20 km, damit der ganze Kegel mit Gipfelkrater und sanften Unterhängen passt — die perfekte Vulkanform, bekannt aus Hokusais Holzschnitten.",
          "Ein Geschenk für Japan-Reisende und Fans japanischer Kultur und Anime. Auf dem Schreibtisch am schönsten in 15–20 cm."] },
      pl: { name: "Fudżi", country: "Japonia", title: "Model 3D Fudżi — święty wulkan Japonii",
        p: ["Fudżi (3776 m) to najwyższa góra Japonii, stratowulkan na wyspie Honsiu niedaleko Tokio. Jej symetryczny stożek jest symbolem kraju, a w 2013 roku góra trafiła na listę światowego dziedzictwa kulturowego UNESCO.",
          "Model obejmuje duży obszar — około 20×20 km — tak by zmieścił się cały stożek z kraterem i łagodnymi podnóżami. Widać idealny kształt wulkanu znany z drzeworytów Hokusaia.",
          "Prezent dla tych, którzy byli w Japonii lub marzą o podróży, dla fanów japońskiej kultury i anime. Najlepiej wygląda na biurku w rozmiarze 15–20 cm."] },
      fr: { name: "Mont Fuji", country: "Japon", title: "Maquette 3D du mont Fuji — le volcan sacré du Japon",
        p: ["Le mont Fuji (3 776 m) est la plus haute montagne du Japon, un stratovolcan sur l'île de Honshu, non loin de Tokyo. Son cône symétrique est devenu le symbole du pays et il est inscrit au patrimoine mondial culturel de l'UNESCO depuis 2013.",
          "La maquette couvre une grande zone — environ 20×20 km — pour contenir tout le cône, avec le cratère au sommet et les pentes douces à la base : la forme parfaite connue grâce aux estampes d'Hokusai.",
          "Un cadeau pour ceux qui sont allés au Japon ou en rêvent, et pour les fans de culture japonaise et d'anime. Parfait sur un bureau en 15–20 cm."] },
      es: { name: "Monte Fuji", country: "Japón", title: "Maqueta 3D del monte Fuji — el volcán sagrado de Japón",
        p: ["El monte Fuji (3776 m) es la montaña más alta de Japón, un estratovolcán en la isla de Honshu, cerca de Tokio. Su cono simétrico es símbolo del país y desde 2013 es Patrimonio cultural de la Humanidad de la UNESCO.",
          "La maqueta abarca una gran área — unos 20×20 km — para que quepa todo el cono con el cráter en la cima y las suaves laderas bajas: la forma perfecta conocida por los grabados de Hokusai.",
          "Un regalo para quien ha estado en Japón o sueña con ir, y para fans de la cultura japonesa y el anime. Queda genial en el escritorio en 15–20 cm."] },
    },
  },
  {
    slug: "kilimanjaro", presetId: "kilimanjaro", elev: 5895, areaKm: 30, lat: -3.06583, lon: 37.35861, photo: "/mountains/presets/kilimanjaro.jpg",
    t: {
      uk: { name: "Кіліманджаро", country: "Танзанія", title: "3D-модель Кіліманджаро — дах Африки",
        p: ["Кіліманджаро — найвища гора Африки й найвища окремо розташована гора світу, у Танзанії. Її вершина Ухуру на кратері вулкана Кібо сягає 5895 м, і на неї піднімаються без спеціального альпіністського спорядження.",
          "Щоб помістився весь масив, модель охоплює найбільшу серед наших пресетів ділянку — близько 30×30 км: вулкан Кібо з кратером, сусідні Мавензі й Шира та широкі схили, що підіймаються над саваною.",
          "Подарунок для тих, хто зійшов на Ухуру або планує сходження, і для всіх, хто мріє про сафарі. На ободку — «5895» чи дата сходження."] },
      en: { name: "Kilimanjaro", country: "Tanzania", title: "3D model of Kilimanjaro — the roof of Africa",
        p: ["Kilimanjaro is the highest mountain in Africa and the highest free-standing mountain in the world, in Tanzania. Its summit, Uhuru Peak on the rim of the Kibo volcano, reaches 5,895 m and is climbed without technical mountaineering gear.",
          "To fit the whole massif, the model covers the largest area among our presets — about 30×30 km: the Kibo volcano with its crater, neighbouring Mawenzi and Shira, and the broad slopes rising above the savannah.",
          "A gift for anyone who has summited Uhuru or plans to, and for everyone dreaming of a safari. Frame engraving: “5895” or the summit date."] },
      de: { name: "Kilimandscharo", country: "Tansania", title: "3D-Modell des Kilimandscharo — das Dach Afrikas",
        p: ["Der Kilimandscharo ist der höchste Berg Afrikas und der höchste freistehende Berg der Welt, in Tansania. Sein Gipfel Uhuru Peak am Kraterrand des Kibo erreicht 5895 m und ist ohne technische Ausrüstung erreichbar.",
          "Damit das ganze Massiv passt, zeigt das Modell den größten Ausschnitt unserer Presets — etwa 30×30 km: den Kibo mit Krater, Mawenzi und Shira sowie die weiten Hänge über der Savanne.",
          "Ein Geschenk für alle, die auf dem Uhuru standen oder es planen, und für Safari-Träumer — Gravur „5895“ oder Gipfeldatum."] },
      pl: { name: "Kilimandżaro", country: "Tanzania", title: "Model 3D Kilimandżaro — dach Afryki",
        p: ["Kilimandżaro to najwyższa góra Afryki i najwyższa wolnostojąca góra świata, w Tanzanii. Jej szczyt Uhuru na krawędzi krateru wulkanu Kibo ma 5895 m i zdobywa się go bez sprzętu wspinaczkowego.",
          "Aby zmieścić cały masyw, model obejmuje największy obszar spośród naszych presetów — około 30×30 km: wulkan Kibo z kraterem, sąsiednie Mawenzi i Shira oraz szerokie zbocza nad sawanną.",
          "Prezent dla tych, którzy stanęli na Uhuru lub to planują, i dla marzących o safari — na ramce „5895” lub data wejścia."] },
      fr: { name: "Kilimandjaro", country: "Tanzanie", title: "Maquette 3D du Kilimandjaro — le toit de l'Afrique",
        p: ["Le Kilimandjaro est la plus haute montagne d'Afrique et le plus haut sommet isolé du monde, en Tanzanie. Son sommet, l'Uhuru Peak sur le cratère du volcan Kibo, culmine à 5 895 m et se gravit sans matériel d'alpinisme technique.",
          "Pour contenir tout le massif, la maquette couvre la plus grande zone de nos préréglages — environ 30×30 km : le Kibo et son cratère, le Mawenzi et le Shira voisins et les larges pentes au-dessus de la savane.",
          "Un cadeau pour ceux qui ont atteint l'Uhuru ou le prévoient, et pour tous les rêveurs de safari — gravure « 5895 » ou date du sommet."] },
      es: { name: "Kilimanjaro", country: "Tanzania", title: "Maqueta 3D del Kilimanjaro — el techo de África",
        p: ["El Kilimanjaro es la montaña más alta de África y la montaña aislada más alta del mundo, en Tanzania. Su cumbre, el Uhuru Peak en el borde del volcán Kibo, alcanza 5895 m y se sube sin material técnico de escalada.",
          "Para que quepa todo el macizo, la maqueta abarca el área más grande de nuestros preajustes — unos 30×30 km: el Kibo con su cráter, el Mawenzi y el Shira vecinos y las amplias laderas sobre la sabana.",
          "Un regalo para quien ha llegado al Uhuru o lo planea, y para quien sueña con un safari — grabado «5895» o la fecha de cumbre."] },
    },
  },
  {
    slug: "aconcagua", presetId: "aconcagua", elev: 6961, areaKm: 12, lat: -32.65333, lon: -70.01083, photo: "/mountains/presets/aconcagua.jpg",
    t: {
      uk: { name: "Аконкагуа", country: "Аргентина", title: "3D-модель Аконкагуа — найвища гора обох Америк",
        p: ["Аконкагуа (6961 м) — найвища гора Америки, Південної півкулі й світу поза Азією, в Андах аргентинської провінції Мендоса. Вона входить до «Семи вершин» — найвищих гір кожного континенту.",
          "Модель охоплює близько 12×12 км: масивну вершину, льодовик Польський на східному схилі та довгі долини Орконес і Вакас, якими йдуть до базових таборів. Сухий андійський рельєф із різкими гребенями добре читається навіть без підсилення вертикалі.",
          "Подарунок для тих, хто збирає «Сім вершин», або для любителів Аргентини й Чилі. Разом з Евересту й Кіліманджаро — колекція найвищих гір континентів."] },
      en: { name: "Aconcagua", country: "Argentina", title: "3D model of Aconcagua — the highest mountain of the Americas",
        p: ["Aconcagua (6,961 m) is the highest mountain in the Americas, in the Southern Hemisphere and anywhere outside Asia, in the Andes of Argentina's Mendoza province. It is one of the Seven Summits — the highest peaks of each continent.",
          "The model covers about 12×12 km: the massive summit, the Polish Glacier on the east face and the long Horcones and Vacas valleys leading to base camps. The dry Andean relief with sharp ridges reads well even without vertical exaggeration.",
          "A gift for Seven Summits collectors or lovers of Argentina and Chile. Together with Everest and Kilimanjaro it builds a collection of continental high points."] },
      de: { name: "Aconcagua", country: "Argentinien", title: "3D-Modell des Aconcagua — der höchste Berg Amerikas",
        p: ["Der Aconcagua (6961 m) ist der höchste Berg Amerikas, der Südhalbkugel und der Welt außerhalb Asiens, in den Anden der argentinischen Provinz Mendoza. Er gehört zu den Seven Summits.",
          "Das Modell zeigt etwa 12×12 km: den massigen Gipfel, den Polnischen Gletscher an der Ostseite und die langen Täler Horcones und Vacas zu den Basislagern. Das trockene Andenrelief mit scharfen Graten wirkt auch ohne Überhöhung.",
          "Ein Geschenk für Seven-Summits-Sammler und Freunde Argentiniens und Chiles — mit Everest und Kilimandscharo eine Kontinent-Sammlung."] },
      pl: { name: "Aconcagua", country: "Argentyna", title: "Model 3D Aconcagui — najwyższa góra obu Ameryk",
        p: ["Aconcagua (6961 m) to najwyższa góra Ameryki, półkuli południowej i świata poza Azją, w Andach argentyńskiej prowincji Mendoza. Należy do Korony Ziemi. Lodowiec na wschodnim zboczu nosi nazwę Polskiego — od polskiej wyprawy, która przeszła tędy w 1934 roku.",
          "Model obejmuje około 12×12 km: masywny szczyt, Lodowiec Polski i długie doliny Horcones i Vacas prowadzące do baz. Suchy andyjski relief z ostrymi graniami dobrze widać nawet bez przewyższenia.",
          "Prezent dla zdobywców Korony Ziemi i miłośników Argentyny — razem z Everestem i Kilimandżaro kolekcja najwyższych szczytów kontynentów."] },
      fr: { name: "Aconcagua", country: "Argentine", title: "Maquette 3D de l'Aconcagua — le toit des Amériques",
        p: ["L'Aconcagua (6 961 m) est la plus haute montagne des Amériques, de l'hémisphère sud et du monde hors d'Asie, dans les Andes de la province argentine de Mendoza. Il fait partie des Sept Sommets.",
          "La maquette couvre environ 12×12 km : le sommet massif, le glacier des Polonais sur la face est et les longues vallées de Horcones et de Vacas vers les camps de base. Le relief andin sec aux arêtes vives se lit bien sans exagération.",
          "Un cadeau pour les collectionneurs des Sept Sommets ou les amoureux de l'Argentine — avec l'Everest et le Kilimandjaro, une collection des toits des continents."] },
      es: { name: "Aconcagua", country: "Argentina", title: "Maqueta 3D del Aconcagua — la montaña más alta de América",
        p: ["El Aconcagua (6961 m) es la montaña más alta de América, del hemisferio sur y del mundo fuera de Asia, en los Andes de la provincia de Mendoza, Argentina. Forma parte de las Siete Cumbres.",
          "La maqueta abarca unos 12×12 km: la cumbre maciza, el glaciar de los Polacos en la cara este y los largos valles de Horcones y Vacas hacia los campos base. El relieve andino seco, de aristas afiladas, se lee bien incluso sin exageración vertical.",
          "Un regalo para coleccionistas de las Siete Cumbres o amantes de Argentina y Chile — con el Everest y el Kilimanjaro, una colección de techos continentales."] },
    },
  },
  {
    slug: "denali", presetId: "denali", elev: 6190, areaKm: 15, lat: 63.06917, lon: -151.00694, photo: "/mountains/presets/denali.jpg",
    t: {
      uk: { name: "Деналі", country: "США, Аляска", title: "3D-модель Деналі — найвища гора Північної Америки",
        p: ["Деналі (6190 м), також відома як Мак-Кінлі, — найвища гора Північної Америки, в Аляскинському хребті в однойменному національному парку. Від підніжжя до вершини вона здіймається більш ніж на 5 км — один з найбільших перепадів серед гір на суходолі.",
          "Модель охоплює близько 15×15 км: масив Деналі з обома вершинами, льодовики Кагілтна і Малдроу, що тягнуться на десятки кілометрів, і гострі сусідні вершини. Льодовикові долини на моделі видно як широкі пологі «ріки».",
          "Подарунок для альпіністів, що збирають «Сім вершин», і для любителів дикої природи Аляски."] },
      en: { name: "Denali", country: "USA, Alaska", title: "3D model of Denali — the highest mountain in North America",
        p: ["Denali (6,190 m), also known as Mount McKinley, is the highest mountain in North America, in the Alaska Range within its namesake national park. It rises more than 5 km from its base to the summit — one of the largest base-to-peak rises of any mountain on land.",
          "The model covers about 15×15 km: the Denali massif with both summits, the Kahiltna and Muldrow glaciers stretching for tens of kilometres, and the sharp neighbouring peaks. The glacier valleys appear on the model as broad, gentle “rivers”.",
          "A gift for Seven Summits climbers and lovers of Alaska's wilderness."] },
      de: { name: "Denali", country: "USA, Alaska", title: "3D-Modell des Denali — der höchste Berg Nordamerikas",
        p: ["Der Denali (6190 m), auch Mount McKinley genannt, ist der höchste Berg Nordamerikas, in der Alaskakette im gleichnamigen Nationalpark. Vom Fuß bis zum Gipfel steigt er über 5 km an — einer der größten Höhenunterschiede an Land.",
          "Das Modell zeigt etwa 15×15 km: das Massiv mit beiden Gipfeln, die Kahiltna- und Muldrow-Gletscher über Dutzende Kilometer und scharfe Nachbargipfel. Die Gletschertäler erscheinen als breite, sanfte „Flüsse“.",
          "Ein Geschenk für Seven-Summits-Bergsteiger und Liebhaber der Wildnis Alaskas."] },
      pl: { name: "Denali", country: "USA, Alaska", title: "Model 3D Denali — najwyższa góra Ameryki Północnej",
        p: ["Denali (6190 m), znane też jako Mount McKinley, to najwyższa góra Ameryki Północnej, w Górach Alaska w parku narodowym o tej samej nazwie. Od podnóża do szczytu wznosi się o ponad 5 km — to jedno z największych przewyższeń na lądzie.",
          "Model obejmuje około 15×15 km: masyw Denali z oboma wierzchołkami, lodowce Kahiltna i Muldrow ciągnące się dziesiątki kilometrów i ostre sąsiednie szczyty. Doliny lodowcowe widać jako szerokie, łagodne „rzeki”.",
          "Prezent dla zdobywców Korony Ziemi i miłośników dzikiej Alaski."] },
      fr: { name: "Denali", country: "États-Unis, Alaska", title: "Maquette 3D du Denali — le plus haut sommet d'Amérique du Nord",
        p: ["Le Denali (6 190 m), aussi appelé mont McKinley, est la plus haute montagne d'Amérique du Nord, dans la chaîne d'Alaska, au cœur du parc national du même nom. Il s'élève de plus de 5 km depuis sa base — l'un des plus grands dénivelés terrestres.",
          "La maquette couvre environ 15×15 km : le massif et ses deux sommets, les glaciers Kahiltna et Muldrow sur des dizaines de kilomètres et les sommets voisins acérés. Les vallées glaciaires apparaissent comme de larges « rivières » douces.",
          "Un cadeau pour les alpinistes des Sept Sommets et les amoureux de la nature sauvage de l'Alaska."] },
      es: { name: "Denali", country: "EE. UU., Alaska", title: "Maqueta 3D del Denali — la montaña más alta de Norteamérica",
        p: ["El Denali (6190 m), también conocido como monte McKinley, es la montaña más alta de Norteamérica, en la cordillera de Alaska, dentro del parque nacional del mismo nombre. Se eleva más de 5 km desde su base: uno de los mayores desniveles en tierra firme.",
          "La maqueta abarca unos 15×15 km: el macizo con sus dos cumbres, los glaciares Kahiltna y Muldrow que se extienden decenas de kilómetros y los picos vecinos afilados. Los valles glaciares aparecen como anchos «ríos» suaves.",
          "Un regalo para alpinistas de las Siete Cumbres y amantes de la naturaleza salvaje de Alaska."] },
    },
  },
  {
    slug: "table-mountain", presetId: "table_mountain", elev: 1085, areaKm: 6, lat: -33.9625, lon: 18.40361, photo: "/mountains/presets/table_mountain.jpg",
    t: {
      uk: { name: "Столова гора", country: "ПАР, Кейптаун", title: "3D-модель Столової гори — пласка вершина над Кейптауном",
        p: ["Столова гора (1085 м) височіє над Кейптауном у Південно-Африканській Республіці. Її вершина — майже пласке плато близько 3 км завдовжки, яке часто накриває хмара, прозвана «скатертиною». Поруч — Левова Голова й Пік Диявола.",
          "Модель охоплює близько 6×6 км: плато, прямовисні скелі над містом, Левову Голову й схили до океану. Контраст між пласким верхом і стрімкими стінами — найкраще, що є в цій моделі.",
          "Подарунок для тих, хто був у Кейптауні, або для мандрівників, що збирають незвичні гори. Добре поєднується з кольоровим супутниковим знімком."] },
      en: { name: "Table Mountain", country: "South Africa, Cape Town", title: "3D model of Table Mountain — the flat summit above Cape Town",
        p: ["Table Mountain (1,085 m) towers over Cape Town in South Africa. Its top is an almost flat plateau about 3 km long, often covered by a cloud nicknamed the “tablecloth”. Lion's Head and Devil's Peak stand beside it.",
          "The model covers about 6×6 km: the plateau, the sheer cliffs above the city, Lion's Head and the slopes to the ocean. The contrast between the flat top and the steep walls is the best part of this model.",
          "A gift for anyone who has been to Cape Town or for travellers who collect unusual mountains. Pairs well with the colour satellite texture."] },
      de: { name: "Tafelberg", country: "Südafrika, Kapstadt", title: "3D-Modell des Tafelbergs — der flache Gipfel über Kapstadt",
        p: ["Der Tafelberg (1085 m) überragt Kapstadt in Südafrika. Sein Gipfel ist ein fast ebenes Plateau von rund 3 km Länge, oft bedeckt von einer Wolke, die „Tischtuch“ heißt. Daneben stehen Lion's Head und Devil's Peak.",
          "Das Modell zeigt etwa 6×6 km: das Plateau, die Steilwände über der Stadt, Lion's Head und die Hänge zum Ozean. Der Kontrast zwischen flacher Oberseite und steilen Wänden ist das Beste an diesem Modell.",
          "Ein Geschenk für Kapstadt-Reisende und Sammler ungewöhnlicher Berge — schön mit farbiger Satellitentextur."] },
      pl: { name: "Góra Stołowa", country: "RPA, Kapsztad", title: "Model 3D Góry Stołowej — płaski szczyt nad Kapsztadem",
        p: ["Góra Stołowa (1085 m) góruje nad Kapsztadem w RPA. Jej szczyt to niemal płaski płaskowyż o długości około 3 km, często przykryty chmurą zwaną „obrusem”. Obok stoją Lion's Head i Devil's Peak.",
          "Model obejmuje około 6×6 km: płaskowyż, pionowe urwiska nad miastem, Lion's Head i zbocza ku oceanowi. Kontrast płaskiej góry i stromych ścian to najlepsze w tym modelu.",
          "Prezent dla tych, którzy byli w Kapsztadzie, albo dla podróżników kolekcjonujących nietypowe góry — pięknie wygląda z kolorową teksturą satelitarną."] },
      fr: { name: "Montagne de la Table", country: "Afrique du Sud, Le Cap", title: "Maquette 3D de la montagne de la Table — le sommet plat du Cap",
        p: ["La montagne de la Table (1 085 m) domine Le Cap, en Afrique du Sud. Son sommet est un plateau presque plat d'environ 3 km de long, souvent recouvert d'un nuage surnommé la « nappe ». À côté se dressent Lion's Head et Devil's Peak.",
          "La maquette couvre environ 6×6 km : le plateau, les falaises au-dessus de la ville, Lion's Head et les pentes vers l'océan. Le contraste entre le sommet plat et les parois abruptes fait tout le charme de ce modèle.",
          "Un cadeau pour ceux qui sont allés au Cap ou pour les voyageurs qui collectionnent les montagnes insolites — superbe avec la texture satellite en couleur."] },
      es: { name: "Montaña de la Mesa", country: "Sudáfrica, Ciudad del Cabo", title: "Maqueta 3D de la Montaña de la Mesa — la cima plana de Ciudad del Cabo",
        p: ["La Montaña de la Mesa (1085 m) domina Ciudad del Cabo, en Sudáfrica. Su cima es una meseta casi plana de unos 3 km de largo, a menudo cubierta por una nube llamada el «mantel». A su lado se alzan Lion's Head y Devil's Peak.",
          "La maqueta abarca unos 6×6 km: la meseta, los acantilados sobre la ciudad, Lion's Head y las laderas hacia el océano. El contraste entre la cima plana y las paredes verticales es lo mejor del modelo.",
          "Un regalo para quien ha estado en Ciudad del Cabo o para viajeros que coleccionan montañas insólitas — precioso con la textura satelital en color."] },
    },
  },
];

export const PEAK_BY_SLUG: Record<string, Peak> = Object.fromEntries(PEAKS.map((p) => [p.slug, p]));

/** Сусідні вершини для перелінковки: спершу того ж «регіону» за індексом, по колу. */
export function relatedPeaks(slug: string, n = 6): Peak[] {
  const i = PEAKS.findIndex((p) => p.slug === slug);
  return Array.from({ length: Math.min(n, PEAKS.length - 1) }, (_, k) => PEAKS[(i + 1 + k) % PEAKS.length]);
}
