import type { AppLocale } from "@/i18n/routing";

/**
 * SEO 26.09.2026: ДРУГЕ КОЛО міст України (≥ ~40 тис. мешканців, крім 23 обласних
 * центрів із lib/templates.ts) — сторінки /maps/[slug] лише uk + en.
 *
 * ДЖЕРЕЛО ЦИФР: Wikidata (населення P1082 з датою 2015–2022, площа P2046,
 * координати P625). Маріуполь — Держстат на 01.01.2022 (у Вікіданих окупаційна
 * оцінка). Річка/візитівка/рік — вписані вручну ЛИШЕ там, де вони безсумнівні;
 * решта полів відсутня, і сторінка їх просто не показує (жодних вигаданих фактів).
 * Крим свідомо не включено (немає українських даних після 2014).
 * Згенеровано скриптом (scratchpad gen_tier2.py) — правити дані тут вручну можна.
 */
export interface UaCity2 {
  slug: string;
  center: [number, number];
  names: { uk: string; en: string };
  population: number;
  populationYear: number;
  area_km2?: number;
  oblast: { uk: string; latin: string };
  river?: { uk: string; latin: string };
  landmark?: { uk: string; latin: string };
  founded?: number;
  firstMention?: boolean;
}

/** Мови, якими ці сторінки мають справжній текст (решта — noindex, canonical на en). */
export const UA_CITY2_LOCALES: AppLocale[] = ["uk", "en"];

export const UA_CITIES_2: UaCity2[] = [
  { slug: "donetsk", center: [48.0158, 37.8028], names: { uk: "Донецьк", en: "Donetsk" }, population: 901645, populationYear: 2022, area_km2: 358, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Кальміус", latin: "Kalmius" }, landmark: { uk: "Донбас Арена", latin: "Donbas Arena" }, founded: 1869, firstMention: false },
  { slug: "mariupol", center: [47.1306, 37.5639], names: { uk: "Маріуполь", en: "Mariupol" }, population: 425681, populationYear: 2022, area_km2: 244, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Азовське море", latin: "Sea of Azov" }, landmark: { uk: "Драматичний театр", latin: "Drama Theatre" }, founded: 1778, firstMention: false },
  { slug: "luhansk", center: [48.5717, 39.2973], names: { uk: "Луганськ", en: "Luhansk" }, population: 403938, populationYear: 2019, area_km2: 257, oblast: { uk: "Луганська область", latin: "Luhansk Oblast" }, river: { uk: "Лугань", latin: "Luhan" }, landmark: { uk: "Музей Володимира Даля", latin: "Volodymyr Dahl Museum" }, founded: 1795, firstMention: false },
  { slug: "makiivka", center: [48.0556, 37.9611], names: { uk: "Макіївка", en: "Makiivka" }, population: 338968, populationYear: 2022, area_km2: 426, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Грузька", latin: "Hruzka" } },
  { slug: "horlivka", center: [48.3336, 38.0925], names: { uk: "Горлівка", en: "Horlivka" }, population: 239828, populationYear: 2020, area_km2: 422, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, founded: 1779, firstMention: false },
  { slug: "kamianske", center: [48.5167, 34.6133], names: { uk: "Кам'янське", en: "Kamianske" }, population: 226845, populationYear: 2022, area_km2: 138, oblast: { uk: "Дніпропетровська область", latin: "Dnipropetrovsk Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" }, founded: 1750, firstMention: false },
  { slug: "kremenchuk", center: [49.0631, 33.4039], names: { uk: "Кременчук", en: "Kremenchuk" }, population: 215271, populationYear: 2022, area_km2: 96, oblast: { uk: "Полтавська область", latin: "Poltava Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" }, landmark: { uk: "Крюківський міст", latin: "Kryukiv Bridge" }, founded: 1571, firstMention: true },
  { slug: "bila-tserkva", center: [49.7956, 30.1167], names: { uk: "Біла Церква", en: "Bila Tserkva" }, population: 207273, populationYear: 2022, area_km2: 67.84, oblast: { uk: "Київська область", latin: "Kyiv Oblast" }, river: { uk: "Рось", latin: "Ros" }, landmark: { uk: "Дендропарк «Олександрія»", latin: "Oleksandriia Arboretum" }, founded: 1032, firstMention: false },
  { slug: "sievierodonetsk", center: [48.9481, 38.4933], names: { uk: "Сіверськодонецьк", en: "Sievierodonetsk" }, population: 150000, populationYear: 2015, area_km2: 42.1, oblast: { uk: "Луганська область", latin: "Luhansk Oblast" }, river: { uk: "Сіверський Донець", latin: "Siverskyi Donets" }, founded: 1934, firstMention: false },
  { slug: "melitopol", center: [46.8489, 35.3675], names: { uk: "Мелітополь", en: "Melitopol" }, population: 148851, populationYear: 2022, area_km2: 49.66, oblast: { uk: "Запорізька область", latin: "Zaporizhzhia Oblast" }, river: { uk: "Молочна", latin: "Molochna" }, founded: 1784, firstMention: false },
  { slug: "kramatorsk", center: [48.7392, 37.5839], names: { uk: "Краматорськ", en: "Kramatorsk" }, population: 147145, populationYear: 2022, area_km2: 77.36, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Казенний Торець", latin: "Kazennyi Torets" }, founded: 1868, firstMention: false },
  { slug: "brovary", center: [50.5111, 30.7900], names: { uk: "Бровари", en: "Brovary" }, population: 109473, populationYear: 2021, area_km2: 34, oblast: { uk: "Київська область", latin: "Kyiv Oblast" }, founded: 1630, firstMention: true },
  { slug: "alchevsk", center: [48.4672, 38.7983], names: { uk: "Алчевськ", en: "Alchevsk" }, population: 107438, populationYear: 2019, area_km2: 50, oblast: { uk: "Луганська область", latin: "Luhansk Oblast" }, founded: 1895, firstMention: false },
  { slug: "berdiansk", center: [46.7556, 36.7889], names: { uk: "Бердянськ", en: "Berdiansk" }, population: 106311, populationYear: 2022, area_km2: 80, oblast: { uk: "Запорізька область", latin: "Zaporizhzhia Oblast" }, river: { uk: "Азовське море", latin: "Sea of Azov" }, landmark: { uk: "Бердянська коса", latin: "Berdiansk Spit" }, founded: 1827, firstMention: false },
  { slug: "nikopol", center: [47.5667, 34.4000], names: { uk: "Нікополь", en: "Nikopol" }, population: 105160, populationYear: 2022, area_km2: 50, oblast: { uk: "Дніпропетровська область", latin: "Dnipropetrovsk Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" } },
  { slug: "sloviansk", center: [48.8533, 37.6059], names: { uk: "Слов'янськ", en: "Sloviansk" }, population: 105141, populationYear: 2022, area_km2: 58.9, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Казенний Торець", latin: "Kazennyi Torets" }, landmark: { uk: "Слов'янські солоні озера", latin: "Sloviansk salt lakes" }, founded: 1645, firstMention: false },
  { slug: "pavlohrad", center: [48.5200, 35.8700], names: { uk: "Павлоград", en: "Pavlohrad" }, population: 101430, populationYear: 2022, area_km2: 59, oblast: { uk: "Дніпропетровська область", latin: "Dnipropetrovsk Oblast" }, river: { uk: "Вовча", latin: "Vovcha" }, founded: 1779, firstMention: false },
  { slug: "kamianets-podilskyi", center: [48.6806, 26.5806], names: { uk: "Кам'янець-Подільський", en: "Kamianets-Podilskyi" }, population: 96896, populationYear: 2022, area_km2: 27.871, oblast: { uk: "Хмельницька область", latin: "Khmelnytskyi Oblast" }, river: { uk: "Смотрич", latin: "Smotrych" }, landmark: { uk: "Кам'янець-Подільська фортеця", latin: "Kamianets-Podilskyi Castle" }, founded: 1062, firstMention: true },
  { slug: "lysychansk", center: [48.9169, 38.4306], names: { uk: "Лисичанськ", en: "Lysychansk" }, population: 96161, populationYear: 2020, area_km2: 95.64, oblast: { uk: "Луганська область", latin: "Luhansk Oblast" }, river: { uk: "Сіверський Донець", latin: "Siverskyi Donets" }, founded: 1710, firstMention: false },
  { slug: "mukachevo", center: [48.4414, 22.7136], names: { uk: "Мукачево", en: "Mukachevo" }, population: 85569, populationYear: 2022, area_km2: 27, oblast: { uk: "Закарпатська область", latin: "Zakarpattia Oblast" }, river: { uk: "Латориця", latin: "Latorytsia" }, landmark: { uk: "Замок Паланок", latin: "Palanok Castle" } },
  { slug: "konotop", center: [51.2375, 33.2083], names: { uk: "Конотоп", en: "Konotop" }, population: 83543, populationYear: 2022, area_km2: 43.78, oblast: { uk: "Сумська область", latin: "Sumy Oblast" }, river: { uk: "Єзуч", latin: "Yezuch" }, founded: 1634, firstMention: true },
  { slug: "uman", center: [48.7500, 30.2167], names: { uk: "Умань", en: "Uman" }, population: 82154, populationYear: 2021, area_km2: 41, oblast: { uk: "Черкаська область", latin: "Cherkasy Oblast" }, river: { uk: "Уманка", latin: "Umanka" }, landmark: { uk: "Парк «Софіївка»", latin: "Sofiyivka Park" }, founded: 1616, firstMention: true },
  { slug: "oleksandriia", center: [48.6667, 33.1167], names: { uk: "Олександрія", en: "Oleksandriia" }, population: 76097, populationYear: 2022, area_km2: 55, oblast: { uk: "Кіровоградська область", latin: "Kirovohrad Oblast" }, river: { uk: "Інгулець", latin: "Inhulets" }, founded: 1754, firstMention: false },
  { slug: "drohobych", center: [49.3500, 23.5000], names: { uk: "Дрогобич", en: "Drohobych" }, population: 73682, populationYear: 2022, area_km2: 41, oblast: { uk: "Львівська область", latin: "Lviv Oblast" }, river: { uk: "Тисмениця", latin: "Tysmenytsia" }, landmark: { uk: "Церква святого Юра", latin: "St. George's Church" }, founded: 1387, firstMention: true },
  { slug: "berdychiv", center: [49.8919, 28.6000], names: { uk: "Бердичів", en: "Berdychiv" }, population: 73046, populationYear: 2022, area_km2: 35.33, oblast: { uk: "Житомирська область", latin: "Zhytomyr Oblast" }, river: { uk: "Гнилоп'ять", latin: "Hnylopiat" }, landmark: { uk: "Монастир босих кармелітів", latin: "Discalced Carmelite Monastery" }, founded: 1430, firstMention: true },
  { slug: "kostiantynivka", center: [48.5333, 37.7167], names: { uk: "Костянтинівка", en: "Kostiantynivka" }, population: 72888, populationYear: 2017, area_km2: 66, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Кривий Торець", latin: "Kryvyi Torets" }, founded: 1870, firstMention: false },
  { slug: "shostka", center: [51.8657, 33.4766], names: { uk: "Шостка", en: "Shostka" }, population: 71966, populationYear: 2022, area_km2: 43.6882, oblast: { uk: "Сумська область", latin: "Sumy Oblast" }, river: { uk: "Шостка", latin: "Shostka" }, founded: 1739, firstMention: false },
  { slug: "bakhmut", center: [48.5947, 38.0008], names: { uk: "Бахмут", en: "Bakhmut" }, population: 71094, populationYear: 2022, area_km2: 41.6, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Бахмутка", latin: "Bakhmutka" }, founded: 1571, firstMention: true },
  { slug: "izmail", center: [45.3418, 28.8346], names: { uk: "Ізмаїл", en: "Izmail" }, population: 70731, populationYear: 2021, area_km2: 53, oblast: { uk: "Одеська область", latin: "Odesa Oblast" }, river: { uk: "Дунай", latin: "Danube" }, landmark: { uk: "Ізмаїльська фортеця", latin: "Izmail Fortress" } },
  { slug: "samar", center: [48.6316, 35.2245], names: { uk: "Самар", en: "Samar" }, population: 69855, populationYear: 2022, area_km2: 36, oblast: { uk: "Дніпропетровська область", latin: "Dnipropetrovsk Oblast" }, river: { uk: "Самара", latin: "Samara" }, landmark: { uk: "Троїцький собор", latin: "Holy Trinity Cathedral" } },
  { slug: "kovel", center: [51.2167, 24.7167], names: { uk: "Ковель", en: "Kovel" }, population: 67575, populationYear: 2022, area_km2: 50, oblast: { uk: "Волинська область", latin: "Volyn Oblast" }, river: { uk: "Турія", latin: "Turiia" } },
  { slug: "nizhyn", center: [51.0474, 31.8805], names: { uk: "Ніжин", en: "Nizhyn" }, population: 66981, populationYear: 2021, area_km2: 50.5, oblast: { uk: "Чернігівська область", latin: "Chernihiv Oblast" }, river: { uk: "Остер", latin: "Oster" }, landmark: { uk: "Ніжинський університет імені Гоголя", latin: "Nizhyn Gogol State University" } },
  { slug: "smila", center: [49.2167, 31.8667], names: { uk: "Сміла", en: "Smila" }, population: 65675, populationYear: 2022, area_km2: 39.85, oblast: { uk: "Черкаська область", latin: "Cherkasy Oblast" }, river: { uk: "Тясмин", latin: "Tiasmyn" }, founded: 1542, firstMention: true },
  { slug: "irpin", center: [50.5167, 30.2500], names: { uk: "Ірпінь", en: "Irpin" }, population: 65167, populationYear: 2022, area_km2: 110.83, oblast: { uk: "Київська область", latin: "Kyiv Oblast" }, river: { uk: "Ірпінь", latin: "Irpin" }, landmark: { uk: "Центральний парк", latin: "Central Park" }, founded: 1899, firstMention: false },
  { slug: "kalush", center: [49.0442, 24.3597], names: { uk: "Калуш", en: "Kalush" }, population: 65088, populationYear: 2022, area_km2: 64.53, oblast: { uk: "Івано-Франківська область", latin: "Ivano-Frankivsk Oblast" }, river: { uk: "Лімниця", latin: "Limnytsia" }, founded: 1437, firstMention: true },
  { slug: "sheptytskyi", center: [50.3822, 24.2275], names: { uk: "Шептицький", en: "Sheptytskyi" }, population: 64297, populationYear: 2022, area_km2: 37.6, oblast: { uk: "Львівська область", latin: "Lviv Oblast" }, river: { uk: "Західний Буг", latin: "Western Bug" }, landmark: { uk: "Палац Потоцьких", latin: "Potocki Palace" }, founded: 1692, firstMention: false },
  { slug: "pokrovsk", center: [48.2833, 37.1833], names: { uk: "Покровськ", en: "Pokrovsk" }, population: 63437, populationYear: 2017, area_km2: 39.3, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" } },
  { slug: "pervomaisk", center: [48.0500, 30.8500], names: { uk: "Первомайськ", en: "Pervomaisk" }, population: 62426, populationYear: 2022, area_km2: 25.14, oblast: { uk: "Миколаївська область", latin: "Mykolaiv Oblast" }, river: { uk: "Південний Буг", latin: "Southern Bug" } },
  { slug: "boryspil", center: [50.3500, 30.9500], names: { uk: "Бориспіль", en: "Boryspil" }, population: 62281, populationYear: 2019, area_km2: 37.01, oblast: { uk: "Київська область", latin: "Kyiv Oblast" }, river: { uk: "Альта", latin: "Alta" } },
  { slug: "korosten", center: [50.9500, 28.6500], names: { uk: "Коростень", en: "Korosten" }, population: 61496, populationYear: 2022, area_km2: 33.851, oblast: { uk: "Житомирська область", latin: "Zhytomyr Oblast" }, river: { uk: "Уж", latin: "Uzh" }, landmark: { uk: "Древлянський парк", latin: "Drevlianskyi Park" }, founded: 945, firstMention: true },
  { slug: "kolomyia", center: [48.5167, 25.0333], names: { uk: "Коломия", en: "Kolomyia" }, population: 60821, populationYear: 2022, area_km2: 40.72, oblast: { uk: "Івано-Франківська область", latin: "Ivano-Frankivsk Oblast" }, river: { uk: "Прут", latin: "Prut" }, landmark: { uk: "Музей «Писанка»", latin: "Pysanka Museum" }, founded: 1241, firstMention: true },
  { slug: "stryi", center: [49.2500, 23.8500], names: { uk: "Стрий", en: "Stryi" }, population: 59425, populationYear: 2022, area_km2: 16.95, oblast: { uk: "Львівська область", latin: "Lviv Oblast" }, river: { uk: "Стрий", latin: "Stryi" }, founded: 1385, firstMention: true },
  { slug: "chornomorsk", center: [46.3013, 30.6545], names: { uk: "Чорноморськ", en: "Chornomorsk" }, population: 57983, populationYear: 2022, area_km2: 25, oblast: { uk: "Одеська область", latin: "Odesa Oblast" }, river: { uk: "Чорне море", latin: "Black Sea" }, landmark: { uk: "Морський порт", latin: "Seaport" }, founded: 1952, firstMention: false },
  { slug: "zviahel", center: [50.5833, 27.6333], names: { uk: "Звягель", en: "Zviahel" }, population: 55086, populationYear: 2022, area_km2: 27, oblast: { uk: "Житомирська область", latin: "Zhytomyr Oblast" }, river: { uk: "Случ", latin: "Sluch" }, landmark: { uk: "Музей Лесі Українки", latin: "Lesya Ukrainka Museum" }, founded: 1256, firstMention: true },
  { slug: "lozova", center: [48.8892, 36.3161], names: { uk: "Лозова", en: "Lozova" }, population: 54026, populationYear: 2021, area_km2: 148, oblast: { uk: "Харківська область", latin: "Kharkiv Oblast" }, founded: 1869, firstMention: false },
  { slug: "druzhkivka", center: [48.6203, 37.5278], names: { uk: "Дружківка", en: "Druzhkivka" }, population: 53977, populationYear: 2022, area_km2: 46.53, oblast: { uk: "Донецька область", latin: "Donetsk Oblast" }, river: { uk: "Казенний Торець", latin: "Kazennyi Torets" }, founded: 1781, firstMention: false },
  { slug: "pryluky", center: [50.6000, 32.4000], names: { uk: "Прилуки", en: "Pryluky" }, population: 53395, populationYear: 2020, area_km2: 42, oblast: { uk: "Чернігівська область", latin: "Chernihiv Oblast" }, river: { uk: "Удай", latin: "Udai" }, founded: 1085, firstMention: true },
  { slug: "enerhodar", center: [47.4989, 34.6558], names: { uk: "Енергодар", en: "Enerhodar" }, population: 52237, populationYear: 2022, area_km2: 635, oblast: { uk: "Запорізька область", latin: "Zaporizhzhia Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" }, landmark: { uk: "Запорізька АЕС", latin: "Zaporizhzhia NPP" }, founded: 1970, firstMention: false },
  { slug: "horishni-plavni", center: [49.0107, 33.6562], names: { uk: "Горішні Плавні", en: "Horishni Plavni" }, population: 49854, populationYear: 2022, area_km2: 110.968, oblast: { uk: "Полтавська область", latin: "Poltava Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" }, founded: 1960, firstMention: false },
  { slug: "novovolynsk", center: [50.7333, 24.1667], names: { uk: "Нововолинськ", en: "Novovolynsk" }, population: 49772, populationYear: 2022, area_km2: 17, oblast: { uk: "Волинська область", latin: "Volyn Oblast" } },
  { slug: "bilhorod-dnistrovskyi", center: [46.1939, 30.3411], names: { uk: "Білгород-Дністровський", en: "Bilhorod-Dnistrovskyi" }, population: 47727, populationYear: 2020, area_km2: 31, oblast: { uk: "Одеська область", latin: "Odesa Oblast" }, river: { uk: "Дністровський лиман", latin: "Dniester Estuary" }, landmark: { uk: "Аккерманська фортеця", latin: "Akkerman Fortress" } },
  { slug: "okhtyrka", center: [50.3074, 34.9016], names: { uk: "Охтирка", en: "Okhtyrka" }, population: 46660, populationYear: 2022, area_km2: 31.86, oblast: { uk: "Сумська область", latin: "Sumy Oblast" }, river: { uk: "Ворскла", latin: "Vorskla" }, founded: 1641, firstMention: false },
  { slug: "fastiv", center: [50.0747, 29.9181], names: { uk: "Фастів", en: "Fastiv" }, population: 45907, populationYear: 2019, area_km2: 43, oblast: { uk: "Київська область", latin: "Kyiv Oblast" }, river: { uk: "Унава", latin: "Unava" }, landmark: { uk: "Костел Воздвиження Святого Хреста", latin: "Church of the Exaltation of the Holy Cross" }, founded: 1390, firstMention: true },
  { slug: "izium", center: [49.1958, 37.2803], names: { uk: "Ізюм", en: "Izium" }, population: 45884, populationYear: 2021, area_km2: 436, oblast: { uk: "Харківська область", latin: "Kharkiv Oblast" }, river: { uk: "Сіверський Донець", latin: "Siverskyi Donets" }, landmark: { uk: "Гора Кременець", latin: "Kremenets Hill" }, founded: 1681, firstMention: false },
  { slug: "svitlovodsk", center: [49.0833, 33.2500], names: { uk: "Світловодськ", en: "Svitlovodsk" }, population: 45312, populationYear: 2017, area_km2: 45, oblast: { uk: "Кіровоградська область", latin: "Kirovohrad Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" }, landmark: { uk: "Кременчуцька ГЕС", latin: "Kremenchuk Hydroelectric Station" }, founded: 1954, firstMention: false },
  { slug: "nova-kakhovka", center: [46.7550, 33.3750], names: { uk: "Нова Каховка", en: "Nova Kakhovka" }, population: 45069, populationYear: 2021, area_km2: 22.7, oblast: { uk: "Херсонська область", latin: "Kherson Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" }, founded: 1952, firstMention: false },
  { slug: "marhanets", center: [47.6480, 34.6167], names: { uk: "Марганець", en: "Marhanets" }, population: 44980, populationYear: 2022, area_km2: 37, oblast: { uk: "Дніпропетровська область", latin: "Dnipropetrovsk Oblast" }, river: { uk: "Дніпро", latin: "Dnipro" }, founded: 1938, firstMention: false },
  { slug: "lubny", center: [50.0186, 32.9869], names: { uk: "Лубни", en: "Lubny" }, population: 44089, populationYear: 2022, area_km2: 45.6, oblast: { uk: "Полтавська область", latin: "Poltava Oblast" }, river: { uk: "Сула", latin: "Sula" }, landmark: { uk: "Мгарський монастир", latin: "Mhar Monastery" }, founded: 988, firstMention: true },
  { slug: "zhovti-vody", center: [48.3500, 33.5167], names: { uk: "Жовті Води", en: "Zhovti Vody" }, population: 42052, populationYear: 2022, area_km2: 33.25, oblast: { uk: "Дніпропетровська область", latin: "Dnipropetrovsk Oblast" }, river: { uk: "Жовта", latin: "Zhovta" }, founded: 1895, firstMention: false },
  { slug: "varash", center: [51.3400, 25.8508], names: { uk: "Вараш", en: "Varash" }, population: 41711, populationYear: 2022, area_km2: 11.3, oblast: { uk: "Рівненська область", latin: "Rivne Oblast" }, river: { uk: "Стир", latin: "Styr" }, landmark: { uk: "Рівненська АЕС", latin: "Rivne NPP" }, founded: 1973, firstMention: false },
  { slug: "vyshneve", center: [50.3833, 30.3667], names: { uk: "Вишневе", en: "Vyshneve" }, population: 40919, populationYear: 2019, area_km2: 25.2, oblast: { uk: "Київська область", latin: "Kyiv Oblast" }, founded: 1887, firstMention: false },
  { slug: "romny", center: [50.7428, 33.4879], names: { uk: "Ромни", en: "Romny" }, population: 40316, populationYear: 2018, area_km2: 65, oblast: { uk: "Сумська область", latin: "Sumy Oblast" }, river: { uk: "Сула", latin: "Sula" } },
  { slug: "shepetivka", center: [50.1833, 27.0667], names: { uk: "Шепетівка", en: "Shepetivka" }, population: 40299, populationYear: 2022, area_km2: 40, oblast: { uk: "Хмельницька область", latin: "Khmelnytskyi Oblast" } },
  { slug: "myrhorod", center: [49.9640, 33.6124], names: { uk: "Миргород", en: "Myrhorod" }, population: 40160, populationYear: 2017, area_km2: 19, oblast: { uk: "Полтавська область", latin: "Poltava Oblast" }, river: { uk: "Хорол", latin: "Khorol" }, landmark: { uk: "Курорт «Миргород»", latin: "Myrhorod spa resort" }, founded: 1575, firstMention: true },
  { slug: "podilsk", center: [47.7531, 29.5309], names: { uk: "Подільськ", en: "Podilsk" }, population: 40155, populationYear: 2019, area_km2: 25.4, oblast: { uk: "Одеська область", latin: "Odesa Oblast" } },
];

export const UA_CITY2_BY_SLUG: Record<string, UaCity2> = Object.fromEntries(
  UA_CITIES_2.map((c) => [c.slug, c]),
);
