import type { AppLocale } from "@/i18n/routing";
import type { CityFacts } from "@/lib/cityFacts";

/**
 * SEO-РОЗШИРЕННЯ НА ЄС (29.07.2026): сторінки міст ЄВРОПИ для /maps/[slug].
 *
 * Навіщо: локалі de/pl/fr/es досі мали контент лише про українські міста —
 * нульовий локальний інтерес для їхньої аудиторії. Німець шукає
 * «3D-Karte Berlin», поляк «mapa 3D Warszawy». Конструктор і так працює для
 * всього світу, тож це НЕ doorway — сторінки під реальний продукт.
 *
 * АНТИ-DOORWAY ПРАВИЛО: місто потрапляє сюди ЛИШЕ з реальними унікальними
 * даними (населення/рік/заснування/площа/річка/регіон/орієнтир) — той самий
 * контракт CityFacts, що й для українських міст. Без даних — без сторінки.
 *
 * ФАЙЛ ЗГЕНЕРОВАНО: scripts/_gen_world_cities.py (правити там, не тут).
 */
export interface WorldCity {
  slug: string;
  /** Ключ пресету конструктора (CITIES у app/[locale]/create/page.tsx). */
  key: string;
  center: [number, number];
  /** Мова-таргет: для внутрішньої перелінковки й пріоритету в sitemap. */
  primaryLocale: AppLocale;
  names: Record<AppLocale, string>;
  facts: CityFacts;
}

export const WORLD_CITIES: WorldCity[] = [
  { slug: "warsaw", key: "World_Warsaw", center: [52.2297, 21.0122], primaryLocale: "pl",
    names: { uk: "Варшава", en: "Warsaw", de: "Warschau", pl: "Warszawa", fr: "Varsovie", es: "Varsovia" },
    facts: { population: 1861975, populationYear: 2023, founded: 1300, firstMention: true, area_km2: 517.2,
      river: { uk: "Вісла", latin: "Vistula" }, oblast: { uk: "Мазовецьке воєводство", latin: "Masovian Voivodeship" },
      landmark: { uk: "Палац культури і науки", latin: "Palace of Culture and Science" } } },
  { slug: "krakow", key: "World_Krakow", center: [50.0647, 19.945], primaryLocale: "pl",
    names: { uk: "Краків", en: "Kraków", de: "Krakau", pl: "Kraków", fr: "Cracovie", es: "Cracovia" },
    facts: { population: 804237, populationYear: 2023, founded: 966, firstMention: true, area_km2: 326.8,
      river: { uk: "Вісла", latin: "Vistula" }, oblast: { uk: "Малопольське воєводство", latin: "Lesser Poland" },
      landmark: { uk: "Вавельський замок", latin: "Wawel Castle" } } },
  { slug: "wroclaw", key: "World_Wroclaw", center: [51.1079, 17.0385], primaryLocale: "pl",
    names: { uk: "Вроцлав", en: "Wrocław", de: "Breslau", pl: "Wrocław", fr: "Wrocław", es: "Breslavia" },
    facts: { population: 674312, populationYear: 2023, founded: 1000, firstMention: true, area_km2: 292.8,
      river: { uk: "Одра", latin: "Oder" }, oblast: { uk: "Нижньосілезьке воєводство", latin: "Lower Silesia" },
      landmark: { uk: "Ринок Вроцлава", latin: "Wrocław Market Square" } } },
  { slug: "gdansk", key: "World_Gdansk", center: [54.352, 18.6466], primaryLocale: "pl",
    names: { uk: "Ґданськ", en: "Gdańsk", de: "Danzig", pl: "Gdańsk", fr: "Gdańsk", es: "Gdansk" },
    facts: { population: 486492, populationYear: 2023, founded: 997, firstMention: true, area_km2: 262.0,
      river: { uk: "Мотлава", latin: "Motława" }, oblast: { uk: "Поморське воєводство", latin: "Pomerania" },
      landmark: { uk: "Журав", latin: "Gdańsk Crane" } } },
  { slug: "poznan", key: "World_Poznan", center: [52.4064, 16.9252], primaryLocale: "pl",
    names: { uk: "Познань", en: "Poznań", de: "Posen", pl: "Poznań", fr: "Poznań", es: "Poznan" },
    facts: { population: 541316, populationYear: 2023, founded: 968, firstMention: true, area_km2: 261.9,
      river: { uk: "Варта", latin: "Warta" }, oblast: { uk: "Великопольське воєводство", latin: "Greater Poland" },
      landmark: { uk: "Познанська ратуша", latin: "Poznań Town Hall" } } },
  { slug: "lodz", key: "World_Lodz", center: [51.7592, 19.456], primaryLocale: "pl",
    names: { uk: "Лодзь", en: "Łódź", de: "Lodz", pl: "Łódź", fr: "Łódź", es: "Lodz" },
    facts: { population: 658444, populationYear: 2023, founded: 1332, firstMention: true, area_km2: 293.3,
      river: { uk: "Лодка", latin: "Łódka" }, oblast: { uk: "Лодзьке воєводство", latin: "Łódź Voivodeship" },
      landmark: { uk: "Вулиця Пьотрковська", latin: "Piotrkowska Street" } } },
  { slug: "szczecin", key: "World_Szczecin", center: [53.4285, 14.5528], primaryLocale: "pl",
    names: { uk: "Щецин", en: "Szczecin", de: "Stettin", pl: "Szczecin", fr: "Szczecin", es: "Szczecin" },
    facts: { population: 391566, populationYear: 2023, founded: 1243, firstMention: false, area_km2: 300.6,
      river: { uk: "Одра", latin: "Oder" }, oblast: { uk: "Західнопоморське воєводство", latin: "West Pomerania" },
      landmark: { uk: "Замок Померанських князів", latin: "Pomeranian Dukes' Castle" } } },
  { slug: "lublin", key: "World_Lublin", center: [51.2465, 22.5684], primaryLocale: "pl",
    names: { uk: "Люблін", en: "Lublin", de: "Lublin", pl: "Lublin", fr: "Lublin", es: "Lublin" },
    facts: { population: 331243, populationYear: 2023, founded: 1317, firstMention: false, area_km2: 147.5,
      river: { uk: "Бистриця", latin: "Bystrzyca" }, oblast: { uk: "Люблінське воєводство", latin: "Lublin Voivodeship" },
      landmark: { uk: "Люблінський замок", latin: "Lublin Castle" } } },
  { slug: "berlin", key: "World_Berlin", center: [52.52, 13.405], primaryLocale: "de",
    names: { uk: "Берлін", en: "Berlin", de: "Berlin", pl: "Berlin", fr: "Berlin", es: "Berlín" },
    facts: { population: 3878100, populationYear: 2023, founded: 1237, firstMention: true, area_km2: 891.7,
      river: { uk: "Шпрее", latin: "Spree" }, oblast: { uk: "Земля Берлін", latin: "State of Berlin" },
      landmark: { uk: "Бранденбурзькі ворота", latin: "Brandenburg Gate" } } },
  { slug: "munich", key: "World_Munich", center: [48.1351, 11.582], primaryLocale: "de",
    names: { uk: "Мюнхен", en: "Munich", de: "München", pl: "Monachium", fr: "Munich", es: "Múnich" },
    facts: { population: 1512491, populationYear: 2023, founded: 1158, firstMention: false, area_km2: 310.7,
      river: { uk: "Ізар", latin: "Isar" }, oblast: { uk: "Баварія", latin: "Bavaria" },
      landmark: { uk: "Марієнплац", latin: "Marienplatz" } } },
  { slug: "hamburg", key: "World_Hamburg", center: [53.5511, 9.9937], primaryLocale: "de",
    names: { uk: "Гамбург", en: "Hamburg", de: "Hamburg", pl: "Hamburg", fr: "Hambourg", es: "Hamburgo" },
    facts: { population: 1892122, populationYear: 2023, founded: 808, firstMention: false, area_km2: 755.2,
      river: { uk: "Ельба", latin: "Elbe" }, oblast: { uk: "Земля Гамбург", latin: "State of Hamburg" },
      landmark: { uk: "Ельбська філармонія", latin: "Elbphilharmonie" } } },
  { slug: "cologne", key: "World_Cologne", center: [50.9375, 6.9603], primaryLocale: "de",
    names: { uk: "Кельн", en: "Cologne", de: "Köln", pl: "Kolonia", fr: "Cologne", es: "Colonia" },
    facts: { population: 1084831, populationYear: 2023, founded: -38, firstMention: false, area_km2: 405.0,
      river: { uk: "Рейн", latin: "Rhine" }, oblast: { uk: "Північний Рейн-Вестфалія", latin: "North Rhine-Westphalia" },
      landmark: { uk: "Кельнський собор", latin: "Cologne Cathedral" } } },
  { slug: "frankfurt", key: "World_Frankfurt", center: [50.1109, 8.6821], primaryLocale: "de",
    names: { uk: "Франкфурт", en: "Frankfurt", de: "Frankfurt am Main", pl: "Frankfurt", fr: "Francfort", es: "Fráncfort" },
    facts: { population: 773068, populationYear: 2023, founded: 794, firstMention: true, area_km2: 248.3,
      river: { uk: "Майн", latin: "Main" }, oblast: { uk: "Гессен", latin: "Hesse" },
      landmark: { uk: "Ремер", latin: "Römer" } } },
  { slug: "stuttgart", key: "World_Stuttgart", center: [48.7758, 9.1829], primaryLocale: "de",
    names: { uk: "Штутгарт", en: "Stuttgart", de: "Stuttgart", pl: "Stuttgart", fr: "Stuttgart", es: "Stuttgart" },
    facts: { population: 632865, populationYear: 2023, founded: 950, firstMention: false, area_km2: 207.4,
      river: { uk: "Неккар", latin: "Neckar" }, oblast: { uk: "Баден-Вюртемберг", latin: "Baden-Württemberg" },
      landmark: { uk: "Палацова площа", latin: "Schlossplatz" } } },
  { slug: "dusseldorf", key: "World_Dusseldorf", center: [51.2277, 6.7735], primaryLocale: "de",
    names: { uk: "Дюссельдорф", en: "Düsseldorf", de: "Düsseldorf", pl: "Düsseldorf", fr: "Düsseldorf", es: "Düsseldorf" },
    facts: { population: 629047, populationYear: 2023, founded: 1288, firstMention: false, area_km2: 217.4,
      river: { uk: "Рейн", latin: "Rhine" }, oblast: { uk: "Північний Рейн-Вестфалія", latin: "North Rhine-Westphalia" },
      landmark: { uk: "Райнтурм", latin: "Rheinturm" } } },
  { slug: "leipzig", key: "World_Leipzig", center: [51.3397, 12.3731], primaryLocale: "de",
    names: { uk: "Лейпциг", en: "Leipzig", de: "Leipzig", pl: "Lipsk", fr: "Leipzig", es: "Leipzig" },
    facts: { population: 628718, populationYear: 2023, founded: 1015, firstMention: true, area_km2: 297.8,
      river: { uk: "Вайсе-Ельстер", latin: "White Elster" }, oblast: { uk: "Саксонія", latin: "Saxony" },
      landmark: { uk: "Пам'ятник битві народів", latin: "Monument to the Battle of the Nations" } } },
  { slug: "dresden", key: "World_Dresden", center: [51.0504, 13.7373], primaryLocale: "de",
    names: { uk: "Дрезден", en: "Dresden", de: "Dresden", pl: "Drezno", fr: "Dresde", es: "Dresde" },
    facts: { population: 566222, populationYear: 2023, founded: 1206, firstMention: true, area_km2: 328.5,
      river: { uk: "Ельба", latin: "Elbe" }, oblast: { uk: "Саксонія", latin: "Saxony" },
      landmark: { uk: "Фрауенкірхе", latin: "Frauenkirche" } } },
  { slug: "nuremberg", key: "World_Nuremberg", center: [49.4521, 11.0767], primaryLocale: "de",
    names: { uk: "Нюрнберг", en: "Nuremberg", de: "Nürnberg", pl: "Norymberga", fr: "Nuremberg", es: "Núremberg" },
    facts: { population: 523026, populationYear: 2023, founded: 1050, firstMention: true, area_km2: 186.4,
      river: { uk: "Пегніц", latin: "Pegnitz" }, oblast: { uk: "Баварія", latin: "Bavaria" },
      landmark: { uk: "Нюрнберзький замок", latin: "Nuremberg Castle" } } },
  { slug: "vienna", key: "World_Vienna", center: [48.2082, 16.3738], primaryLocale: "de",
    names: { uk: "Відень", en: "Vienna", de: "Wien", pl: "Wiedeń", fr: "Vienne", es: "Viena" },
    facts: { population: 2005760, populationYear: 2023, founded: 1147, firstMention: true, area_km2: 414.9,
      river: { uk: "Дунай", latin: "Danube" }, oblast: { uk: "Земля Відень", latin: "State of Vienna" },
      landmark: { uk: "Собор Святого Стефана", latin: "St. Stephen's Cathedral" } } },
  { slug: "salzburg", key: "World_Salzburg", center: [47.8095, 13.055], primaryLocale: "de",
    names: { uk: "Зальцбург", en: "Salzburg", de: "Salzburg", pl: "Salzburg", fr: "Salzbourg", es: "Salzburgo" },
    facts: { population: 157479, populationYear: 2023, founded: 696, firstMention: false, area_km2: 65.7,
      river: { uk: "Зальцах", latin: "Salzach" }, oblast: { uk: "Земля Зальцбург", latin: "State of Salzburg" },
      landmark: { uk: "Фортеця Гогензальцбург", latin: "Hohensalzburg Fortress" } } },
  { slug: "zurich", key: "World_Zurich", center: [47.3769, 8.5417], primaryLocale: "de",
    names: { uk: "Цюрих", en: "Zurich", de: "Zürich", pl: "Zurych", fr: "Zurich", es: "Zúrich" },
    facts: { population: 443037, populationYear: 2023, founded: -15, firstMention: false, area_km2: 87.9,
      river: { uk: "Ліммат", latin: "Limmat" }, oblast: { uk: "Кантон Цюрих", latin: "Canton of Zurich" },
      landmark: { uk: "Гросмюнстер", latin: "Grossmünster" } } },
  { slug: "prague", key: "World_Prague", center: [50.0755, 14.4378], primaryLocale: "de",
    names: { uk: "Прага", en: "Prague", de: "Prag", pl: "Praga", fr: "Prague", es: "Praga" },
    facts: { population: 1384732, populationYear: 2023, founded: 885, firstMention: true, area_km2: 496.2,
      river: { uk: "Влтава", latin: "Vltava" }, oblast: { uk: "Столичний край", latin: "Prague Capital" },
      landmark: { uk: "Карлів міст", latin: "Charles Bridge" } } },
  { slug: "brno", key: "World_Brno", center: [49.1951, 16.6068], primaryLocale: "de",
    names: { uk: "Брно", en: "Brno", de: "Brünn", pl: "Brno", fr: "Brno", es: "Brno" },
    facts: { population: 400566, populationYear: 2023, founded: 1243, firstMention: false, area_km2: 230.2,
      river: { uk: "Свратка", latin: "Svratka" }, oblast: { uk: "Південноморавський край", latin: "South Moravia" },
      landmark: { uk: "Вілла Тугендгат", latin: "Villa Tugendhat" } } },
  { slug: "bratislava", key: "World_Bratislava", center: [48.1486, 17.1077], primaryLocale: "de",
    names: { uk: "Братислава", en: "Bratislava", de: "Pressburg", pl: "Bratysława", fr: "Bratislava", es: "Bratislava" },
    facts: { population: 475503, populationYear: 2023, founded: 907, firstMention: true, area_km2: 367.6,
      river: { uk: "Дунай", latin: "Danube" }, oblast: { uk: "Братиславський край", latin: "Bratislava Region" },
      landmark: { uk: "Братиславський град", latin: "Bratislava Castle" } } },
  { slug: "budapest", key: "World_Budapest", center: [47.4979, 19.0402], primaryLocale: "de",
    names: { uk: "Будапешт", en: "Budapest", de: "Budapest", pl: "Budapeszt", fr: "Budapest", es: "Budapest" },
    facts: { population: 1682308, populationYear: 2023, founded: 1873, firstMention: false, area_km2: 525.2,
      river: { uk: "Дунай", latin: "Danube" }, oblast: { uk: "Центральна Угорщина", latin: "Central Hungary" },
      landmark: { uk: "Будівля парламенту", latin: "Hungarian Parliament Building" } } },
  { slug: "paris", key: "World_Paris", center: [48.8566, 2.3522], primaryLocale: "fr",
    names: { uk: "Париж", en: "Paris", de: "Paris", pl: "Paryż", fr: "Paris", es: "París" },
    facts: { population: 2102650, populationYear: 2023, founded: -52, firstMention: false, area_km2: 105.4,
      river: { uk: "Сена", latin: "Seine" }, oblast: { uk: "Іль-де-Франс", latin: "Île-de-France" },
      landmark: { uk: "Ейфелева вежа", latin: "Eiffel Tower" } } },
  { slug: "lyon", key: "World_Lyon", center: [45.764, 4.8357], primaryLocale: "fr",
    names: { uk: "Ліон", en: "Lyon", de: "Lyon", pl: "Lyon", fr: "Lyon", es: "Lyon" },
    facts: { population: 522250, populationYear: 2023, founded: -43, firstMention: false, area_km2: 47.9,
      river: { uk: "Рона", latin: "Rhône" }, oblast: { uk: "Овернь-Рона-Альпи", latin: "Auvergne-Rhône-Alpes" },
      landmark: { uk: "Базиліка Фурв'єр", latin: "Fourvière Basilica" } } },
  { slug: "marseille", key: "World_Marseille", center: [43.2965, 5.3698], primaryLocale: "fr",
    names: { uk: "Марсель", en: "Marseille", de: "Marseille", pl: "Marsylia", fr: "Marseille", es: "Marsella" },
    facts: { population: 873076, populationYear: 2023, founded: -600, firstMention: false, area_km2: 240.6,
      river: { uk: "Ювон", latin: "Huveaune" }, oblast: { uk: "Прованс-Альпи-Лазурний Берег", latin: "Provence-Alpes-Côte d'Azur" },
      landmark: { uk: "Нотр-Дам-де-ла-Гард", latin: "Notre-Dame de la Garde" } } },
  { slug: "toulouse", key: "World_Toulouse", center: [43.6047, 1.4442], primaryLocale: "fr",
    names: { uk: "Тулуза", en: "Toulouse", de: "Toulouse", pl: "Tuluza", fr: "Toulouse", es: "Toulouse" },
    facts: { population: 504078, populationYear: 2023, founded: -100, firstMention: false, area_km2: 118.3,
      river: { uk: "Гаронна", latin: "Garonne" }, oblast: { uk: "Окситанія", latin: "Occitania" },
      landmark: { uk: "Базиліка Сен-Сернен", latin: "Basilica of Saint-Sernin" } } },
  { slug: "nice", key: "World_Nice", center: [43.7102, 7.262], primaryLocale: "fr",
    names: { uk: "Ніцца", en: "Nice", de: "Nizza", pl: "Nicea", fr: "Nice", es: "Niza" },
    facts: { population: 348085, populationYear: 2023, founded: -350, firstMention: false, area_km2: 71.9,
      river: { uk: "Пайон", latin: "Paillon" }, oblast: { uk: "Прованс-Альпи-Лазурний Берег", latin: "Provence-Alpes-Côte d'Azur" },
      landmark: { uk: "Англійська набережна", latin: "Promenade des Anglais" } } },
  { slug: "bordeaux", key: "World_Bordeaux", center: [44.8378, -0.5792], primaryLocale: "fr",
    names: { uk: "Бордо", en: "Bordeaux", de: "Bordeaux", pl: "Bordeaux", fr: "Bordeaux", es: "Burdeos" },
    facts: { population: 261804, populationYear: 2023, founded: -300, firstMention: false, area_km2: 49.4,
      river: { uk: "Гаронна", latin: "Garonne" }, oblast: { uk: "Нова Аквітанія", latin: "Nouvelle-Aquitaine" },
      landmark: { uk: "Площа Біржі", latin: "Place de la Bourse" } } },
  { slug: "nantes", key: "World_Nantes", center: [47.2184, -1.5536], primaryLocale: "fr",
    names: { uk: "Нант", en: "Nantes", de: "Nantes", pl: "Nantes", fr: "Nantes", es: "Nantes" },
    facts: { population: 320732, populationYear: 2023, founded: -70, firstMention: false, area_km2: 65.2,
      river: { uk: "Луара", latin: "Loire" }, oblast: { uk: "Пеї-де-ла-Луар", latin: "Pays de la Loire" },
      landmark: { uk: "Замок герцогів Бретані", latin: "Château des ducs de Bretagne" } } },
  { slug: "strasbourg", key: "World_Strasbourg", center: [48.5734, 7.7521], primaryLocale: "fr",
    names: { uk: "Страсбург", en: "Strasbourg", de: "Straßburg", pl: "Strasburg", fr: "Strasbourg", es: "Estrasburgo" },
    facts: { population: 291313, populationYear: 2023, founded: -12, firstMention: false, area_km2: 78.3,
      river: { uk: "Іль", latin: "Ill" }, oblast: { uk: "Гранд-Ест", latin: "Grand Est" },
      landmark: { uk: "Страсбурзький собор", latin: "Strasbourg Cathedral" } } },
  { slug: "brussels", key: "World_Brussels", center: [50.8503, 4.3517], primaryLocale: "fr",
    names: { uk: "Брюссель", en: "Brussels", de: "Brüssel", pl: "Bruksela", fr: "Bruxelles", es: "Bruselas" },
    facts: { population: 1249597, populationYear: 2023, founded: 979, firstMention: false, area_km2: 162.4,
      river: { uk: "Сенна", latin: "Senne" }, oblast: { uk: "Брюссельський столичний регіон", latin: "Brussels-Capital Region" },
      landmark: { uk: "Гран-Плас", latin: "Grand-Place" } } },
  { slug: "geneva", key: "World_Geneva", center: [46.2044, 6.1432], primaryLocale: "fr",
    names: { uk: "Женева", en: "Geneva", de: "Genf", pl: "Genewa", fr: "Genève", es: "Ginebra" },
    facts: { population: 203856, populationYear: 2023, founded: -121, firstMention: false, area_km2: 15.9,
      river: { uk: "Рона", latin: "Rhône" }, oblast: { uk: "Кантон Женева", latin: "Canton of Geneva" },
      landmark: { uk: "Же-до", latin: "Jet d'Eau" } } },
  { slug: "madrid", key: "World_Madrid", center: [40.4168, -3.7038], primaryLocale: "es",
    names: { uk: "Мадрид", en: "Madrid", de: "Madrid", pl: "Madryt", fr: "Madrid", es: "Madrid" },
    facts: { population: 3223334, populationYear: 2023, founded: 865, firstMention: true, area_km2: 604.3,
      river: { uk: "Мансанарес", latin: "Manzanares" }, oblast: { uk: "Автономна спільнота Мадрид", latin: "Community of Madrid" },
      landmark: { uk: "Королівський палац", latin: "Royal Palace" } } },
  { slug: "barcelona", key: "World_Barcelona", center: [41.3874, 2.1686], primaryLocale: "es",
    names: { uk: "Барселона", en: "Barcelona", de: "Barcelona", pl: "Barcelona", fr: "Barcelone", es: "Barcelona" },
    facts: { population: 1620343, populationYear: 2023, founded: -218, firstMention: false, area_km2: 101.4,
      river: { uk: "Бесос", latin: "Besòs" }, oblast: { uk: "Каталонія", latin: "Catalonia" },
      landmark: { uk: "Саграда Фамілія", latin: "Sagrada Família" } } },
  { slug: "valencia", key: "World_Valencia", center: [39.4699, -0.3763], primaryLocale: "es",
    names: { uk: "Валенсія", en: "Valencia", de: "Valencia", pl: "Walencja", fr: "Valence", es: "Valencia" },
    facts: { population: 807693, populationYear: 2023, founded: -138, firstMention: false, area_km2: 134.6,
      river: { uk: "Турія", latin: "Turia" }, oblast: { uk: "Валенсійська спільнота", latin: "Valencian Community" },
      landmark: { uk: "Місто мистецтв і наук", latin: "City of Arts and Sciences" } } },
  { slug: "seville", key: "World_Seville", center: [37.3891, -5.9845], primaryLocale: "es",
    names: { uk: "Севілья", en: "Seville", de: "Sevilla", pl: "Sewilla", fr: "Séville", es: "Sevilla" },
    facts: { population: 681998, populationYear: 2023, founded: -206, firstMention: false, area_km2: 140.8,
      river: { uk: "Гвадалквівір", latin: "Guadalquivir" }, oblast: { uk: "Андалусія", latin: "Andalusia" },
      landmark: { uk: "Хіральда", latin: "La Giralda" } } },
  { slug: "zaragoza", key: "World_Zaragoza", center: [41.6488, -0.8891], primaryLocale: "es",
    names: { uk: "Сарагоса", en: "Zaragoza", de: "Saragossa", pl: "Saragossa", fr: "Saragosse", es: "Zaragoza" },
    facts: { population: 681877, populationYear: 2023, founded: -14, firstMention: false, area_km2: 973.8,
      river: { uk: "Ебро", latin: "Ebro" }, oblast: { uk: "Арагон", latin: "Aragon" },
      landmark: { uk: "Базиліка дель Пілар", latin: "Basilica del Pilar" } } },
  { slug: "malaga", key: "World_Malaga", center: [36.7213, -4.4214], primaryLocale: "es",
    names: { uk: "Малага", en: "Malaga", de: "Málaga", pl: "Malaga", fr: "Malaga", es: "Málaga" },
    facts: { population: 586384, populationYear: 2023, founded: -770, firstMention: false, area_km2: 395.1,
      river: { uk: "Гвадальмедіна", latin: "Guadalmedina" }, oblast: { uk: "Андалусія", latin: "Andalusia" },
      landmark: { uk: "Алькасаба", latin: "Alcazaba" } } },
  { slug: "bilbao", key: "World_Bilbao", center: [43.263, -2.935], primaryLocale: "es",
    names: { uk: "Більбао", en: "Bilbao", de: "Bilbao", pl: "Bilbao", fr: "Bilbao", es: "Bilbao" },
    facts: { population: 346843, populationYear: 2023, founded: 1300, firstMention: false, area_km2: 41.3,
      river: { uk: "Нервйон", latin: "Nervión" }, oblast: { uk: "Країна Басків", latin: "Basque Country" },
      landmark: { uk: "Музей Гуггенхайма", latin: "Guggenheim Museum" } } },
  { slug: "lisbon", key: "World_Lisbon", center: [38.7223, -9.1393], primaryLocale: "es",
    names: { uk: "Лісабон", en: "Lisbon", de: "Lissabon", pl: "Lizbona", fr: "Lisbonne", es: "Lisboa" },
    facts: { population: 548703, populationYear: 2023, founded: -1200, firstMention: false, area_km2: 100.1,
      river: { uk: "Тежу", latin: "Tagus" }, oblast: { uk: "Лісабонський регіон", latin: "Lisbon Region" },
      landmark: { uk: "Вежа Белен", latin: "Belém Tower" } } },
  { slug: "porto", key: "World_Porto", center: [41.1579, -8.6291], primaryLocale: "es",
    names: { uk: "Порту", en: "Porto", de: "Porto", pl: "Porto", fr: "Porto", es: "Oporto" },
    facts: { population: 231962, populationYear: 2023, founded: -300, firstMention: false, area_km2: 41.4,
      river: { uk: "Дору", latin: "Douro" }, oblast: { uk: "Північний регіон", latin: "Norte Region" },
      landmark: { uk: "Міст Луїша I", latin: "Dom Luís I Bridge" } } },
  { slug: "rome", key: "World_Rome", center: [41.9028, 12.4964], primaryLocale: "es",
    names: { uk: "Рим", en: "Rome", de: "Rom", pl: "Rzym", fr: "Rome", es: "Roma" },
    facts: { population: 2748109, populationYear: 2023, founded: -753, firstMention: false, area_km2: 1287.4,
      river: { uk: "Тибр", latin: "Tiber" }, oblast: { uk: "Лаціо", latin: "Lazio" },
      landmark: { uk: "Колізей", latin: "Colosseum" } } },
  { slug: "milan", key: "World_Milan", center: [45.4642, 9.19], primaryLocale: "es",
    names: { uk: "Мілан", en: "Milan", de: "Mailand", pl: "Mediolan", fr: "Milan", es: "Milán" },
    facts: { population: 1371498, populationYear: 2023, founded: -590, firstMention: false, area_km2: 181.8,
      river: { uk: "Олона", latin: "Olona" }, oblast: { uk: "Ломбардія", latin: "Lombardy" },
      landmark: { uk: "Міланський собор", latin: "Duomo di Milano" } } },
  { slug: "naples", key: "World_Naples", center: [40.8518, 14.2681], primaryLocale: "es",
    names: { uk: "Неаполь", en: "Naples", de: "Neapel", pl: "Neapol", fr: "Naples", es: "Nápoles" },
    facts: { population: 913462, populationYear: 2023, founded: -470, firstMention: false, area_km2: 119.0,
      river: { uk: "Себето", latin: "Sebeto" }, oblast: { uk: "Кампанія", latin: "Campania" },
      landmark: { uk: "Везувій", latin: "Mount Vesuvius" } } },
  { slug: "florence", key: "World_Florence", center: [43.7696, 11.2558], primaryLocale: "es",
    names: { uk: "Флоренція", en: "Florence", de: "Florenz", pl: "Florencja", fr: "Florence", es: "Florencia" },
    facts: { population: 361619, populationYear: 2023, founded: -59, firstMention: false, area_km2: 102.4,
      river: { uk: "Арно", latin: "Arno" }, oblast: { uk: "Тоскана", latin: "Tuscany" },
      landmark: { uk: "Санта-Марія-дель-Фйоре", latin: "Florence Cathedral" } } },
  { slug: "venice", key: "World_Venice", center: [45.4408, 12.3155], primaryLocale: "es",
    names: { uk: "Венеція", en: "Venice", de: "Venedig", pl: "Wenecja", fr: "Venise", es: "Venecia" },
    facts: { population: 250369, populationYear: 2023, founded: 421, firstMention: false, area_km2: 414.6,
      river: { uk: "Гранд-канал", latin: "Grand Canal" }, oblast: { uk: "Венето", latin: "Veneto" },
      landmark: { uk: "Площа Сан-Марко", latin: "St Mark's Square" } } },
  { slug: "turin", key: "World_Turin", center: [45.0703, 7.6869], primaryLocale: "es",
    names: { uk: "Турин", en: "Turin", de: "Turin", pl: "Turyn", fr: "Turin", es: "Turín" },
    facts: { population: 847287, populationYear: 2023, founded: -28, firstMention: false, area_km2: 130.2,
      river: { uk: "По", latin: "Po" }, oblast: { uk: "П'ємонт", latin: "Piedmont" },
      landmark: { uk: "Моле Антонелліана", latin: "Mole Antonelliana" } } },
  { slug: "london", key: "World_London", center: [51.5074, -0.1278], primaryLocale: "en",
    names: { uk: "Лондон", en: "London", de: "London", pl: "Londyn", fr: "Londres", es: "Londres" },
    facts: { population: 8866180, populationYear: 2022, founded: 47, firstMention: false, area_km2: 1572.0,
      river: { uk: "Темза", latin: "Thames" }, oblast: { uk: "Великий Лондон", latin: "Greater London" },
      landmark: { uk: "Тауерський міст", latin: "Tower Bridge" } } },
  { slug: "manchester", key: "World_Manchester", center: [53.4808, -2.2426], primaryLocale: "en",
    names: { uk: "Манчестер", en: "Manchester", de: "Manchester", pl: "Manchester", fr: "Manchester", es: "Mánchester" },
    facts: { population: 568996, populationYear: 2022, founded: 79, firstMention: false, area_km2: 115.6,
      river: { uk: "Ірвелл", latin: "Irwell" }, oblast: { uk: "Великий Манчестер", latin: "Greater Manchester" },
      landmark: { uk: "Стадіон Олд Траффорд", latin: "Old Trafford" } } },
  { slug: "edinburgh", key: "World_Edinburgh", center: [55.9533, -3.1883], primaryLocale: "en",
    names: { uk: "Единбург", en: "Edinburgh", de: "Edinburgh", pl: "Edynburg", fr: "Édimbourg", es: "Edimburgo" },
    facts: { population: 526470, populationYear: 2022, founded: 1130, firstMention: false, area_km2: 264.0,
      river: { uk: "Вотер-оф-Літ", latin: "Water of Leith" }, oblast: { uk: "Шотландія", latin: "Scotland" },
      landmark: { uk: "Единбурзький замок", latin: "Edinburgh Castle" } } },
  { slug: "dublin", key: "World_Dublin", center: [53.3498, -6.2603], primaryLocale: "en",
    names: { uk: "Дублін", en: "Dublin", de: "Dublin", pl: "Dublin", fr: "Dublin", es: "Dublín" },
    facts: { population: 592713, populationYear: 2022, founded: 841, firstMention: false, area_km2: 117.8,
      river: { uk: "Ліффі", latin: "Liffey" }, oblast: { uk: "Ленстер", latin: "Leinster" },
      landmark: { uk: "Трініті-коледж", latin: "Trinity College" } } },
  { slug: "amsterdam", key: "World_Amsterdam", center: [52.3676, 4.9041], primaryLocale: "en",
    names: { uk: "Амстердам", en: "Amsterdam", de: "Amsterdam", pl: "Amsterdam", fr: "Amsterdam", es: "Ámsterdam" },
    facts: { population: 921402, populationYear: 2023, founded: 1275, firstMention: true, area_km2: 219.3,
      river: { uk: "Амстел", latin: "Amstel" }, oblast: { uk: "Північна Голландія", latin: "North Holland" },
      landmark: { uk: "Канали Амстердама", latin: "Amsterdam Canals" } } },
  { slug: "rotterdam", key: "World_Rotterdam", center: [51.9244, 4.4777], primaryLocale: "en",
    names: { uk: "Роттердам", en: "Rotterdam", de: "Rotterdam", pl: "Rotterdam", fr: "Rotterdam", es: "Róterdam" },
    facts: { population: 664311, populationYear: 2023, founded: 1270, firstMention: false, area_km2: 324.1,
      river: { uk: "Ньїве-Маас", latin: "Nieuwe Maas" }, oblast: { uk: "Південна Голландія", latin: "South Holland" },
      landmark: { uk: "Міст Еразма", latin: "Erasmus Bridge" } } },
  { slug: "copenhagen", key: "World_Copenhagen", center: [55.6761, 12.5683], primaryLocale: "en",
    names: { uk: "Копенгаген", en: "Copenhagen", de: "Kopenhagen", pl: "Kopenhaga", fr: "Copenhague", es: "Copenhague" },
    facts: { population: 653664, populationYear: 2023, founded: 1043, firstMention: true, area_km2: 88.3,
      river: { uk: "Ересунн", latin: "Øresund" }, oblast: { uk: "Столичний регіон", latin: "Capital Region" },
      landmark: { uk: "Русалонька", latin: "The Little Mermaid" } } },
  { slug: "stockholm", key: "World_Stockholm", center: [59.3293, 18.0686], primaryLocale: "en",
    names: { uk: "Стокгольм", en: "Stockholm", de: "Stockholm", pl: "Sztokholm", fr: "Stockholm", es: "Estocolmo" },
    facts: { population: 984748, populationYear: 2023, founded: 1252, firstMention: true, area_km2: 188.0,
      river: { uk: "Норрстрем", latin: "Norrström" }, oblast: { uk: "Стокгольмський лен", latin: "Stockholm County" },
      landmark: { uk: "Гамла Стан", latin: "Gamla Stan" } } },
  { slug: "oslo", key: "World_Oslo", center: [59.9139, 10.7522], primaryLocale: "en",
    names: { uk: "Осло", en: "Oslo", de: "Oslo", pl: "Oslo", fr: "Oslo", es: "Oslo" },
    facts: { population: 709037, populationYear: 2023, founded: 1040, firstMention: false, area_km2: 454.0,
      river: { uk: "Акерсельва", latin: "Akerselva" }, oblast: { uk: "Осло", latin: "Oslo County" },
      landmark: { uk: "Оперний театр", latin: "Oslo Opera House" } } },
  { slug: "helsinki", key: "World_Helsinki", center: [60.1699, 24.9384], primaryLocale: "en",
    names: { uk: "Гельсінкі", en: "Helsinki", de: "Helsinki", pl: "Helsinki", fr: "Helsinki", es: "Helsinki" },
    facts: { population: 664000, populationYear: 2023, founded: 1550, firstMention: false, area_km2: 214.3,
      river: { uk: "Вантаа", latin: "Vantaa" }, oblast: { uk: "Уусімаа", latin: "Uusimaa" },
      landmark: { uk: "Кафедральний собор", latin: "Helsinki Cathedral" } } },
  { slug: "athens", key: "World_Athens", center: [37.9838, 23.7275], primaryLocale: "en",
    names: { uk: "Афіни", en: "Athens", de: "Athen", pl: "Ateny", fr: "Athènes", es: "Atenas" },
    facts: { population: 643452, populationYear: 2023, founded: -1400, firstMention: false, area_km2: 38.96,
      river: { uk: "Кіфісос", latin: "Kifisos" }, oblast: { uk: "Аттика", latin: "Attica" },
      landmark: { uk: "Акрополь", latin: "Acropolis" } } },
  { slug: "riga", key: "World_Riga", center: [56.9496, 24.1052], primaryLocale: "en",
    names: { uk: "Рига", en: "Riga", de: "Riga", pl: "Ryga", fr: "Riga", es: "Riga" },
    facts: { population: 605802, populationYear: 2023, founded: 1201, firstMention: false, area_km2: 304.0,
      river: { uk: "Даугава", latin: "Daugava" }, oblast: { uk: "Ризький регіон", latin: "Riga Region" },
      landmark: { uk: "Будинок Чорноголових", latin: "House of the Blackheads" } } },
  { slug: "vilnius", key: "World_Vilnius", center: [54.6872, 25.2797], primaryLocale: "en",
    names: { uk: "Вільнюс", en: "Vilnius", de: "Wilna", pl: "Wilno", fr: "Vilnius", es: "Vilna" },
    facts: { population: 581475, populationYear: 2023, founded: 1323, firstMention: true, area_km2: 401.0,
      river: { uk: "Нярис", latin: "Neris" }, oblast: { uk: "Вільнюський повіт", latin: "Vilnius County" },
      landmark: { uk: "Вежа Гедиміна", latin: "Gediminas' Tower" } } },
  { slug: "tallinn", key: "World_Tallinn", center: [59.437, 24.7536], primaryLocale: "en",
    names: { uk: "Таллінн", en: "Tallinn", de: "Tallinn", pl: "Tallin", fr: "Tallinn", es: "Tallin" },
    facts: { population: 461000, populationYear: 2023, founded: 1219, firstMention: true, area_km2: 159.2,
      river: { uk: "Пирита", latin: "Pirita" }, oblast: { uk: "Харьюмаа", latin: "Harju County" },
      landmark: { uk: "Старе місто", latin: "Tallinn Old Town" } } },
];

export const WORLD_CITY_BY_SLUG: Record<string, WorldCity> = Object.fromEntries(
  WORLD_CITIES.map((c) => [c.slug, c]),
);

/** Міста, для яких ця локаль — «домашня» (перелінковка «поблизу»). */
export function worldCitiesForLocale(locale: AppLocale): WorldCity[] {
  const home = WORLD_CITIES.filter((c) => c.primaryLocale === locale);
  return home.length ? home : WORLD_CITIES.slice(0, 6);
}
